### ISSUE TITLE
Error on launch for iOS (Running on Device)

### ISSUE THREAD

**Issue by frederickjjoubert** [ConnectyCube/connectycube-reactnative-samples#10]
I built the base project 'RNVideoChat' to an iOS device and got the following error:

Please note building to an android device is working fine for me.

'Unknown arguement type '__attribute__' in method -[RCTAppState getCurrentAppState:error]. Extend RCTConvert to support this type.'

Attached is a screenshot of the error.

![IMG_6171](https://user-images.githubusercontent.com/20562845/66147163-1f6aff00-e5c3-11e9-894a-2cc7c1107d4e.png)

Steps to reproduce: 
- clone 'connectycube-reactnative-samples'
- follow readme QuickStart instructions to set up RNVideoChat project
- build to device (iOS)

The only recent change to my develop environment that I can think of that may produce an incompatibility is that I am using Xcode 11.

Thanks for the help!

**Comment by Mike-Van** [comment]
I'm having the same problem for building the chatting sample. Have you found any solution to this? Thanks

**Comment by frederickjjoubert** [comment]
@Mike-Van no solution yet

**Comment by DaveLomber** [comment]
@Mike-Van  @frederickjjoubert we will check and let you know tomorrow

**Comment by ccvlad** [comment]
Try our last code. We updated react-native-webrtc lib in RNVideoChat.

Tested on Simulator (iOS 13.0), iPhone X (iOS 13.0) and iPhone 6 (iOS 10.1.1) with Xcode 11.1. Can't reproduce.

- git clone ...
- cd connectycube-reactnative-samples/RNVideoChat
- npm install
- run build in RNVideoChat.xcworkspace (or 'npm run ios')

Please provide more info if problem doesn't solve (environments, device, logs if exist).
