### ISSUE TITLE
When using  any type of earphone cable or bluetooth no working

### ISSUE THREAD

**Issue by uendar** [ConnectyCube/connectycube-reactnative-samples#101]
When i try to use earphone cable or bluetooth  i do not listen at all the other person

**Comment by ccvlad** [comment]
Hi @uendar 
We did not test sound from earphone cable or bluetooth in our RNVideoChat.
Try to switch back from speakerphone :
```javascript
import InCallManager from 'react-native-incall-manager';

InCallManager. setSpeakerphoneOn(false);
// or InCallManager. setForceSpeakerphoneOn(false);
```
You may find the info you need in the [react-native-incall-manager](https://github.com/react-native-webrtc/react-native-incall-manager). We use this library to [switch on/off](https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNVideoChat/src/services/call-service.js#L98) the speaker.

Also have a look on this issue - https://github.com/react-native-webrtc/react-native-incall-manager/issues/117

**Comment by banshiAnton** [comment]
Seems there is no much activity out there. Closing the issue as stale. If it’s still actual - please raise a new one.
