### ISSUE TITLE
 When the video is disabled on ongoing call, Last image still been shown in caller and receiver.

### ISSUE THREAD

**Issue by sapkotamadhusudan** [ConnectyCube/connectycube-reactnative-samples#103]
I'm having issue while disabling video in active call. 

When i muted the video (from caller/receiver) using
```
this._session.mute('video');
```
muted video screen will display the last visible image.  I think it should be shown black screen.
I've also tested this issue in this sample application (RNVideoChat) and the issue still persist.

**Comment by DaveLomber** [comment]
The recommended way is to send system messages to other users along with mute/unmute

https://developers.connectycube.com/js/messaging?id=system-messages

so other user once received the system message - can hide your video view 

for example

```
const userId = 123234;

ConnectyCube.chat.sendSystemMessage(userId, {videommute: true});

...

ConnectyCube.chat.sendSystemMessage(userId, {videommute: false});
```
