### ISSUE TITLE
How to change Android push notification icon

### ISSUE THREAD

**Issue by sjwoodard** [ConnectyCube/connectycube-reactnative-samples#106]
I'm sending push notification via the ConnectyCube API. Android users notifications have the default Android icon. Where can I change that icon?

Thanks!

**Comment by ccvlad** [comment]
Hi @sjwoodard 
Usually an app's icons use, but some versions of Android (Oreo or Pie, do not really remember) need two-colors icon for notification. It doesn't related to ConnectyCube API.
Did you set icons for your app? You are able to find the information via Google.

**Comment by sjwoodard** [comment]
I have the app icons set, and I'm seeing the issue on Andoird 8-10.

I was thinking the local notifications are called from within the ConnectyCube library which then uses https://github.com/zo0r/react-native-push-notification. The react-native-push-notification docs show how to change the icon, but I couldn't figure out how to pass the settings using the ConnectyCube React sample code.

**Comment by ccvlad** [comment]
Here we have icons in working app:
<img width="1090" alt="Снимок экрана 2020-08-10 в 11 33 05" src="https://user-images.githubusercontent.com/43810932/89765765-a0f2be00-daff-11ea-9e0a-671bf189a71a.png">

**Comment by sjwoodard** [comment]
thanks for the help!
