### ISSUE TITLE
How to Call app when app has Closed (IOS & Android)?

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#107]
### Description:
* I want user to sign in. After user closes app. I want the user to still receive phone call while app is closed. 
* "Closed" meaning app is completely off, not minimised. 
* I am using react-native-callkeep. Using CallKit. So right now user sees the IOS/Android call UI but only while app is open.
* I want the user to see the Call UI via CallKit after the app has closed. (app not active of in background, completely closed).
---

#### *How does one do this with ConnectyCube RNVideoChat?*

**Comment by banshiAnton** [comment]
Hi @stephanoparaskeva you can use from IOS VOIP https://developers.connectycube.com/reactnative/push-notifications?id=callkit-and-voip-push-notifications
for Android you can create push event  https://developers.connectycube.com/js/videocalling?id=receive-a-call-in-background

**Comment by stephanoparaskeva** [comment]
> Hi @stephanoparaskeva you can use from IOS VOIP https://developers.connectycube.com/reactnative/push-notifications?id=callkit-and-voip-push-notifications
> for Android you can create push event https://developers.connectycube.com/js/videocalling?id=receive-a-call-in-background

Does this work when the app is completely closed?

If user is logged out after 2 hours of inactivity, how do you get this to work after app being off for > 2 hours?

**Comment by banshiAnton** [comment]
Yes, after app is launched you need to authorization again (init sdk and createSession with credentials)
https://developers.connectycube.com/js/authentication-and-users?id=create-session-token

If you use p2p calls you need connect to chat and set call listeners https://developers.connectycube.com/js/videocalling?id=accept-a-call

If you use videocalling-conference you need put roomId to push message (https://developers.connectycube.com/js/push-notifications?id=send-push-notifications) and then join to that room https://developers.connectycube.com/js/videocalling-conference?id=join-video-room

**Comment by stephanoparaskeva** [comment]
> Yes, after app is launched you need to authorization again (init sdk and createSession with credentials)
> https://developers.connectycube.com/js/authentication-and-users?id=create-session-token
> 
> If you use p2p calls you need connect to chat and set call listeners https://developers.connectycube.com/js/videocalling?id=accept-a-call
> 
> If you use videocalling-conference you need put roomId to push message (https://developers.connectycube.com/js/push-notifications?id=send-push-notifications) and then join to that room https://developers.connectycube.com/js/videocalling-conference?id=join-video-room

Can we have an example implementation with `react-native-callkeep` of launching app after being closed and Receiving video call?

**Comment by banshiAnton** [comment]
Unfortunately we don't have react-native sample with implemented react-native-callkeep
Perhaps we will do it in the future

**Comment by yuduth88** [comment]
> Unfortunately we don't have react-native sample with implemented react-native-callkeep
> Perhaps we will do it in the future

please create sample for react-native-callkeep integration for voip notification (background and kill apps)
