### ISSUE TITLE
Switch Camera freezes on Android -> IOS Calls for Remote Stream 

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#108]
Sometimes when I change camera mode from front to back or vice versa On Android Device, the stream freezes on the Remote IOS device.

The call is between an Android and IOS device. This also sometimes happens on Android -> Android Calls. 

When I change camera on IOS device, it always works fine.

## Steps
* Call between IOS and Android (or Android and Android)
* Change camera mode on Android device
* IOS Device Remote video Stream Freezes.

## Code
```JavaScript
 const toggleCamera = () => {
    setIsFrontCamera(!isFrontCamera);
    localStream[0]?.stream
      ?.getVideoTracks?.()
      .forEach((track: Track) => track._switchCamera());
  };
```

**Comment by ccvlad** [comment]
Please provide the device info (Galaxy S6 with Nougat?)
We will try to test.

**Comment by stephanoparaskeva** [comment]
> Please provide the device info (Galaxy S6 with Nougat?)
> We will try to test.

### Info
```
Device name: Galaxy S6
Model: SM-G920F
Android Version: 7.0 (Nougat)
```

**Comment by stephanoparaskeva** [comment]
Any progress?

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
