### ISSUE TITLE
 connectycute support expo?

### ISSUE THREAD

**Issue by kkchickha** [ConnectyCube/connectycube-reactnative-samples#112]
![Screen Shot 2563-08-11 at 14 50 47](https://user-images.githubusercontent.com/701643/89876885-7da43d80-dbe9-11ea-829f-c90cf9152f27.png)
**I have installed package import ConnectyCube from "react-native-connectycube";
But cannot run** 
![Screen Shot 2563-08-11 at 15 49 17](https://user-images.githubusercontent.com/701643/89877471-59952c00-dbea-11ea-8f7f-19f05c7ee5b6.png)

**Comment by ccvlad** [comment]
Did you install "react-native-connectycube" via NPM or YARN? The VS Code shows that it can not see the module.

**Comment by kkchickha** [comment]
> Did you install "react-native-connectycube" via NPM or YARN? The VS Code shows that it can not see the module.

Hi ccvlad I user Yarn add react-native-connectycube

**Comment by ccvlad** [comment]
I used to run the "react-native-connectycube" about year ago and it was working. Let us check and we will update you.

**Comment by ccvlad** [comment]
Did you start project from scratch  or tried to modify one of current samples?

**Comment by kkchickha** [comment]
> Did you start project from scratch or tried to modify one of current samples?

I tried testing both but couldn't run through expo either.
![S__3489797](https://user-images.githubusercontent.com/701643/89883455-5e5dde00-dbf2-11ea-9482-8a0630e664e4.jpg)

**Comment by kkchickha** [comment]
> I used to run the "react-native-connectycube" about year ago and it was working. Let us check and we will update you.
How did you check, I can not run on exo project

**Comment by kkchickha** [comment]
How do you use sdk version? and 
May I have a look at your package.json?
Thank you

**Comment by ccvlad** [comment]
Of course, see:
```javascript
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~38.0.8",
    "expo-status-bar": "^1.0.2",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-connectycube": "^3.6.2",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true
}
```

**Comment by kkchickha** [comment]
Hi, I'm not sure I understand that sdk can be run on expo. 
[https://expo.canny.io/feature-requests/p/webrtc](url)
Do you have a sample source code to try out?

**Comment by ccvlad** [comment]
Hi, @kkchickha 
Check the latest release of the [react-native-connectycube](https://github.com/ConnectyCube/connectycube-js-sdk-releases/releases/tag/3.7.2)

https://www.npmjs.com/package/react-native-connectycube
