### ISSUE TITLE
In a P2P video call, switchMediaTracks is not working?

### ISSUE THREAD

**Issue by technasir** [ConnectyCube/connectycube-reactnative-samples#113]
Hi,
In a peer to peer video call, when i use below code to to switch my video camera,
`this.session
    .switchMediaTracks(constraints)
    .then(stream => {
     this.setState({localStream: stream})
     })
    .catch(error => {});`
- The local stream gets updated successfully but the remote stream on the other device does not gets updated 
   and gets frozen.
 I went to the connectycube react native code sample to see how they switch a video camera, they used this 
 code to switch the video camera?
 `localStream.getVideoTracks().forEach(track => track._switchCamera());`
-  Why was this above code is used instead of session.switchMediaTracks() that is available on the docs. 
    Thanks.

**Comment by ccvlad** [comment]
For React Native we use this code (`import ConnectyCube from 'react-native-connectycube'`):
https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNVideoChat/src/services/call-service.js#L94
The **switchMediaTracks** is used for other JS projects (`import ConnectyCube from 'connectycube'`).
We use one codebase for all platforms (JS, NodeJS, Cordova, React Native, NativeScript).
I see that we have not docs for the switch cameras in RN. We will add. Thank you!

**Comment by technasir** [comment]
There is also this line of code that is used in the connectycube react native code sample that i can't find in the docs:
https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/b318570a0e5ceef521d8234b9f22fac23ee6f842/RNVideoChat/src/services/call-service.js#L75
Please add information about this too in the docs.

**Comment by ccvlad** [comment]
> There is also this line of code that is used in the connectycube react native code sample that i can't find in the docs:
> https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/b318570a0e5ceef521d8234b9f22fac23ee6f842/RNVideoChat/src/services/call-service.js#L75
> 
> 
> Please add information about this too in the docs.

```javascript
// clear a WebRTC session by ID
clearSession(sessionId) {
  delete this.sessions[sessionId];
}
```

**Comment by ccvlad** [comment]
Closed. Create a separate issue for a new question/problem if need.
