### ISSUE TITLE
Facebook Auth

### ISSUE THREAD

**Issue by paluch** [ConnectyCube/connectycube-reactnative-samples#114]
Code:
const userCredentials = { provider: 'facebook', keys: {token: 'XXXXXXXX'} };
let res = await ConnectyCube.login(userCredentials);

package.json
"react-native-connectycube": "^3.4.0",

error:
TypeError: Network request failed

-----

if I put the userCredentials on purpose wrongly, I get feedback from the server.

**Comment by DaveLomber** [comment]
@paluch please post the complete response from the server in both cases - correct credentials and a wrong one

**Comment by banshiAnton** [comment]
Seems there is no much activity out there. Closing the issue as stale. If it’s still actual - please raise a new one.
