### ISSUE TITLE
Opponent Video is not showing when connected to the VPN in both devices

### ISSUE THREAD

**Issue by sapkotamadhusudan** [ConnectyCube/connectycube-reactnative-samples#116]
Hi,
I'm using the ConnectyCube SDK to develop the communication application and i'm using my office VPN connection to work remotely. But when i try to work with ConnectyCube Video calling feature with VPN connection, opponent video is not loaded. 

I've tried using this sample **(RNVideoChat)** and the issue still occurs. 
I've attached the logs of both of my device using this sample application **(RNVideoChat)**. 

Brand: Samsung Galaxy S8+
OS: Android 9

[Log File](https://drive.google.com/file/d/1RzZehW_kp8ir_CZu43D8kVtJDplErJZq/view?usp=sharing)

Brand: MI Redimi Note 7 Pro
OS: Android 9

[Log File](https://drive.google.com/file/d/1IPDevI4ZNLx2OBnx_seMGEvI8mawdCM2/view?usp=sharing)

**Comment by DaveLomber** [comment]
In general - we do not have any VPN related restrictions, 
probably it's =more about some blocked ports etc

Could you please do couple tests for us about connectivity environment, this will help us analyze the situation 

#1
- Go to https://test.webrtc.org/?stunURI=stun%3Astun.l.google.com%3A19302&turnURI=turn%3Aturn.connectycube.com%3A5349&turnUsername=connectycube&turnCredential=4c29501ca9207b7fb9c4b4b6b04faeb1
- click Start
- wait for results and share screenshot with us

#2
- Go to https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
- add the following 3 additional servers

stun:turn.connectycube.com

turn:turn.connectycube.com:5349?transport=udp
connectycube
4c29501ca9207b7fb9c4b4b6b04faeb1

turn:turn.connectycube.com:5349?transport=tcp
connectycube
4c29501ca9207b7fb9c4b4b6b04faeb1

- click Gather Candidates
- wait for results and share screenshot with us

**Comment by sapkotamadhusudan** [comment]
@DaveLomber i've followed your instruction on my mobile device with VPN connectivity on. And the results are:
![Mobile_Debug_1](https://user-images.githubusercontent.com/20489827/90473734-5a2a4700-e143-11ea-9c66-ee29584c86b5.jpg)

![Mobile_Debug_0](https://user-images.githubusercontent.com/20489827/90474200-74b0f000-e144-11ea-9804-f33bb0489352.jpg)

![Mobile_Debug_01](https://user-images.githubusercontent.com/20489827/90474353-cd808880-e144-11ea-923a-5d285bf2f5b5.jpg)

**Comment by DaveLomber** [comment]
Thanks for the reports provided 

So seems ICE candidates can be gathered (which is also confirmed by logs provided)

But then, by some reason, ICE connection is failed when it tried to connect each other:

```
[Mon Aug 17 2020 18:19:47.200]  LOG      [VideoChat]: onIceConnectionStateCallback: failed
```

One more check please - does https://appr.tc work at your env?

**Comment by sapkotamadhusudan** [comment]
@DaveLomber Yes, https://appr.tc/ works at my env. 
And one more thing to add (idk it would be helpful or not). 
i did also tested the **android-messenger-app** from sample, It works while my VPN is on.

**Comment by ccvlad** [comment]
Closed. Please, create a new issue if the problem still exist.
