### ISSUE TITLE
There is a latency of approx. 2 seconds in video call

### ISSUE THREAD

**Issue by AbhiSri2020** [ConnectyCube/connectycube-reactnative-samples#118]
I am working on the sample code of video chat and I noticed a voice/video reaches after 2 seconds on the other side.

this is my configuration:

static MEDIA_OPTIONS = {
    audio: true, video: {
      facingMode: 'user',
      width: { min: 144, ideal: 1280, max: 1980 },
      height: { min: 176, ideal: 720, max: 1080 }
    }
  };

**Comment by DaveLomber** [comment]
Is it p2p or Conferencing code sample?

**Comment by AbhiSri2020** [comment]
It is p2p, just 2 person

**Comment by DaveLomber** [comment]
this one? https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat

you are trying to use HD quality, 
could you try some SD/LD and let us know how it works

**Comment by AbhiSri2020** [comment]
Yes I am using sample code from [https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat]

these are configuration that I have tested:

 ```
static MEDIA_OPTIONS = {
    audio: true, video: {
      facingMode: 'user',
      width: 1980,
      height: 1080
    }
 };
```

`  static MEDIA_OPTIONS = {
    audio: true, video: {
      facingMode: 'user',
      width: Dimensions.get("window").width,
      height: Dimensions.get("window").height
    }
  };
`

`  static MEDIA_OPTIONS = {
    audio: true, video: {
      facingMode: 'user',
      width: 144,
      height: 176
    }
  };
`

But still, I am facing latency of at least 2 seconds which increases with time.

Moreover, my internet bandwidth is: download: 10.7mbps  upload: 1mbps.
While video chatting internet speed (consumption as shown on the status bar) is 30kbps to 70kbps on the basis of quality, whereas while playing youtube video speed is 500+ kbps (for HD)

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
