### ISSUE TITLE
How to remove listeners

### ISSUE THREAD

**Issue by AbhiSri2020** [ConnectyCube/connectycube-reactnative-samples#119]
I am using the sample code provided in the master branch and made some changes so now I have same kind of listeners set up at different screens, as

Parrent has listeners: 
_onCallListener, _onAcceptCallListener, this._onRejectCallListener, this._onStopCallListener, this._onUserNotAnswerListener, _onRemoteStreamListener
and grandchild also has the same listeners except for _onCallListener.

parent's componentDidMount code
```
        ConnectyCube.videochat.onCallListener = this._onCallListener;
        ConnectyCube.videochat.onAcceptCallListener = this._onAcceptCallListener;
        ConnectyCube.videochat.onRejectCallListener = this._onRejectCallListener;
        ConnectyCube.videochat.onStopCallListener = this._onStopCallListener;
        ConnectyCube.videochat.onUserNotAnswerListener = this._onUserNotAnswerListener;
        ConnectyCube.videochat.onRemoteStreamListener = this._onRemoteStreamListener;

```
grandchild componentDidMount code (_onCallListener is not present here)
```
        ConnectyCube.videochat.onAcceptCallListener = this._onAcceptCallListener;
        ConnectyCube.videochat.onRejectCallListener = this._onRejectCallListener;
        ConnectyCube.videochat.onStopCallListener = this._onStopCallListener;
        ConnectyCube.videochat.onUserNotAnswerListener = this._onUserNotAnswerListener;
        ConnectyCube.videochat.onRemoteStreamListener = this._onRemoteStreamListener;
```
and conponentWillUnmount
```
        ConnectyCube.videochat._onAcceptCallListener = this._onAcceptCallListener
        ConnectyCube.videochat._onRejectCallListener = this._onRejectCallListener
        ConnectyCube.videochat._onStopCallListener = this._onStopCallListener
        ConnectyCube.videochat._onUserNotAnswerListener = this._onUserNotAnswerListener
        ConnectyCube.videochat._onRemoteStreamListener = this._onRemoteStreamListener
```

but when I unmount the grandChild and moved to the parent screen then also grandChild's _onRemoteStreamListener is called instead of the parent's _onRemoteStreamListener.

**Comment by banshiAnton** [comment]
Hi @AbhiSri2020 our sdk architecture does not provide that you have more then one videochat listeners
You need to set up listeners in one place (it can be service) in your app

**Comment by banshiAnton** [comment]
Hi @AbhiSri2020 do you need help ?

**Comment by aravi365** [comment]
> Hi @AbhiSri2020 do you need help ?

@banshiAnton  could you please help me to write the listeners for functional components
