### ISSUE TITLE
Question: Dose redux is compulsory to use for rect native app for this chat lib implementation???

### ISSUE THREAD

**Issue by kp72-dev** [ConnectyCube/connectycube-reactnative-samples#120]
**Question: Dose redux is compulsory to use for rect native app for this chat lib implementation???**

**Comment by banshiAnton** [comment]
Hi @kp72-dev , you can create your own project without redux
In this sample we use redux because it is much easier than use just react state or context

**Comment by kp72-dev** [comment]
> Hi @kp72-dev , you can create your own project without redux
> In this sample we use redux because it is much easier than use just react state or context

thanx for responding.
i am facing error called native module null
![Simulator Screen Shot - iPhone 8 - 2020-09-07 at 14 31 18](https://user-images.githubusercontent.com/70267992/92369569-cd0d5900-f116-11ea-9ee8-87c00606e6e6.png)

**Comment by banshiAnton** [comment]
Probably react-native-webrtc lib is not linked, check this guide https://github.com/react-native-webrtc/react-native-webrtc#installation
Is it chat sample ?

**Comment by kp72-dev** [comment]
its my demo app where i just installed lib and imported sdk as mention in doc.
@banshiAnton

**Comment by banshiAnton** [comment]
@kp72-dev our sdk include react-native-webrtc as dependence for p2p calling and conference
We don't have separate sdk for chat and calls
