### ISSUE TITLE
Not able to send message - [Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'this.Transport.prototype')]

### ISSUE THREAD

**Issue by Arveti** [ConnectyCube/connectycube-reactnative-samples#122]
Hi,
I am trying to send message through connectycube javascript sdk for react native. And I am getting the following error -
[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'this.Transport.prototype')] at 
- node_modules/react-native-connectycube/lib/messaging/cubeChat.js:306:19 in ChatService#send.

My code -

```
let toSendMessage = {
      type: "chat",
      body: message[0].text,
      extension: {
        save_to_history: 1,
        dialog_id: targetUserDetails.dialogId,
        date_sent: new Date().getTime(),
      },
      markable: 1,
    };

    const msgId = await ConnectyCube.chat.send(
      targetUserDetails.id,
      toSendMessage
    );
```

Requesting to please help. Possibly asap due to time sensitivity.

**Comment by DaveLomber** [comment]
Make sure you performed chat connect in order to send messages

https://developers.connectycube.com/js/messaging?id=connect-to-chat

**Comment by Arveti** [comment]
Ok, will try that out and let you know. Thanks

**Comment by Arveti** [comment]
It's working. Thanks.
