### ISSUE TITLE
Bug - Get Random Call from User. Even if user not logged in.

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#124]
* log in as Alice 
* another mobile I log in as Ciri

Leave it for a while. 
Alice (IOS) starts receiving calls from BOB.

How can this even happen?
This will effect our ability to go into production.

**Comment by ccvlad** [comment]
There are four hardcoded users in the RN VideoSample. Someone are testing the sample at the same time with you.
You can create your own [application](https://connectycube.com/signup/) with separate users.

**Comment by stephanoparaskeva** [comment]
> There are four hardcoded users in the RN VideoSample. Someone are testing the sample at the same time with you.
> You can create your own [application](https://connectycube.com/signup/) with separate users.

Ahh, I see that must be correct.
