### ISSUE TITLE
App crashed when call initiated from ConnectyCube web sample (Firefox)

### ISSUE THREAD

**Issue by sapkotamadhusudan** [ConnectyCube/connectycube-reactnative-samples#125]
Hi,
I'm using the **ConnectyCube JS SDK** to develop the communication application and when i initiated call from Web application using **ConnectyCube JS SDK** from **Firefox** browser to react native application, React native application crashes.

I've tried using this sample (RNVideoChat) and ConectyCube-web-sample using **FireFox** browser and the issue still occurs.
I've attached the logs of both of my device using this sample applications.

Device: Window 10 ( Build version 2004)
Browser: Firefox  (81 stable)

[Log File](https://drive.google.com/file/d/1R0o3h8vFvYgjav3TIH6nbM942hYbBfjF/view?usp=sharing)

Brand: Samsung Galaxy S8+
OS: Android 9

[Log File](https://drive.google.com/file/d/1yK4Z6akG7PT4D4fzr5qvZ0KW66dQXEOL/view?usp=sharing)

**Comment by ccvlad** [comment]
Hi @sapkotamadhusudan 
Were you using the latest version of ConnectyCube JS SDK?
Thanks for good description! We will check the case and let you know!

**Comment by sapkotamadhusudan** [comment]
@ccvlad  
I'm using v3.6.2 in React Native project and v3.7.1 in Web application. I'm planning to update this library in react-native application soon.

**Comment by ccvlad** [comment]
Thanks! I have tested also with v3.6.2 and got the same crash. Will keep you update about news.

**Comment by sapkotamadhusudan** [comment]
@ccvlad any updates regarding this issue?

**Comment by ccvlad** [comment]
Hi, @sapkotamadhusudan 
We planned to fix this the week before last, but it didn't work out due to the workload. Postponed to next week

**Comment by ccvlad** [comment]
Hi, @sapkotamadhusudan 

The crash was solved in [v3.7.5](https://github.com/ConnectyCube/connectycube-js-sdk-releases/releases/tag/3.7.5) ([NPM](https://www.npmjs.com/package/react-native-connectycube))

Sorry for delay!

**Comment by sapkotamadhusudan** [comment]
@ccvlad Thanks, i'll test the new release and will close this issue :)
