### ISSUE TITLE
Open particular chat automatically when clicking notification

### ISSUE THREAD

**Issue by ciamalaeaskan** [ConnectyCube/connectycube-reactnative-samples#126]
I'm using connectycube chat system in my react native  application it works fine. But i have integrated Push notification separately it triggers every time when we send message . So when i click the notification it should open the respective chat. But i can't able to open that chat.
Below is my code:

var dialog={"id": "5f5a21f0ca8b.........", "occupants_ids": [189..., 189...], "unread_messages_count": 0, "type":3,"user_id": 189...};
this.props.navigation.navigate("Chat", {dialog});

Please help me if i have missed anything.

Thanks.

**Comment by ccvlad** [comment]
Are any error in you console?

FYI. Usually we use `dialog_id`. Define a dialog by `dialog_id` and pass it to navigation.
You may need to configure your navigation to open the "Chat" screen from any place (just a guess).

**Comment by ciamalaeaskan** [comment]
> Are any error in you console?
> 
> FYI. Usually we use `dialog_id`. Define a dialog by `dialog_id` and pass it to navigation.
> You may need to configure your navigation to open the "Chat" screen from any place (just a guess).

yes i'm receiving error on the below line
    store.getState().users[id]

**Comment by ccvlad** [comment]
Seams you lost users' state in redux before navigate.
So, you have to fix this. Or try to comment a code where you have errors to test navigation to the Chat screen.

**Comment by ciamalaeaskan** [comment]
Error: Could not find "store" in the context of "Connect(Dialogs)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(Dialogs) in connect options.

I'm getting this error when navigate to chat page

**Comment by ciamalaeaskan** [comment]
Any update for me this is the only issue i'm facing now.

**Comment by ccvlad** [comment]
> Error: Could not find "store" in the context of "Connect(Dialogs)". Either wrap the root component in a , or pass a custom React context provider to and the corresponding React context consumer to Connect(Dialogs) in connect options.
> 
> I'm getting this error when navigate to chat page

It is Redux. Please see the Redux docs and how to use it with the React Native.

**Comment by ciamalaeaskan** [comment]
Yeah! I check that. And also I like to let you know that I'm not using connectycube default notification process, I have separately create notification process and integrated with it. So can you please let me know what are the parameters to be passed to open particular chat.

**Comment by ccvlad** [comment]
I would be use a dialog's ID to obtain a dialog by ID (from redux, from DB or from server) and use it.

**Comment by ciamalaeaskan** [comment]
Can you please explain this with any example ?

**Comment by ccvlad** [comment]
In most cases it will be your own code realization.

How to get dialog by ID from server:
```javascript
ConnectyCube.chat.dialog.list({ _id: someDialogId }).then(dialog => dialog)

**Comment by ciamalaeaskan** [comment]
Yes i have got the dialog id. But  I'm asking what are required datas for this navigation. "this.props.navigation.navigate("Chat", {dialog});" I mean what are the datas should inside the {dialog} variable

**Comment by ccvlad** [comment]
You pass a data and you get the data, so you should know what exactly you are need :)

The `{dialog}` is short code notation from an object `{dialog: dialogObject}`.

Try this:
```javascript
ConnectyCube.chat.dialog.list({ _id: dialogId})
  .then(dialog => {
    this.props.navigation.navigate("Chat", {dialog});
  })
  .catch(error => {
    console.log(error)
  });
```

**Comment by ciamalaeaskan** [comment]
Hi, 
 
I have tried the  above  method like this, 

 ConnectyCube.chat.dialog.list({ _id: 1895242})
        .then(dialog => {
          this.props.navigation.navigate("Chat", {dialog});
 })
 .catch(error => {
          console.log(error)
 });
 

I'm having the error like the first screenshot .

So i have tried another method

  gotToChat = (receiverid) => {
    this.setState({ isLoader: true })
    ChatService.createPrivateDialog(receiverid)
        .then((newDialog) => {
            console.log(newDialog, "newDialog response")
    });
  }

That also having error like the second screenshot. 

Can you please help me 


<img width="379" alt="Screenshot 2020-10-15 at 7 02 43 PM" src="https://user-images.githubusercontent.com/54099216/96134900-03f63c00-0f19-11eb-8773-8cdafbe25e57.png">
<img width="351" alt="Screenshot 2020-10-15 at 7 09 52 PM" src="https://user-images.githubusercontent.com/54099216/96137217-04430700-0f1a-11eb-9532-b6b13c453e08.png">

**Comment by ccvlad** [comment]
Check with the `console.log()` what you have in `this.props.navigation`, then `this.props.navigation.state` > `this.props.navigation.state.dialog` > `this.props.navigation.state.dialog.name`. You will find what is missing.

**Comment by ciamalaeaskan** [comment]
Now i have tried this 

ConnectyCube.chat.dialog.list({ _id: "5f87d9beca8bf45d18b30ce6"})
        .then(dialog => {
          console.log(dialog.items[0], "dialogdialognew")
          this.props.navigation.navigate("Chat", {dialog : dialog.items[0]});
        })
        .catch(error => {
          console.log(error)
        });

its redirect to chat page but did't show any previous message like the below screenshot 

I missed any thing ?

<img width="351" alt="Screenshot 2020-10-15 at 7 23 49 PM" src="https://user-images.githubusercontent.com/54099216/96138974-f55d5400-0f1b-11eb-916e-6ee7469a354f.png">

**Comment by ccvlad** [comment]
Check a log of Metro server or via Chrome console. Probably you would see some errors.

**Comment by ciamalaeaskan** [comment]
having TypeError: null is not an object (evaluating 'name.length') warning only. 

I'm receiving this error by using above all three methods

**Comment by ccvlad** [comment]
What you have in the dialog object? (`console.log(dialog)`)

**Comment by ciamalaeaskan** [comment]
{"_id": "5f87d9beca8bf45d18b30ce6", "admins_ids": [], "created_at": "2020-10-15T05:10:22Z", "description": null, "last_message": "Hiii", "last_message_date_sent": 1602769104, "last_message_id": "5f8850d00ed3a949ca00000c", "last_message_user_id": 1895242, "name": "Teststudent021020200328 Teststudent021020200328", "occupants_ids": [1895242, 2171558], "photo": null, "pinned_messages_ids": [], "type": 3, "unread_messages_count": 0, "updated_at": "2020-10-15T13:38:24Z", "user_id": 1895242, "xmpp_room_jid": null}

this are my dialog response

**Comment by ccvlad** [comment]
It is OK. And try to check the dialog on the Chat screen

**Comment by ciamalaeaskan** [comment]
above is the response of this code 

ConnectyCube.chat.dialog.list({ _id: "5f87d9beca8bf45d18b30ce6"})
.then(dialog => {
console.log(dialog.items[0])
this.props.navigation.navigate("Chat", {dialog : dialog.items[0]});
})
.catch(error => {
console.log(error)
});

**Comment by ccvlad** [comment]
On the "Chat" route. After `this.props.navigation.navigate("Chat", {dialog : dialog.items[0]})` you go to  the "Chat" route. There you need to check your params (dialog).

**Comment by ciamalaeaskan** [comment]
Yes, i check it on chat page componentDidMount function there also having same data, But on ChatService.getMessages(dialog) method go to catch part but did't show any error message, it shows like the below log only 

[Thu Oct 15 2020 19:50:17.324]  LOG      Error.



  componentDidMount() {
    this.initAuthToken();
    const { dialog } = this.props.navigation.state.params
    console.log(dialog, "Chat page ")
    ChatService.getMessages(dialog)
      .catch(e => 
        console.log(`Error.\n\n${JSON.stringify(e)}`)
      )
      .then(amountMessages => {
        amountMessages === 100 ? this.needToGetMoreMessage = true : this.needToGetMoreMessage = false
        this.setState({ activIndicator: false })
      })
  }

**Comment by ccvlad** [comment]
Probably you need to find error inside the `getMessages` to fix - https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNChat/src/services/chat-service.js#L118

**Comment by ciamalaeaskan** [comment]
Thank
