### ISSUE TITLE
No resume for video call session

### ISSUE THREAD

**Issue by georgessaroufim** [ConnectyCube/connectycube-reactnative-samples#128]
During a video call, if i disconnect from wifi network and then turn it on, session is ended and its not resumed.
Is there any way where i can set a timeout for retry connection so i can handle session if there is any network problem?

I got this log when turning off network then turn it on:
<img width="546" alt="Screen Shot 2020-10-13 at 12 32 21 PM" src="https://user-images.githubusercontent.com/32562953/95843399-533d4080-0d50-11eb-92f4-b20292d8e335.png">

Thank you in advance.

**Comment by ccvlad** [comment]
Hi @georgessaroufim 
The WebRTC connection is able to resume within 30 seconds interval and it will close after. Is your session able to resume if disconnect takes not more than 30 seconds?

**Comment by georgessaroufim** [comment]
Video call didn't resumed. I turn off wifi network for 5 secs then turn it on. After i turn it on, video still stuck.

**Comment by ccvlad** [comment]
I see, have tested on our VideoChat Sample. Seems it is an issue in our SDK. I am planning to create a task to fix the problem in next release.

Thank you for the report. We will let you know about the SDK release with the fix.

**Comment by georgessaroufim** [comment]
Appreciate your support.

**Comment by ccvlad** [comment]
Hi, @georgessaroufim 

I was trying to solve, but didn't manage.

In a browser on a PC, reconnection works fine, where WebRTC gives a real 30 seconds for reconnection.

In React Native app and web-app for browser (mobile Chrome) iceCandidates get status "failed" after manual off/on Wi-Fi connection. Seams WebRTC is losing its iceCandidates after re-establishing the connection point. But WebRTC stream manage to continue if plug-out/plug-in an internet cable on a Wi-Fi router in a 30 second interval.
