### ISSUE TITLE
"Internal Server Error", "status": "500"

### ISSUE THREAD

**Issue by pankajinfowind** [ConnectyCube/connectycube-reactnative-samples#129]
This demo project is successfully running, but when I try to implement in my react native project then it always through an error ""Internal Server Error", "status": "500"" when I try to call "CreateSession" API.

**Comment by DaveLomber** [comment]
Please share the logs of the request, will check

**Comment by pankajinfowind** [comment]
OK, This was happened because I was creating the session with user which has not registered.

**Comment by pankajinfowind** [comment]
But I have one question regarding next flow.

**Comment by ccvlad** [comment]
@pankajinfowind 
We need to check your logs

**Comment by pankajinfowind** [comment]
@ccvlad thanks, It has solved now, it happened because server side setup, I had enabled Custom Identity Provider, that's  why I was always getting "Internal Server Error"
