### ISSUE TITLE
ConnectyCube.pushnotifications.subscriptions.create(params) returns 401 error

### ISSUE THREAD

**Issue by GuleriaAshish** [ConnectyCube/connectycube-reactnative-samples#131]
I am trying to integrate push notification with connetycube. But when i tried to hit ConnectyCube.pushnotifications.subscriptions.create(params) method with params that provided in documentation then it results a error code 401, {"code": 401, "info": {"errors": ["Token is required"]}}

**code sample:** 
**Method decleration:**
const subcribeToPushNotification = (deviceToken) => {
    const DeviceInfo = require('react-native-device-info').default
    const params = {
        notification_channel: Platform.OS === 'ios' ? 'apns' : 'gcm',
        device: {
            platform: Platform.OS,
            udid: DeviceInfo.getUniqueId()
        },
        push_token: {
            environment: 'development',
            client_identification_sequence: deviceToken,
            bundle_identifier: "com.afyanet"
        }
    }
    console.warn("param", params)
    // JS SDK v2+
    ConnectyCube.pushnotifications.subscriptions.create(params)
        .then(result => {
            console.warn("suc", result)
        })
        .catch(error => {
            console.warn("err", error)
        });

    // JS SDK v1
    /*
    ConnectyCube.pushnotifications.subscriptions.create(
      params,
      (error, result) => {}
    );
    */
}

**Calling methods subcribeToPushNotification:**
 // (optional) Called when Token is generated (iOS and Android)
            onRegister: function (token) {

                AsyncStorage.setItem('notification', token.token);
                const deviceToken = token.token;
                console.warn("token", deviceToken)
                subcribeToPushNotification(deviceToken);
            },

**Comment by GuleriaAshish** [comment]
![Screenshot 2020-10-19 at 4 57 28 PM](https://user-images.githubusercontent.com/61535271/96444642-3e6b1c00-122c-11eb-9c9a-3e14648522e7.png)

**Comment by GuleriaAshish** [comment]
@ccvlad please suggest me what i am doing wrong .

**Comment by ccvlad** [comment]
Hi, @GuleriaAshish 

I think you have not logged in to ConnectyCube.
https://developers.connectycube.com/js/authentication-and-users?id=session-token-rights

**Comment by GuleriaAshish** [comment]
> Hi, @GuleriaAshish
> 
> I think you have not logged in to ConnectyCube.
> https://developers.connectycube.com/js/authentication-and-users?id=session-token-rights

Thanks for the quick reply @ccvlad , really appreciate your efforts.
I have logged in to connectycube successfully. And as i can see create subscription api require deviceToken which i have provided.

**Comment by GuleriaAshish** [comment]
@ccvlad any solution for this ?

**Comment by ccvlad** [comment]
Please provide a full log, from ConnectyCube.createSession to ConnectyCube.pushnotifications.subscriptions.create

**Comment by GuleriaAshish** [comment]
I am implementing notifications code in my app.js class. And in onRegister() method of notifications i am calling ConnectyCube.pushnotifications.subscriptions.create() this method with the token that i get from onRegister() method just like explained in your documentation.

 I think there is no relation with connectycube session. That may take part when i am willing to send the notification but on subscription i don't think it is needed .

And the most important part is we can not createSession in app.js it must be created when we login .

**Comment by ccvlad** [comment]
Could you show your logs?
You can not request to API w/o session

**Comment by GuleriaAshish** [comment]
[Response][1] {"session": {"application_id": 3448, "created_at": "2020-10-21T07:51:09Z", "id": 18537738, "nonce": 5077, "token": "65b09550bf95295b5b3074339054e1c976000d78", "ts": 1603266667, "updated_at": "2020-10-21T07:51:09Z", "user": {"avatar": "", "blob_id": null, "created_at": "2020-10-13T09:05:01Z", "custom_data": "", "email": null, "external_user_id": null, "facebook_id": null, "full_name": "Ashish Guleria", "id": 2190208, "last_request_at": "2020-10-21T07:51:09Z", "login": "Ashish", "phone": "9882744034", "twitter_id": null, "updated_at": "2020-10-21T07:51:09Z", "user_tags": null, "website": null}, "user_id": 2190208}}
[Wed Oct 21 2020 13:21:09.358]  LOG      [Chat] Connect with parameters  {"password": "Mind#123", "userId": 2190208}
[Wed Oct 21 2020 13:21:09.358]  LOG      [Chat] status connecting wss://chat.connectycube.com:5291
[Wed Oct 21 2020 13:21:11.144]  LOG      [Chat] status connect 
[Wed Oct 21 2020 13:21:11.145]  LOG      [Chat] CONNECTING
[Wed Oct 21 2020 13:21:11.146]  LOG      [Chat] status opening 
[Wed Oct 21 2020 13:21:11.146]  LOG      [Chat] SENT: <open version="1.0" xmlns="urn:ietf:params:xml:ns:xmpp-framing" to="chat.connectycube.com"/>
[Wed Oct 21 2020 13:21:11.691]  LOG      [Chat] RECV: <open xmlns='urn:ietf:params:xml:ns:xmpp-framing' from='chat.connectycube.com' id='8e566504-324b-4b8b-97a5-d965fb86de88' version='1.0' xml:lang='en' />
[Wed Oct 21 2020 13:21:11.692]  LOG      [Chat] status open <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" from="chat.connectycube.com" id="8e566504-324b-4b8b-97a5-d965fb86de88" version="1.0" xml:lang="en"/>
[Wed Oct 21 2020 13:21:11.697]  LOG      [Chat] RECV: <stream:features xmlns:stream="http://etherx.jabber.org/streams"><sm xmlns="urn:xmpp:sm:3"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS</mechanism><mechanism>PLAIN_FAST</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression></stream:features>
[Wed Oct 21 2020 13:21:11.699]  LOG      [Chat] SENT: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">ADIxOTAyMDgtMzQ0OABNaW5kIzEyMw==</auth>
[Wed Oct 21 2020 13:21:12.811]  LOG      [Chat] RECV: <success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/>
[Wed Oct 21 2020 13:21:12.812]  LOG      [Chat] status opening 
[Wed Oct 21 2020 13:21:12.813]  LOG      [Chat] SENT: <open version="1.0" xmlns="urn:ietf:params:xml:ns:xmpp-framing" to="chat.connectycube.com"/>
[Wed Oct 21 2020 13:21:13.367]  LOG      [Chat] RECV: <open xmlns='urn:ietf:params:xml:ns:xmpp-framing' from='chat.connectycube.com' id='8e566504-324b-4b8b-97a5-d965fb86de88' version='1.0' xml:lang='en' />
[Wed Oct 21 2020 13:21:13.367]  LOG      [Chat] status open <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" from="chat.connectycube.com" id="8e566504-324b-4b8b-97a5-d965fb86de88" version="1.0" xml:lang="en"/>
[Wed Oct 21 2020 13:21:13.371]  LOG      [Chat] RECV: <stream:features xmlns:stream="http://etherx.jabber.org/streams"><sm xmlns="urn:xmpp:sm:3"/><mobile xmlns="http://tigase.org/protocol/mobile#v2"/><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></stream:features>
[Wed Oct 21 2020 13:21:13.372]  LOG      [Chat] SENT: <iq type="set" id="prbbk4fzik" xmlns="jabber:client"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/></iq>
[Wed Oct 21 2020 13:21:13.918]  LOG      [Chat] RECV: <iq xmlns="jabber:client" type="result" id="prbbk4fzik" to="2190208-3448@chat.connectycube.com/1204607085-chat-68990"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>2190208-3448@chat.connectycube.com/1204607085-chat-68990</jid></bind></iq>
[Wed Oct 21 2020 13:21:13.919]  LOG      [Chat] SENT: <iq type="set" id="t046fykyf0" xmlns="jabber:client"><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></iq>
[Wed Oct 21 2020 13:21:13.920]  LOG      [Chat] status online 2190208-3448@chat.connectycube.com/1204607085-chat-68990
[Wed Oct 21 2020 13:21:13.921]  LOG      [Chat] ONLINE
[Wed Oct 21 2020 13:21:13.921]  LOG      [Chat] CONNECTED
[Wed Oct 21 2020 13:21:13.922]  LOG      [Chat] SENT: <iq type="set" from="2190208-3448@chat.connectycube.com/1204607085-chat-68990" id="abd53f68-6066-4dc5-ae46-f8263cd02450:enableCarbons" xmlns="jabber:client"><enable xmlns="urn:xmpp:carbons:2"/></iq>
[Wed Oct 21 2020 13:21:13.922]  LOG      [Chat] SENT: <presence xmlns="jabber:client"/>
[Wed Oct 21 2020 13:21:14.470]  LOG      [Chat] RECV: <iq xmlns="jabber:client" type="result" id="t046fykyf0" to="2190208-3448@chat.connectycube.com/1204607085-chat-68990"/>
[Wed Oct 21 2020 13:21:14.731]  LOG      [Chat] RECV: <iq xmlns="jabber:client" type="result" id="abd53f68-6066-4dc5-ae46-f8263cd02450:enableCarbons" to="2190208-3448@chat.connectycube.com/1204607085-chat-68990"/>
[Wed Oct 21 2020 13:21:14.734]  LOG      [Chat] RECV: <presence from="2190208-3448@chat.connectycube.com/1204607085-chat-68990" xmlns="jabber:client" to="2190208-3448@chat.connectycube.com"/>

**Comment by ccvlad** [comment]
@GuleriaAshish 

The log is not full.

Anyway, your steps should be:
```javascript
ConnectyCube.init(appCreds, appConfig);

ConnectyCube.createSession(userParams).then(session => {
  ConnectyCube.pushnotifications.subscriptions.create(params);
});
```

**Comment by GuleriaAshish** [comment]
@ccvlad ,i am closing this issue as it's working now. 
Thanks for the help.
