### ISSUE TITLE
Message get duplicates

### ISSUE THREAD

**Issue by ciamalaeaskan** [ConnectyCube/connectycube-reactnative-samples#132]
Hi, 

I have an issue on message sending process. When i send a message it get duplicates multiple times. Can you please help me to find out why this is happend ?

Please refer the below screenshot.

Thanks.
![image_2020_10_20T04_54_08_271Z](https://user-images.githubusercontent.com/54099216/96541834-7b7fee80-12be-11eb-933e-2552481c9d47.png)

**Comment by ccvlad** [comment]
Hi, @ciamalaeaskan 

Is the issue reproduce on our Sample Chat (w/o your modifications)? Or is it in your code?

A logs will be helpful.

**Comment by ccvlad** [comment]
OK. We will check to find the issue and fix. Are there any special steps to reproduce or the problem always present?

**Comment by ciamalaeaskan** [comment]
No it not on all time. I think its happen when both sender or receiver open chat at a time or open chat with multiple devices. But not sure about this scenario. Can you please give me a solution ASAP ?

**Comment by ciamalaeaskan** [comment]
And also I want to confirm  that this will persist when user is logged in via browser version and Mobile at a time ?

**Comment by ccvlad** [comment]
> No its not on all time. I think its happen when both sender or receiver open chat at a time or open chat with multiple devices. But not sure about this scenario. Can you please give me a solution ASAP ?

Please show your logs. We have to check the duplicate issue there. Or provide steps to reproduce for the issue.

> And also I want to confirm that this will persist when user is logged in via browser version and Mobile at a time ?

You will get messages from the same user. Compare users' IDs to know that you've received the message from the same user.

**Comment by ciamalaeaskan** [comment]
> Please show your logs. We have to check the duplicate issue there. Or provide steps to reproduce for the issue.


This is happend when both sender and receiver open and chat each other at a time. And also if the user logged in multiple devices also its happend

**Comment by ciamalaeaskan** [comment]
Message duplication scenario :  

1. Person1 and Person2  logged in a real devices seperately. And also Person1 has logged in more than one devices
2. both open their personal chat module and start chatting. 
3. Person1 sent hai to Person2, then Person2 open  personal chat page. And reply to Person1
4. then Person1 get duplicate message ( same message with multiple times)

**Comment by ccvlad** [comment]
Thanks
We will check it and let you know

**Comment by ciamalaeaskan** [comment]
Hi, @ccvlad 

This issue is only pending from our end, Any update on this please?

**Comment by ccvlad** [comment]
Hi @ciamalaeaskan 
I have tested our [Sample RNChat](https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNChat) (user-A and user-B) with [Sample Web Chat](https://github.com/ConnectyCube/connectycube-web-samples/tree/master/chat) (User-A) by your steps and have not reproduced the issue with duplicate.
Could you provide log from device where the problem exists?

**Comment by ciamalaeaskan** [comment]
No, for now we are not using web chat. We are having this issue only on RNchat on the real device when chatting each other  at the same time.

**Comment by ccvlad** [comment]
I am not ask you for logs from webapp. You are able to copy logs from the RNChat and paste here (via Metro Bundler / Android Studio / Chrome Debuger)

**Comment by ciamalaeaskan** [comment]
Now i have attached log file with the demo to reproduce this issue. Please refer the below zip file. 

[Uploading Archive.zip…]()

**Comment by ccvlad** [comment]
> Now i have attached log file with the demo to reproduce this issue. Please refer the below zip file.
> 
> Uploading Archive.zip…

It is empty:
<img width="1237" alt="Screen Shot 2020-10-28 at 13 37 54" src="https://user-images.githubusercontent.com/43810932/97431437-fa120700-1922-11eb-8c5c-cd88eae67457.png">

**Comment by ciamalaeaskan** [comment]
Please check it now

**Comment by ccvlad** [comment]
A user receive a forwarded message from the same user and it is normal. You can check incoming message by ID and display it if doesn't exist.

```javascript
...

// init onMessageListener 
ConnectyCube.chat.onMessageListener = this.onMessage;

...

const isMessageExistById = msgId => {
  return messages.some(msg => msg.id === msgId); // messages - list of all current chat's messages
}

const displayMessage = msg => {
  // here a code to display
}

const sendMessage = (dialogJidOrUserId, msg) => {
  const messageId = ConnectyCube.chat.send(dialogJidOrUserId, msg);

  this.displayMessage(msg);

  return messageId;
}

const onMessage = (senderId, msg) => {
  // use for some more conditions:
  // const isPrivateMessage = msg.type === 'chat';
  // const isGroupMessage = msg.type === 'groupchat';
  // const isSelfUser = currentUserId === senderId;
 const isMessageExist = this.isMessageExistById(msg.id)

  if (!isMessageExist) {
    this.displayMessage(msg);
  }
...
```

FYI:
- User who send a message in private chat, won't receive the message in onMessageListener on current device. But it will receive the message on other device as forwarded message (peer-to-peer chat)
- User who send a message in group chat (or channel, or broadcast), will receive the message in onMessageListener. Means that the user sends a message to a dialog (not to other user) and the dialog send the message to all occupants. There isn't forwarded messages, because unnecessary.

**Comment by joy-mollick** [comment]
Message gets duplicates , so many bugs of sample RNChat project !!!!! When you close app without seeing the received messages ,then when you open again ,you will see double double messages of the last unseen messages.
