### ISSUE TITLE
Open app Notification app crash

### ISSUE THREAD

**Issue by ciamalaeaskan** [ConnectyCube/connectycube-reactnative-samples#134]
Hi,

I have integrated push notification for our chat system separately and its works fine. But when i open notification when the phone is locked with the app is  in foreground,  App get crash. Other than this scenario it works fine. Please refer the below demo video. Can you please give any solution for this ?

[Screen Recording 2020-10-23 at 4.41.57 PM.zip](https://github.com/ConnectyCube/connectycube-reactnative-samples/files/5429095/Screen.Recording.2020-10-23.at.4.41.57.PM.zip)

**Comment by ccvlad** [comment]
Hi, @ciamalaeaskan 
Try to use real device.

**Comment by ciamalaeaskan** [comment]
Yes real device also having this same poblem. On real device the get stopped on both android and ios.

**Comment by ccvlad** [comment]
Please show logs from Metro server or from AndroidStudio
