### ISSUE TITLE
Cannot find message Listeners in Version 3.7.2 

### ISSUE THREAD

**Issue by mikeangelsilva** [ConnectyCube/connectycube-reactnative-samples#136]
Hi,
i'm using the react native connectycube sdk on my development.the version i'm using is 3.72,
when i tried using this code. (from react native documentation in connectycube doc site)

`ConnectyCube.chat.onDeliveredStatusListener = function (messageId, dialogId, userId) { console.log("[ConnectyCube.chat.onDeliveredStatusListener] callback:", messageId, dialogId, userId);};`

the` .onDeliveredStatusListener `is not defined. 

also i tried the other listeners. but i cant't find the listeners as mentioned in the documentation site.
 
![image](https://user-images.githubusercontent.com/38802880/97503164-7d793a00-19af-11eb-8a84-bc7ab1b6d1b2.png)

how can i use that? it seems that version is not compatible in my react native version (0.63.2)

please help me on this issue. 
Thank you.

**Comment by ccvlad** [comment]
Hi, @mikeangelsilva 
Symbol "_" uses for methods' names to show that the method is private. So, this listeners uses inside the ConnectyCube SDK, you do not need to use they. It is conventional rule for JavaScript language.
Do not fully trust to a code editor's extension. It does not work as you expect. JS is not compiled language.
Chat listeners are not methods of the Chat class. You should define each chat's listener by a function.
Just try the code in development.

**Comment by mikeangelsilva** [comment]
> Hi, @mikeangelsilva
> Symbol "_" uses for methods' names to show that the method is private. So, this listeners uses inside the ConnectyCube SDK, you do not need to use they. It is conventional rule for JavaScript language.
> Do not fully trust to a code editor's extension. It does not work as you expect. JS is not compiled language.
> Chat listeners are not methods of the Chat class. You should define each chat's listener by a function.
> Just try the code in development.

**Comment by mikeangelsilva** [comment]
tried using it. still not working the listener. please help me. we cant really proceed in the next step because of this listener.

**Comment by mikeangelsilva** [comment]
this is the code i used. 
![image](https://user-images.githubusercontent.com/38802880/97948440-93319980-1dcb-11eb-9b8e-9fdb7eee59c2.png)

**Comment by mikeangelsilva** [comment]
also tried this.
![image](https://user-images.githubusercontent.com/38802880/97949251-fb817a80-1dcd-11eb-80ae-c1d865c7a62a.png)
not working. :(

**Comment by ccvlad** [comment]
Show your logs, please. The code snippet you have provided is correct, but this is not enough to understand the problem.
You can get logs from Metro serrver / Chrome debugger / AndroidStudio / XCode
