### ISSUE TITLE
Session Unauthorized

### ISSUE THREAD

**Issue by ciamalaeaskan** [ConnectyCube/connectycube-reactnative-samples#138]
Hi,
 I'm using our web chat system, on that we have created session and registered user  yesterday, but today when i run the same code, I'm getting "Unauthorized" on session creation. Can you please help me why this is happend ?

stdClass Object
(
    [errors] => Array
        (
            [0] => Unauthorized
        )

)
stdClass Object
(
    [errors] => Array
        (
            [0] => Token is required
        )

)

**Comment by ccvlad** [comment]
Is it actual for now? Did you manage to create a session yesterday?
Also check this user in your admin panel.
