### ISSUE TITLE
getMediaDevices is not a function

### ISSUE THREAD

**Issue by mikeangelsilva** [ConnectyCube/connectycube-reactnative-samples#139]
i tried integrating the code of RMVideoChatConf project into my project.

and i get this.

![image](https://user-images.githubusercontent.com/38802880/97994602-6cea1900-1e20-11eb-99c0-9c03f9fdcca2.png)

"react": "16.9.0",
"react-native": "0.63.0"

help me on this

**Comment by ccvlad** [comment]
Our SDK uses [react-native-webrtc](https://github.com/react-native-webrtc/react-native-webrtc) lib. So you should manually link the lib.

From our docs: https://developers.connectycube.com/reactnative/videocalling?id=connect-webrtc-lib
Guides for iOS and Android: https://github.com/react-native-webrtc/react-native-webrtc#installation

**Comment by mikeangelsilva** [comment]
fixed thank you!
