### ISSUE TITLE
[IOS] Notification sometimes delay or not received.

### ISSUE THREAD

**Issue by mikeangelsilva** [ConnectyCube/connectycube-reactnative-samples#141]
i configured the apns in the dashboard then try sending a sample notification.

 the notification delivered on time and sometimes the notification delayed or not delivered.

 i thought the reason of the delay is because i'm using free account.

if we switched it to Enterprise account, is the issue possible ?

Thank You!

**Comment by DaveLomber** [comment]
@mikeangelsilva The shared cloud hosts many apps, which may produce some delays in push delivery, cause some apps may have user load spikes and other apps can be affected a bit during this period. We are trying to mitigate all these spikes, but sometimes it can produce temp issues. 

With Enterprise, the only your app is hosted in server account, hence no other apps may interrupt or produce any overloading.

If you are interested in Enterprise plan  - please check https://connectycube.com/pricing/ and contact https://connectycube.com/contact/
