### ISSUE TITLE
How to integrate a video call into the chat of an existing project?

### ISSUE THREAD

**Issue by anauk** [ConnectyCube/connectycube-reactnative-samples#142]
There is a project with one-on-one chats built on top of GiftedChat. How to add video calls to such a chat?

**Comment by DaveLomber** [comment]
@anauk 

please find a way re how to integrate it into existing app

1. First of all, you need to perform ConnectyCube user login (e.g. under the hood) - please check the users & auth guide https://developers.connectycube.com/js/authentication-and-users

2. Then I suggest too follow the video calling integration guide https://developers.connectycube.com/js/videocalling

3. As a help - you can use ready code sample and move all the required parts into your app https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat
