### ISSUE TITLE
Navigation between  chat and other components

### ISSUE THREAD

**Issue by ciamalaeaskan** [ConnectyCube/connectycube-reactnative-samples#145]
We have integrated RNChat system with our app but the navigation is not working properly.

For eg. we have 2 login student and instructor. First we have login as instructor and logut immediately login as student but the same instructor pages are showing for me. This is happen only when we back from chat. Otherwise it works fine. Please refer the attached videos

Can you please help me to integrate our own navigation with your chat navigation.

[Archive 2.zip](https://github.com/ConnectyCube/connectycube-reactnative-samples/files/5515509/Archive.2.zip)

**Comment by ccvlad** [comment]
@ciamalaeaskan sorry, it is not our responsibilities. See [React Navigation](https://reactnavigation.org/docs/getting-started) docs to achieve your case.
