### ISSUE TITLE
Call Listener

### ISSUE THREAD

**Issue by krishna11124** [ConnectyCube/connectycube-reactnative-samples#146]
How To Remove on Call Listener While Component Will Unmount..

**Comment by ccvlad** [comment]
`ConnectyCube.videochat.onCallListener = null` will rewrite prev listener, so you won't receive a call. Under the hood of ConnectyCube SDK the XMPP chat delegates stanzas and calls `ConnectyCube.videochat.onCallListener` if it has `typeof === 'function'` on an incoming call's signaling.

**Comment by krishna11124** [comment]
Okey, Can't Remove A Call Listener??

**Comment by DaveLomber** [comment]
Setting null means removing it, so it should work just well

**Comment by krishna11124** [comment]
Hi, actually i have a scenario of  calling i create a single incoming calling screen and set the only call listener on the home page for redirection of the incoming call screen its redirect successfully from receive request from the call listener on the home page but in the incoming call screen the call process or call listener is not working..thanks can u please help me

**Comment by ccvlad** [comment]
@krishna11124 

You can use `onCallListener` to redirect with data from the listener on other screen where you will connect other listeners such as `onRemoteStreamListener`, `onStopCallListener` etc. (check our [docs](https://developers.connectycube.com/js/videocalling)).
Or use High Order Component to connect all listeners and provide all data to children (or via Redux state)
