### ISSUE TITLE
Email and phone number to be Link

### ISSUE THREAD

**Issue by ciamalaeaskan** [ConnectyCube/connectycube-reactnative-samples#147]
Hi if we send message in our RNchat system  the chat  contains email or phone number and that  should be hyperlinked/hotlink like whatsapp. How can we implement this. Please refer the below screenshots.

![image_2020_11_12T12_50_19_240Z](https://user-images.githubusercontent.com/54099216/98942915-be775f80-2514-11eb-9503-a8ffb738cb28.png)

![image](https://user-images.githubusercontent.com/54099216/98944055-76f1d300-2516-11eb-8f31-a9f96b819c5d.png)

**Comment by ccvlad** [comment]
Use [react-native-hyperlink](https://www.npmjs.com/package/react-native-hyperlink) to solve you issue
