### ISSUE TITLE
UDID Id for Android

### ISSUE THREAD

**Issue by godwin12345** [ConnectyCube/connectycube-reactnative-samples#15]
What id need to pass for the android UDID for push notification subscribe?

**Comment by DaveLomber** [comment]
UDID is simply something that can identify current device

For example, here is what we use usually:

```
    const DeviceInfo = require('react-native-device-info').default

    const params = {
        notification_channels: Platform.OS === 'ios' ? 'apns' : 'gcm',
        device: {
          platform: Platform.OS,
          udid: DeviceInfo.getUniqueID()
        },
        push_token: {
          environment: __DEV__ ? 'development' : 'production',
          client_identification_sequence: deviceToken
        }
      }
```

**Comment by godwin12345** [comment]
deviceToken?

**Comment by DaveLomber** [comment]
Please see here https://github.com/ConnectyCube/connectycube-reactnative-samples/issues/14#issuecomment-540643992

**Comment by DaveLomber** [comment]
In a case for further reference - we prepared a complete guide on how to integrate push notifications in React Native

 
https://developers.connectycube.com/reactnative/push-notifications
