### ISSUE TITLE
Will Pay Someone to implement background calling and messaging in my app

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#151]
Need help implementing ConnectyCube react native. Finding integration of messages + notifications + calls + callkeep too difficult. Willing to pay someone to work with me for a few days to fix my issues.

What I need:
- Wake closed app on incoming call, wake background app on incoming call.
- App -> App notifications. (background/foreground).
- Fix issues fixed related to ConnectyCube + React-Native Callkeep integration
- Implement basic React Native chat within my app. 

contact for details:
stephanokparaskeva@gmail.com

**Comment by ccvlad** [comment]
> Need help implementing ConnectyCube react native. Finding integration of messages + notifications + calls + callkeep too difficult. Willing to pay someone to work with me for a few days to fix my issues.
> 
> What I need:
> 
> * Wake closed app on incoming call, wake background app on incoming call.
> * App -> App notifications. (background/foreground).
> * Fix issues fixed related to ConnectyCube + React-Native Callkeep integration
> * Implement basic React Native chat within my app.
> 
> contact for details:
> [stephanokparaskeva@gmail.com](mailto:stephanokparaskeva@gmail.com)

I will forward your message to our leadership

**Comment by andybui090** [comment]
I has implement function iOS complete, android has some bugs when app killed, any help

**Comment by DaveLomber** [comment]
@andybui090 please describe your Android issues in details
