### ISSUE TITLE
Chat Dialog

### ISSUE THREAD

**Issue by krishna11124** [ConnectyCube/connectycube-reactnative-samples#152]
Hello Team, Is There Any Way To Filter Chat Dialog With PhoneBook Name & Filter Contacts With Phone Book ??

**Comment by DaveLomber** [comment]
There is no way to filter chat dialog with phone book name

All the filters are available here 
https://developers.connectycube.com/server/chat?id=parameters

**Comment by krishna11124** [comment]
Any Way Available For Filter User With PhoneBook???

**Comment by DaveLomber** [comment]
there is a way to get users by phone number

**Comment by DaveLomber** [comment]
Just user `users.get`

**Comment by DaveLomber** [comment]
https://developers.connectycube.com/js/authentication-and-users?id=retrieve-user-by-phone-number

**Comment by krishna11124** [comment]
I Integrate Your Code It is Given

 Retriveuser error is-->{"code":422,"info":{"errors":{"id":["should be a positive integer"]}}}
