### ISSUE TITLE
VideoChat Sample does not work

### ISSUE THREAD

**Issue by ErnesII** [ConnectyCube/connectycube-reactnative-samples#153]
I just followed this guide: https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat
and I was able to run the app on two physical devices: Redmi and Samsung and I was able to make a call but the remote stream seems that is not working.

Also my first try implementing this lib was based on this guide: https://developers.connectycube.com/js/videocalling
because I like to see a cleaner code but it didnt work really well with react 0.60.0. Also I had to add these lines when receiving a call:
` session.getUserMedia(mediaParams).then(stream => {
       session.accept({});
   });
`
without these lines i could not saw any remote stream. But if i add those lines i can see in one phone the remote stream.

It seems that this lib is really well documented but maybe some parts are out of date. I would really like to implement this lib in my project but it seems unstable.

Thank you!

**Comment by DaveLomber** [comment]
Hi @ErnesII 

The code sample https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat works just well 

Could you please explain in more details what does 'but the remote stream seems that is not working.' ?
We will try to help here


On the `session.getUserMedia(mediaParams).then(stream => { session.accept({}); });` part - agree! Let us modify the doc and make it clearer. Thank you for mentioned this

**Comment by DaveLomber** [comment]
Updated documentation https://developers.connectycube.com/js/videocalling?id=accept-a-call

**Comment by DaveLomber** [comment]
@ErnesII let us know more regarding code sample issue
