### ISSUE TITLE
Getting Noise in audio when having video calling

### ISSUE THREAD

**Issue by priyankasaini3** [ConnectyCube/connectycube-reactnative-samples#155]
Getting Noise in audio when having video calling may be due to ---(audio from speaker of phone is getting feedback into the mic of the phone creating a audio feedback loop) so can you please provide a solution for that.

**Comment by DaveLomber** [comment]
@priyankasaini3 do your 2 phones are close to each other or different rooms?

**Comment by priyankasaini3** [comment]
They are closer to each other means they are in same room.

**Comment by DaveLomber** [comment]
Can you try diff rooms?

**Comment by priyankasaini3** [comment]
Yes I tried it in different rooms and they worked fine in that case
