### ISSUE TITLE
Does Custom Identity Provider require remote url?

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#156]
So can I use `localhost` with Custom Identity Provider?

This does not work for me:
<img width="585" alt="Screenshot 2020-11-30 at 23 48 46" src="https://user-images.githubusercontent.com/40718272/100679127-b453be80-3366-11eb-801b-6847c3c844cc.png">

If this does not work, it should work. As this should allow Redirects

**Comment by DaveLomber** [comment]
Yes it does require a remote url, cause ConnectyCube backend performs a remote url call verification

More understanding on the the backround process can be obtained in this article https://developers.connectycube.com/guides/custom-identity-provider
