### ISSUE TITLE
[Question] Password reset mechanism?

### ISSUE THREAD

**Issue by ethanx94** [ConnectyCube/connectycube-reactnative-samples#158]
Looking at the docs here, it's a bit ambiguous about what happens when a call is made to reset a user's password. Is this actually sending a password reset email to the user or what exactly happens when the method is called?

![image](https://user-images.githubusercontent.com/4449468/100797445-1efd0c80-33f0-11eb-991f-8e5cc82a6b24.png)

**Comment by DaveLomber** [comment]
You are right

If provided email is valid - an email with password reset instruction will be sent to it.

We added the required corrections to the docs, thank you !
