### ISSUE TITLE
Attachment Upload Progress

### ISSUE THREAD

**Issue by mikeangelsilva** [ConnectyCube/connectycube-reactnative-samples#159]
Does the react native sdk supports upload progress in single or multiple uploads?

Thanks!!

**Comment by DaveLomber** [comment]
@mikeangelsilva a 'fetch' API is used under the hood in `ConnectyCube.storage.createAndUpload` which does not support the upload progress 

https://developers.connectycube.com/js/messaging?id=attachments-photo-video

As an alternative way:
- call `ConnectyCube.storage.create`
- use some other lib to upload a file, with progress
- call `ConnectyCube.storage.markUploaded({ id: xx, size: cc })`

**Comment by mikeangelsilva** [comment]
Thanks for the reply.

Also wanna ask about video calling.
We want to integrate a face filter sdk/augmented reality sdk in video
calls.
Is it possible to do that?

Thank You.

**Comment by DaveLomber** [comment]
This is expected behaviour for 1-1 

What I can suggest is to have some hash variable with opponentId -> dialogId and then look into it to get a dialogId for participantID

**Comment by DaveLomber** [comment]
Yes it should be possible

There are many libs that allow to do it, 

for example 
https://github.com/jeeliz/jeelizFaceFilter

You have an access to media stream , so basically you can attach the lib to it to get filters
