### ISSUE TITLE
Error running RNChat

### ISSUE THREAD

**Issue by vabic** [ConnectyCube/connectycube-reactnative-samples#16]
TypeError: TypeError: null is not an object (evaluating '_reactNativeSetSoftInputMode.default.set')

This error is located at:
    in Auth (created by Context.Consumer)
    in Connect(Auth) (at navigationStore.js:448)
    in Wrapped (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:478)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.js:477)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.js:476)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:71)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at View.js:45)
    in View (at screens.native.js:101)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.js:400)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at View.js:45)
    in View (at Transitioner.js:141)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:57)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at Router.js:97)
    in App (at Router.js:122)
    in Router (at router.js:59)
    in AppRouter (created by Context.Consumer)
    in Connect(AppRouter) (at Root.js:51)
    in AppRoot (created by Context.Consumer)
    in Connect(AppRoot) (at App.js:10)
    in Provider (at App.js:9)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

This error is located at:
    in NavigationContainer (at Router.js:97)
    in App (at Router.js:122)
    in Router (at router.js:59)
    in AppRouter (created by Context.Consumer)
    in Connect(AppRouter) (at Root.js:51)
    in AppRoot (created by Context.Consumer)
    in Connect(AppRoot) (at App.js:10)
    in Provider (at App.js:9)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)
componentDidMount
    
commitLifeCycles
    react.development.js:1149:34
commitAllLifeCycles
    DeprecatedTransformPropTypes.js:54:40
invokeGuardedCallbackImpl
    
invokeGuardedCallback
    ToolbarAndroid.android.js:203:37
commitRoot
    normalizeColor.js:217:14
<unknown>
    MatrixMath.js:142:2
unstable_runWithPriority
    ReactNativeRenderer-prod.js:5703:2
completeRoot
    MatrixMath.js:20:19
performWorkOnRoot
    MatrixMath.js:63:26
performWork
    react-is.development.js:210
performSyncWork
    
requestWork
    react-is.development.js:94:7
scheduleWork
    react-is.production.min.js:13:259
enqueueSetState
    
setState
    KeyboardAvoidingView.js:77:4
dispatch
    navigationStore.js:566:28
dispatch
    navigationStore.js:128:3
replace
    navigationStore.js:224:27
execute
    navigationStore.js:141:41
<unknown>
    
tryCallOne
    ReactNativeRenderer-dev.js:4620:9
<unknown>
    ReactNativeRenderer-dev.js:4729:9
_callTimer
    ReactNativeRenderer-dev.js:9658:4
_callImmediatesPass
    ReactNativeRenderer-dev.js:9692:4
callImmediates
    ReactNativeRenderer-dev.js:9939:4
callImmediates
    [native code]
__callImmediates
    ReactNativeART.js:373:1
<unknown>
    
__guard
    ReactNativeART.js:359:6
flushedQueue
    
flushedQueue
    [native code]
invokeCallbackAndReturnFlushedQueue
    [native code]

**Comment by ccvlad** [comment]
Try new code from master branch. We've updated samples and got rid of setSoftInputMode dependency
