### ISSUE TITLE
How can i implement audio calling functionality with library

### ISSUE THREAD

**Issue by DevPurveshThakkar** [ConnectyCube/connectycube-reactnative-samples#160]
I have implemented the connectycube video calling functionality but i also want to implement audio calling functionality and i found one thing in code when video call gone connected at that time i am able to mute video but i want audio calling when i start calling to another user. Also I didn't found any specific code for audio chat stream. Can you help on this part.

**Comment by DaveLomber** [comment]
If you need an audio only call , you can remove `video: true` here

https://developers.connectycube.com/js/videocalling?id=access-local-media-stream 

If you want to be able to enable video during a call, then use  `video: true` here as well, 
and once a `stream ` is obtained, you can disable video track:

```
stream.getVideoTracks()[0].enabled = false
```


and then unmute later while on a call
