### ISSUE TITLE
Upload image via url link

### ISSUE THREAD

**Issue by mikeangelsilva** [ConnectyCube/connectycube-reactnative-samples#161]
I'm trying to upload an image using url.

Is this possible in the upload API?

Thanks

**Comment by DaveLomber** [comment]
Hi @mikeangelsilva 

It's not possible to upload an image using url.
There should be a file on a disk and represented by `File` object

Anyway, 
If you already have a file uploaded somewhere and you have an url, then
you can send the url directly in a chat message w/o uploading it 

This should work
