### ISSUE TITLE
add participant in ongoing conference video call

### ISSUE THREAD

**Issue by mikeangelsilva** [ConnectyCube/connectycube-reactnative-samples#164]
is it possible to add a participant in an ongoing video call session?

thanks

**Comment by DaveLomber** [comment]
Is it about p2p or conf calling?

**Comment by mikeangelsilva** [comment]
It is a conference calling.

Does it support?

Thank you

**Comment by DaveLomber** [comment]
Yes, you ca do it by sending a user a system message 

e.g.

```
const msg = {event: "callInvite", roomId: "xxx"};

ConnectyCube.chat.sendSystemMessage(userId, msg);
```

so then this user receives the message and can join into room by `roomId ` param

https://developers.connectycube.com/js/messaging?id=system-messages
