### ISSUE TITLE
Android push notification broken with connectycube-reactnative 1.8.1

### ISSUE THREAD

**Issue by selfcreator** [ConnectyCube/connectycube-reactnative-samples#165]
Hi guys, my project is still using connectycube-reactnative 1.8.1 and it seems the push notifications on Android broke for several months but iOS still works well.
Is there a known issue about this situation? Do I have to upgrade to version 2.+?

Thanks!

**Comment by DaveLomber** [comment]
there are no much diff between 1.x / 2.x / 3.x in terms of push notifications 

Could you please check the following:
1) Google API key is valid (which is set in ConnectyCube Dashboard)
2) a user you send a push to has Android push notification subscription. You can go to ConnectyCube Dashboard, Users module, find a user, open its profile and there will be a list of push subscriptions

**Comment by selfcreator** [comment]
@DaveLomber thanks for the answer, I finally found out it's because another developer adds another receiver in the manifest...
