### ISSUE TITLE
How to get all notifications?

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#167]
I would like to build a notifications list to show users all notifications, to show user all past notifications and current notification on a tab in my app.

How does one do this?

(Imagine similar to instagram's notifications tab)

**Comment by ccvlad** [comment]
Unfortunately, we don't have API for this. Could you describe your case more detailed? We will try to help you find a solution

**Comment by stephanoparaskeva** [comment]
> Unfortunately, we don't have API for this. Could you describe your case more detailed? We will try to help you find a solution

Ah, ok thank you.

So I'm trying to build something like Instagram's Notification Screen. For example in this screenshot:
<img width="385" alt="Screenshot 2020-12-15 at 17 40 47" src="https://user-images.githubusercontent.com/40718272/102251425-af614400-3efc-11eb-97f0-bebca278990a.png">

Where you can see previous notifications from today, or days gone. How can this be done using connectycube and it's messaging/notification system?

**Comment by ccvlad** [comment]
You can use our [Custom Objects API](https://developers.connectycube.com/server/custom_objects?id=custom-objects-api). It's an online DB where you are able to build your own data structure or schema for data.

```javascript
ConnectyCube.data.list(className, filters)
ConnectyCube.data.create(className, data)
ConnectyCube.data.update(className, data)
ConnectyCube.data.delete(className, data)
```

It will not be very easy to do this in application's background, cause you will need to start background process by push notification to init ConnectyCube to call the method `ConnectyCube.data.create(className, data)`.

We use a similar logic for call's history. We store messages via Custom Objects API and have a case when user have missed a call (stores in Custom Objects by push notification in background state).

**Comment by stephanoparaskeva** [comment]
> You can use our [Custom Objects API](https://developers.connectycube.com/server/custom_objects?id=custom-objects-api). It's an online DB where you are able to build your own data structure or schema for data.
> 
> ```js
> ConnectyCube.data.list(className, filters)
> ConnectyCube.data.create(className, data)
> ConnectyCube.data.update(className, data)
> ConnectyCube.data.delete(className, data)
> ```
> 
> It will not be very easy to do this in application's background, cause you will need to start background process by push notification to init ConnectyCube to call the method `ConnectyCube.data.create(className, data)`.
> 
> We use a similar logic for call's history. We store messages via Custom Objects API and have a case when user have missed a call (stores in Custom Objects by push notification in background state).

No I only need this data for *RECEIVER* for 1 user:
<img width="1399" alt="Screenshot 2020-12-17 at 21 24 49" src="https://user-images.githubusercontent.com/40718272/102545588-5d602000-40ae-11eb-85e5-fde5c01dce13.png">


E.g
For User A, get me last 100 notifications received in Queue  (NOT SENT)

**Comment by stephanoparaskeva** [comment]
@ccvlad @DaveLomber 

Can someone help me do this, it is a big blocker for my application. As my app needs a way to view and organise notifications to help users interact with history and accept requests.

**Comment by ccvlad** [comment]
> You can use our [Custom Objects API](https://developers.connectycube.com/server/custom_objects?id=custom-objects-api). It's an online DB where you are able to build your own data structure or schema for data.
> 
> ```js
> ConnectyCube.data.list(className, filters)
> ConnectyCube.data.create(className, data)
> ConnectyCube.data.update(className, data)
> ConnectyCube.data.delete(className, data)
> ```
> 
> It will not be very easy to do this in application's background, cause you will need to start background process by push notification to init ConnectyCube to call the method `ConnectyCube.data.create(className, data)`.
> 
> We use a similar logic for call's history. We store messages via Custom Objects API and have a case when user have missed a call (stores in Custom Objects by push notification in background state).

@stephanoparaskeva 
Store notifications in online DB (Custom Objects) as we do not have the API to get all notifications for user. Also I agree with you that the API to list all notification is the best solution for current case. I will be pushing our BE team to add this feature. It will be useful for us to have this functionality.

We will update you after discuss the issue.

**Comment by DaveLomber** [comment]
Hi @stephanoparaskeva 
what kind of app are you building? 

I just want to understand what type of notifications should be displayed  there

**Comment by stephanoparaskeva** [comment]
> Hi @stephanoparaskeva
> what kind of app are you building?
> 
> I just want to understand what type of notifications should be displayed there

Hi @DaveLomber 
The app is quite complicated with regards to notifications. It is all based on notifications. You schedule calls and receive notifications the time it is ready to make the call. For this I need a notification list and scheduled notifications. I know connectycube has scheduled notifications which is great. But the user must be able to also *see* a list of all previous (and perhaps scheduled) notifications and then interact with this list. This is the core premise of my app. I cannot say much more as I've been heavily developing for 2 years and would like to turn this into a production ready app.

I only need a HTTP Rest Endpoint e.g. /connectycube/mynotifications etc to get previous and scheduled notifications. And pick last 100, skip 0 etc

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
