### ISSUE TITLE
Message Not being Sent

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#169]
I am using the opponent id eg: 3030123 and sending a chat message via 1 on 1 chat. The onMessage listener on the other device never runs and no messages are listed in the dialog:

### Screenshot

![Screenshot 2020-12-18 at 19 30 02](https://user-images.githubusercontent.com/40718272/102653832-74af1400-4167-11eb-8094-530758f27ea1.png)

### Code

```ts
const ChatModal = ({ navigation, route }: TRatingProps) => {
  const [messages, setMessages] = useState([]);
  const recipient = route?.params?.user;
  const dialog = route?.params?.dialog;

  const close = () => navigation.goBack();
  const send = async () => {
    const message = {
      type: 3,
      body: 'hello world',
      extension: {
        save_to_history: 1,
        dialog_id: dialog._id,
      },
      markable: 1,
    };
    console.warn(dialog);
    try {
      console.warn(ConnectyCube.chat.send);
      const x = await ConnectyCube.chat.send(recipient?.cubeId, message);
    } catch (err) {
      console.warn(err);
    }
  };

  const params = {
    chat_dialog_id: dialog?._id,
    sort_desc: 'date_sent',
    limit: 100,
    skip: 0,
  };

  useEffect(() => {
    ConnectyCube.chat.message.list(params).then(console.warn).catch(console.warn);
  }, []);

  return (
    <KeyboardAvoidingView style={styles.root} behavior='padding'>
      <CommonText style={styles.closeText}>{recipient.name}</CommonText>
      <TouchableOpacity onPress={close} style={styles.closeButton}>
        <CommonText style={styles.closeText}>Close</CommonText>
      </TouchableOpacity>
      <View>
        <TextInput style={styles.textInput} />
        <TouchableOpacity onPress={send} style={styles.sendButton}>
          <CommonText style={styles.submitButtonText}>Send</CommonText>
        </TouchableOpacity>
      </View>
    </KeyboardAvoidingView>
  );
};

```

When viewing Network Inspector, it seems that this function does not make a network request at all.

Version:
`    "react-native-connectycube": "^3.7.8",`

**Comment by DaveLomber** [comment]
Are you connected to chat before using `ConnectyCube.chat.send` ? If not then it will not work.
Make sure you are connected to chat by calling `ConnectyCube.chat.connect`

Regarding Network requests, the `ConnectyCube.chat.send` call does not do a common XHR request.
Instead you should look into WSS tab -  

<img width="770" alt="Screenshot 2020-12-19 at 10 21 38" src="https://user-images.githubusercontent.com/39332586/102684760-13795600-41e4-11eb-928a-abfea30b6afe.png">

**Comment by stephanoparaskeva** [comment]
@DaveLomber I am connected when checking `ConnectyCube.chat.isConnected`. I see, thank you for explaining this to me.
But even still, no messages actually get created and stored to the dialog when calling `ConnectyCube.chat.send`, I can only get it to work when making an `axios` request.


By the way, is there any other way of contacting if I get anymore questions, I'd really appreciate that, rather than having to make an issue on these great Repo's every time I run into a small problem that I cannot myself fix.

**Comment by DaveLomber** [comment]
@stephanoparaskeva it's totally fine to create GitHub issues as many as you need ;) 

Let's check the following:

1) what you see in WS tab, Messages section (as shown in my screenshot above)?
2) what you see in browser console log when send a message ?

**Comment by stephanoparaskeva** [comment]
> @stephanoparaskeva it's totally fine to create GitHub issues as many as you need ;)
> 
> Let's check the following:
> 
> 1. what you see in WS tab, Messages section (as shown in my screenshot above)?
> 2. what you see in browser console log when send a message ?

Awesome okay!
This works
```ts
      return cubeWrap(() => ({
        method: 'post',
        url: 'https://api.connectycube.com/chat/Message',
        data: {
          recipient_id: recipient?.cubeId,
          type: 3,
          markable: 1,
          message: msg,
          send_to_chat: 1,
        },
      }));
```

This does not:

```ts
ConnectyCube.chat.send(recipient?.cubeId, message)
```

**Comment by ccvlad** [comment]
@stephanoparaskeva 
Could you enable a [logger](https://developers.connectycube.com/js/?id=configuration) and provide logs after `ConnectyCube.chat.send(recipient?.cubeId, message)` ?

**Comment by aravi365** [comment]
> ```ts
> https://api.connectycube.com/chat/Message
> ```

Same issue with me, but not working even when called via axios or postman as it returns a 404 or   "The recipient wasn't found" error everytime for a valid recepient id in the dashboard.

**Comment by aravi365** [comment]
@stephanoparaskeva  could you please guide me how to add the onMessage listeners in function components. Looks like you have used function components in your project.

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
