### ISSUE TITLE
Push notification not working

### ISSUE THREAD

**Issue by godwin12345** [ConnectyCube/connectycube-reactnative-samples#17]
Dear Team,

  We can successfully subscribe, but during chat push notification not receiving. Why? Any Idea?

Thanks.

**Comment by DaveLomber** [comment]
@godwin12345 Could you check the setting enabled in Admin panel

- go to https://admin.connectycube.com
- Chat module
- Offline notifications tab
- 'ENABLE AUTOMATIC NOTIFICATIONS FOR OFFLINE USERS IN CHAT' checkbox

**Comment by godwin12345** [comment]
Dear,
 The settings was already enabled and i reconfirmed.
Thanks

**Comment by ccvlad** [comment]
Closing the issue as resolved. Please raise a separate issue in case of any other questions.

**Comment by DaveLomber** [comment]
In a case for further reference - we prepared a complete guide on how to integrate push notifications in React Native

 
https://developers.connectycube.com/reactnative/push-notifications
