### ISSUE TITLE
OnMessageListener never fired

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#170]
```ts
// Doing this way because  ConnectyCube.chat.send(dialog._id || recipientId, message) does not work.
const cubeToken = ConnectyCube?.auth?.proxy?.sdkInstance?.session?.token;
  const y = await axios({
        method: 'post',
        url: 'https://api.connectycube.com/chat/Message',
        data: {
          recipient_id: recipient?.cubeId,
          message: 'where are you?',
        },
        headers: { 'CB-Token': cubeToken },
      });
      console.warn(y);
```
### console.warn of y:
> { "data":  { "_id": ....... }

--- 

### Other phone:

```ts
    ConnectyCube.chat.onMessageListener = () => console.warn('MESSAGE RECEIVED');
```

 Never gets called.

Version:
`    "react-native-connectycube": "^3.7.8",`

**Comment by DaveLomber** [comment]
If you want to send messages via REST API and to be them delivered in real time, just add one more parameter: `send_to_chat: 1`

**Comment by DaveLomber** [comment]
as described here https://developers.connectycube.com/server/chat?id=create-a-message

**Comment by stephanoparaskeva** [comment]
This has worked, thank you! 
@DaveLomber

**Comment by aravi365** [comment]
> This has worked, thank you!
> @DaveLomber

`ConnectyCube.chat.onMessageListener = () => console.warn('MESSAGE RECEIVED');
`
i am in doubt, where to add this code inorder to catch the live messages in the chat. I am using function components instead of class. @DaveLomber  @stephanoparaskeva
