### ISSUE TITLE
Network request failed

### ISSUE THREAD

**Issue by meosieudang** [ConnectyCube/connectycube-reactnative-samples#172]
when i login account to admin dashboard, sometime i get this error: Network request failed
![Screen Shot 2020-12-21 at 15 38 04](https://user-images.githubusercontent.com/45912335/102756632-c5f71780-43a2-11eb-9104-adbe00962a78.png)
![Screen Shot 2020-12-21 at 15 38 12](https://user-images.githubusercontent.com/45912335/102756642-cd1e2580-43a2-11eb-9d86-e25471d7d11c.png)

        "react-native": "0.63.2",
    "react-native-connectycube": "^3.7.7"

**Comment by Mani1124** [comment]
Same here

**Comment by DaveLomber** [comment]
@Mani1124 @meosieudang which dashboard are you referring to?

Is it https://admin.connectycube.com ?

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
