### ISSUE TITLE
Messages history does not include new message, always 1 message behind.

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#174]
I am trying to build 1-to-1 chat, when user sends message, useMutation (from `react-query`) is fired. onSuccess, the chat history is refetched. But the new message is not there:

### Working example:
```ts
  const getDialogHistory = () => dialog._id && ConnectyCube.chat.message.list(params);

  const history = useQuery<THistory>(['history.query', dialog._id], getDialogHistory);


  const MessageInput = () => {
    const [text, setText] = useState('');

    const send = async (msg: string) => {
      if (!msg) return;

      return cubeWrap(() => ({
        method: 'post',
        url: 'https://api.connectycube.com/chat/Message',
        data: {
          recipient_id: recipient?.cubeId,
          type: 3,
          markable: 1,
          message: msg,
          send_to_chat: 1,
        },
      }));
    };

    const msgMutation = useMutation(send, {
      onSuccess: (result: any) => {
        console.warn(result);
        history.refetch();
      },
    });

    return (
      <KeyboardAvoidingView behavior='padding'>
        <TouchableOpacity
          onPress={() => msgMutation.mutate(text)}
          style={styles.sendButton}>
          <CommonText style={styles.sendButtonText}>Send</CommonText>
        </TouchableOpacity>
        <TextInput onChangeText={setText} style={styles.textInput} />
      </KeyboardAvoidingView>
    );
  };
```

#### Below, is the message list. This is 1 message behind when you press send:
```ts
  const MessageList = () => (
    <FlatList
      data={history?.data?.items}
      keyExtractor={item => item?._id}
      renderItem={({ item }) => <Text>{item.message || ''}</Text>}
    />
  );
```

**Comment by Friscas** [comment]
I also have the same issue. Did you find a solution? 

I'm building the chat in OpenUI5 and when the onMessageListener events get fired I reload the model with the new data but the latest message is not there.

**Comment by DaveLomber** [comment]
@stephanoparaskeva 

- I do not recommend to call ConnectyCube API and get chat history on every message sent. It will produce tons of extra unneeded API calls. When you send a message - you already have it - do not need to request it from server. Just save it to you local array 
- And regarding the reason why you face this issues - sending a message is async operation, it does not immediately put a message to history, but only after some ms, e.g. 100-300 whatever. This is why you dod not have a message yet returned.

**Comment by DaveLomber** [comment]
@Friscas FYI
