### ISSUE TITLE
How to turn OFF Chat Message Notification when app is closed?

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#175]
My app sends notification with chat message when app is closed. I want to turn this OFF. The reason I want to turn this off is because I am implementing this myself with ConnectyCube.notifications.push instead, so my app sends TWO notifications when app is closed. I want to turn this default behaviour off. This is so I can have the same logic to handle application in background as well. E.g:

```ts
    const createMessageReq = async (msg: string) => {
      const x = await cubeWrap(() => ({
        method: 'post',
        url: 'https://api.connectycube.com/chat/Message',
        data: {
          recipient_id: recipient.data?.cubeId,
          type: 3,
          markable: 1,
          message: msg,
          send_to_chat: 1,
        },
      }));


       // Manually send notification on message sent
      const payload = JSON.stringify({
        message: x?.data?.message,
      });
      const pushParameters = {
        notification_type: 'push',
        user: { ids: [recipient.data?.cubeId] }, // recipients.
        environment: __DEV__ ? 'development' : 'production',
        message: ConnectyCube.pushnotifications.base64Encode(payload),
      };
      await ConnectyCube.pushnotifications.events.create(pushParameters);
    };

    const send = useMutation(createMessageReq, {
      // @ts-ignore
      onSuccess: (result: any) => {
        history.refetch();
        queryClient.refetchQueries(DIALOGS_QUERY);
      },
    });

```

![IMG_0372](https://user-images.githubusercontent.com/40718272/103089791-021aba00-45e7-11eb-92f5-0ca646946519.jpg)

**Comment by DaveLomber** [comment]
you can go to Admin panel, Chat page, Offline notifications and disable pushes for offline users when send a chat 

<img width="875" alt="Screenshot 2020-12-24 at 16 03 52" src="https://user-images.githubusercontent.com/39332586/103092960-a4e03200-4601-11eb-990c-fc2e411fb211.png">

**Comment by stephanoparaskeva** [comment]
> you can go to Admin panel, Chat page, Offline notifications and disable pushes for offline users when send a chat 
> 
> 
> 
> <img width="875" alt="Screenshot 2020-12-24 at 16 03 52" src="https://user-images.githubusercontent.com/39332586/103092960-a4e03200-4601-11eb-990c-fc2e411fb211.png">
> 
> 
> 
> 

Thank you, this is perfect!
