### ISSUE TITLE
filterdialog

### ISSUE THREAD

**Issue by Krishna8077078** [ConnectyCube/connectycube-reactnative-samples#179]
How to filter dialog user name with phonebook contact name is this possible??

**Comment by ccvlad** [comment]
@Krishna8077078 

Contacts are from your phone contact book (its were created by you). You are able to post/update/get/delete the contact's book via API.
Connectycube user is creating by each new user. It isn't expect that contact's name and user's name are match.
A private dialog's name depends on the opponent's `full_name` (user_A sees user_B's name and vice versa).

Try to match contact's `phone number` with user `phone` and user `id` with dialog's `occupants_ids` array.

```javascript
const userPhoneNumber  = someContact.phone;
const user = await ConnectyCube.users.get({ phone: userPhoneNumber })); // get Connectycube user by phone number
const dialogsListResponse = await ConnectyCube.chat.dialog.list({ type: 3, name: user.full_name }); // get a response with private dialogs and matched name from server
const dialogs = dialogsListResponse.items; // dialogs from the response
const dialog = dialogs.find(dialog => dialog.occupants_ids.some(id => (id === user.id))); // find the dialogs
```
