### ISSUE TITLE
not able to install in RN using npm install. getting error

### ISSUE THREAD

**Issue by Jayaprakashwins** [ConnectyCube/connectycube-reactnative-samples#180]
Thank you for using react-native-elements!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/react-native-elements/donate

> ConnectyCubeChatCodeSample@1.0.1 postinstall C:\Users\JP\ReactNative\Erramma\connectycube-reactnative-samples-master\RNChat
> npx jetify && cd ios && pod install

Jetifier found 1138 file(s) to forward-jetify. Using 8 workers...
'pod' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ConnectyCubeChatCodeSample@1.0.1 postinstall: `npx jetify && cd ios && pod install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ConnectyCubeChatCodeSample@1.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JP\AppData\Roaming\npm-cache\_logs\2020-12-30T10_54_29_872Z-debug.log

**Comment by ccvlad** [comment]
You should follow [React Native CLI Quickstart](https://reactnative.dev/docs/environment-setup) and finish all installations for iOS.
`'pod' is not recognized as an internal or external command` === XCode CocoaPods is not installed.

**Comment by Jayaprakashwins** [comment]
Hi , But I want only android.

**Comment by Jayaprakashwins** [comment]
Hi ccvlad, Thanks for your imemdiate response. I changed the below line in packages.json and issue resolved.    "postinstall": "npx jetify",
