### ISSUE TITLE
Creating private dialog returns error ["Occupants_ids is missing opponent ID."]

### ISSUE THREAD

**Issue by mikeangelsilva** [ConnectyCube/connectycube-reactnative-samples#181]
tried creating a private dialog but returns error.

im using this code.

const params = {
  type: 3,
  occupants_ids: [3175426],
};

ConnectyCube.chat.dialog
  .create(params)
  .then((dialog) => {})
  .catch((error) => {});

![image](https://user-images.githubusercontent.com/38802880/103472605-40c02980-4dca-11eb-9d63-d4d9199e01f6.png)

please help thank you.

**Comment by ccvlad** [comment]
Does the user with id = 3175426 exist?

**Comment by mikeangelsilva** [comment]
fixed. thanks

**Comment by sagarpatel288** [comment]
> Does the user with id = 3175426 exist?

How to check that 😬

**Comment by sagarpatel288** [comment]
> fixed. thanks

How did you fix it? 😬
