### ISSUE TITLE
Sometimes end call is not reported to other phone

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#184]
#### Using
-  IOS & Android
- `react-native-voip-push`
-  `react-native-callkeep`

---

Sometimes I will make a call, the call rings on other phone. If I end the call on initiator phone then sometimes the other phone keeps ringing.

User A calls User B
User A ends call before answer
User B phone still rings

#### OR

The opposite does not work sometimes

User A calls User B
User B rejects the call
User A is still calling

(Both work sometimes, and sometimes don't work)

---

*I am aiming for 100% reliability.*

My code is below:
https://pastebin.com/6Zv8Jg1e

**Comment by DaveLomber** [comment]
@stephanoparaskeva  do you have any specific day hours where it happens? If so - please report

**Comment by stephanoparaskeva** [comment]
> @stephanoparaskeva do you have any specific day hours where it happens? If so - please report

This happens almost any time per day I believe, sometimes things are just delayed

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
