### ISSUE TITLE
Can’t track down this unhandled exception

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#185]
Sometimes when making a call during connecting state

I get this 
![image](https://user-images.githubusercontent.com/40718272/103684213-21b8c780-4f83-11eb-895b-7db002703e3c.png)
![image](https://user-images.githubusercontent.com/40718272/103684219-241b2180-4f83-11eb-9434-1f9b1afba579.png)

**Comment by DaveLomber** [comment]
@stephanoparaskeva I think you initiate a call while the chat is still in connecting state 

Please make sure that chat is connected at the time you make a call

https://developers.connectycube.com/js/messaging?id=connect-to-chat

https://developers.connectycube.com/js/messaging?id=connection-status

**Comment by stephanoparaskeva** [comment]
> @stephanoparaskeva I think you initiate a call while the chat is still in connecting state
> 
> Please make sure that chat is connected at the time you make a call
> 
> https://developers.connectycube.com/js/messaging?id=connect-to-chat
> 
> https://developers.connectycube.com/js/messaging?id=connection-status

Thank you
