### ISSUE TITLE
Muting camera will freezing the video

### ISSUE THREAD

**Issue by mikeangelsilva** [ConnectyCube/connectycube-reactnative-samples#190]
How can i turn to black the video to the other users in the call when someone turn off ther camera?

Its always freezing.

Or am i missing something?

Thanks

**Comment by ccvlad** [comment]
Hi, @mikeangelsilva 
It is expected behavior for current case. You should send system message to other occupants that you have muted video. Each occupant will receive the message and resolve video stream state (mute/unmute) on UI.
