### ISSUE TITLE
Connectycube connects to chat server too late. (RN Voip and Call-Keep)

### ISSUE THREAD

**Issue by CMLCNL** [ConnectyCube/connectycube-reactnative-samples#192]
Hello, I use voip push to wake up an application. RN call-keep works right after waking the application with Voip. However, these are happening on the native side. On the Rn side, call-keep works before I connect to the chat. As soon as the user answers the call, only the open application comes in front of him. How can we synchronize both.

```
- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
  // Process the received push
  [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:(NSString *)type];
  
  NSObject* aps = payload.dictionaryPayload[@"aps"];
  
  NSString* alert = [aps valueForKey:@"alert"];
  
  NSLog(@"%@", alert);
  
  NSData *webData = [alert dataUsingEncoding:NSUTF8StringEncoding];
  NSError *error;
  NSDictionary *jsonDic = [NSJSONSerialization JSONObjectWithData:webData options:NSJSONReadingMutableContainers error:&error];

  NSLog(@"%@", jsonDic);
  
  NSString *uuid = [jsonDic valueForKey:@"uuid"];
  NSString *callerName = [jsonDic valueForKey:@"callerName"];
  NSString *handle = [jsonDic valueForKey:@"handle"];

  NSLog(@"%@ %@ %@", handle,callerName,uuid);
  
  BOOL hasVideo = NO;
  
  if ([[jsonDic valueForKey:@"hasVideo"] isEqualToString:(@"1")]) {
    hasVideo = YES;
  } else {
    hasVideo = NO;
  }
  
  if([[UIApplication sharedApplication] applicationState] != UIApplicationStateActive)
  {
      [RNCallKeep reportNewIncomingCall: uuid
                               handle: handle
                           handleType: @"generic"
                             hasVideo: hasVideo
                  localizedCallerName: callerName
                      supportsHolding: NO
                         supportsDTMF: YES
                     supportsGrouping: NO
                   supportsUngrouping: NO
                          fromPushKit: YES
                              payload: nil
                withCompletionHandler: completion];
  }
```

**Comment by DaveLomber** [comment]
@CMLCNL Is this a P2P call?

In general, the flow should be the following:

1) UserA starts to call UserB. SDK sends call requests via Chat every 5 seconds. This is managed by `videochat.dialingTimeInterval` config.
Also, UserA sends a VoIP push notification.

2) At UserB side, the app is in bg or closed. 
UserB receives the VoIP push and display CallKit UI.
Then UserB accepts the call, which triggers the app to launch. 

3) Once app is launched at UserB side, you perform login + chat connect. 
Once chat is connected, UserB will receive one of the dialing messages via Chat and can perform `accept` https://developers.connectycube.com/js/videocalling?id=accept-a-call


Is this how you are trying to implement it?

**Comment by CMLCNL** [comment]
I'm doing what you say. Do you yourself use this connectycube? Because it takes a long time to connect to the chat server. Sometimes it takes 5 seconds to connect. I successfully show CallKit ui with voip notification. However, I cannot answer the call while on the Lock screen. Most of the time, the request cannot be sent. Application that falls off the socket. Listeners may not be working.

**Comment by DaveLomber** [comment]
@CMLCNL the call request duration is managed by   `videochat.answerTimeInterval` config and set to 60 seconds by default, 
so mainly a user should have enough time to answer 

Once a user accepted a call via CallKit screen -> run your app, show Call screen. 
Then connect to chat and listen for incoming call request which you need to accept automatically

**Comment by CMLCNL** [comment]
I tried what you said, but I am having trouble connecting to http requests and sometimes socket service. If the application is on the Lock screen and I answer the call from Callkit, then sometimes I cannot connect to the http request and socket service. Most of the time cb listeners don't work either. I'm getting a warning that Connection is not offline.

**Comment by CMLCNL** [comment]
I'm sending voip push via connectycube.
When there is a push on the native side, callkit works. How do I make CallKit work on js side? If I remove the call kit on the native side, the application only runs for a few seconds.

I don't use it because the application keeps running with voip for a few seconds. When voip notification arrives.

`RNCallKeep.displayIncomingCall(uuid, handle, localizedCallerName);`


Whenever I use it like that. Then the application is fully working. But most of the time I cannot answer calls on the lock screen. Something is happening that I don't understand. Connection is not offline on console.

```
[RNCallKeep reportNewIncomingCall: uuid
                               handle: handle
                           handleType: @"generic"
                             hasVideo: hasVideo
                  localizedCallerName: callerName
                      supportsHolding: NO
                         supportsDTMF: YES
                     supportsGrouping: NO
                   supportsUngrouping: NO
                          fromPushKit: YES
                              payload: nil
                withCompletionHandler: nil];
```

**Comment by meosieudang** [comment]
me too

**Comment by DaveLomber** [comment]
@meosieudang @CMLCNL I think the best way will be to implement it on our side an integrate in P2P code sample.
Will try to dod it this week and share

**Comment by DaveLomber** [comment]
As for the progress tracking - here is an MR https://github.com/ConnectyCube/connectycube-reactnative-samples/pull/200

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
