### ISSUE TITLE
Security Concern - API keys and Secret

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#193]
These keys are stored on the front end. So every client has access to the secret and keys, meaning they can use the API E.g:

```ts 

{
    appId: 385,
    authKey: 'DFBMs5-dKBBCXcd',
    authSecret: 'SkCW -ThdnmRg9Za',
}
```

How can one do this and configure without the client ever knowing the AppID,authKey, authSecret or API keys?

**Comment by ccvlad** [comment]
This way can be useful - https://github.com/ConnectyCube/connectycube-js-sdk-releases/issues/64#issuecomment-753909198
