### ISSUE TITLE
Group Handle

### ISSUE THREAD

**Issue by Krishna8077078** [ConnectyCube/connectycube-reactnative-samples#196]
Hi In This Sdk Have this features on Group Chat:-
Add option to: -Delete member -Block member -Report member -Export Chat -Share Group -Delete Group -Suspend Group

**Comment by ccvlad** [comment]
If you about a group chat or public:

Regular user:
- [block user](https://developers.connectycube.com/js/messaging?id=privacy-black-list)
- delete dialog for themself (`ConnectyCube.chat.dialog.delete(dialogId)`)
- share invite (send dialogId to user(s). User have to subscribe - `ConnectyCube.chat.dialog.subscribeToPublic(dialogId)`)

Admin: 
- [add/delete new member(s)](https://developers.connectycube.com/js/messaging?id=addremove-occupants) - also for admin role
- regular user privileges

Owner/SuperAdmin (means a creator of a dialog - `dialog.user_id`):
- [add/delete admin](https://developers.connectycube.com/js/messaging?id=add-remove-admins)
- delete dialog for everyone (`ConnectyCube.chat.dialog.delete(dialogId, {force: 1})`)
- regular user privileges
- admin user privileges

See all role's privileges - https://developers.connectycube.com/server/chat?id=roles-and-privileges

____

- export chat (Is it the same with share invite?)
- suspend (It should be you implementation. Use message/systemMessages to send signal to occupants and suspend on each side)

____

Check our docs to find more information
