### ISSUE TITLE
encountered an error when having a video call and sending a chat message 

### ISSUE THREAD

**Issue by mikeangelsilva** [ConnectyCube/connectycube-reactnative-samples#197]
encountered an error when having a video call and sending a chat message to a group dialog and which the participants is in a video call also.

![image](https://user-images.githubusercontent.com/38802880/105174762-02629280-5b5e-11eb-9330-7806a0e34759.png)

that error recieves in other users.

any help on these please. 

thanks

**Comment by ccvlad** [comment]
Hi, @mikeangelsilva 

I can't understand the problem. You should check "last_message". Usually the error occurs after trying to rewrite a const. Could check a stack trace? The error's stack trace should be in the screenshot's trimmed part.
