### ISSUE TITLE
Remove participants from group??

### ISSUE THREAD

**Issue by Krishna8077078** [ConnectyCube/connectycube-reactnative-samples#199]
Hello, I want to know how to remove participants from the group, because I can't find any listener & method about remove participants from the group chat.

**Comment by DaveLomber** [comment]
please check the add/remove Users API doc https://developers.connectycube.com/js/messaging?id=addremove-occupants

**Comment by mikeangelsilva** [comment]
@DaveLomber  hi, what if the participant want to leave on the group?

is this the right code? 

const dialogId = "5356c64ab35c12bd3b108a41";
const toUpdateParams = { pull_all: { occupants_ids: [your_user_id] } };

ConnectyCube.chat.dialog
  .update(dialogId, toUpdateParams)
  .then((dialog) => {})
  .catch((error) => {});


the value of `your_user_id` is the participant id in the group dialog.

thanks

**Comment by DaveLomber** [comment]
When a user wants to leave the chat, it's better to simply delete the chat 


https://developers.connectycube.com/js/messaging?id=remove-dialog

**Comment by mikeangelsilva** [comment]
Thanks! Closed
