### ISSUE TITLE
'_reactNativeConnectycube.default.videochat.onCallListener

### ISSUE THREAD

**Issue by ahmi354** [ConnectyCube/connectycube-reactnative-samples#211]
<img width="792" alt="Screenshot 2021-03-09 at 9 22 01 PM" src="https://user-images.githubusercontent.com/62913134/110503071-a4920600-811d-11eb-9aff-7db3dfdcc490.png">
working fine on android but when i try to open it on ios i am getting the error any idea why ?

**Comment by ccvlad** [comment]
Is it the RNVideoChat sample? Did you change something i the code?

**Comment by ahmi354** [comment]
no i havent

**Comment by ccvlad** [comment]
@ahmi354 
1. `git clone git@github.com:ConnectyCube/connectycube-reactnative-samples.git`
2. `cd connectycube-reactnative-samples/RNVideoChat`
3. `npm install`
4. `npm run android` and start project from Xcode

Works for me:
<img width="1253" alt="Screen Shot 2021-03-15 at 14 16 52" src="https://user-images.githubusercontent.com/43810932/111152888-eeee0980-8599-11eb-8450-cef5c8788c67.png">

**Comment by kim-zhong** [comment]
I am encounting the same issue. I am using expo and tring to run the sample however everytime after I click login in it returns the error oncall listener cannot be null....

**Comment by SavinderSingh** [comment]
For this you have to install react-native-webrtc library, this will help you to solve this issue..

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
