### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating 'new _authService.default()')

### ISSUE THREAD

**Issue by devteamtalkag1** [ConnectyCube/connectycube-reactnative-samples#213]
This is the error I'm getting after integrating the RNVideoChat example, into my existing app !
It came with several other errors 
![image](https://user-images.githubusercontent.com/68539784/110637554-cdfa7280-81ad-11eb-8a46-cfe37a150e86.png)
Not really know where it's coming from or what is causing it !

**Comment by ccvlad** [comment]
Did you call `ConnectyCube.init(credentials, config)` ?

https://developers.connectycube.com/reactnative/?id=initialize

**Comment by devteamtalkag1** [comment]
Exact ! I dit it till the opening of the app, in the constructor same as in the example App !

**Comment by ccvlad** [comment]
Please, show your code with the method

**Comment by devteamtalkag1** [comment]
OK ! 
In my Main.js which serves as an opening file for the project, I do all the setting including the init :
![image](https://user-images.githubusercontent.com/68539784/110654871-d14a2a00-81be-11eb-94a3-d3c8c0a26a08.png)

and after I've simplified the screen on which I make the call by just navigating this way : 
![image](https://user-images.githubusercontent.com/68539784/110655149-179f8900-81bf-11eb-90c8-bf80c4b0f232.png)
and the rest point to the VideoScreen folder index screen as in the code sample as shown in the three here : 
![image](https://user-images.githubusercontent.com/68539784/110655482-62b99c00-81bf-11eb-8bed-6ad9a8ab82c9.png)

**Comment by ccvlad** [comment]
```javascript
import ConnectyCube from 'react-native-connectycube';

...

export default class AuthService {
  init = () => {
    ConnectyCube.init(...config);
    
    console.log(config);
    console.log(ConnectyCube)
  }
  
  ...
```

Modify your `AuthService.init()` to check logs.
