### ISSUE TITLE
switch between voice and video call within an ongoing call

### ISSUE THREAD

**Issue by arghyaMatrix** [ConnectyCube/connectycube-reactnative-samples#214]
I want to implement a feature to toggle between voice and video call within an ongoing call. how can I switch between voice and video call within an ongoing call? Please help me to achieve this feature

**Comment by DaveLomber** [comment]
For this you simply need to on/off camera

https://developers.connectycube.com/reactnative/videocalling?id=mute-video

**Comment by arghyaMatrix** [comment]
But muting video camera producing freezing of camera and again unmuting it it shows error no available video sources

**Comment by DaveLomber** [comment]
If it's freezing at receiver's side, 
we recommend to send system messages along with camera on/off
https://developers.connectycube.com/reactnative/messaging?id=system-messages

in this case, other user can hide/show video stream element
