### ISSUE TITLE
How to sort by custom data: Location on the react native SDK

### ISSUE THREAD

**Issue by onursezn** [ConnectyCube/connectycube-reactnative-samples#216]
Is there any example request that I can use for the sorting by custom data: Location on the react-native SDK? Any help would be appreciated. Thanks.

**Comment by DaveLomber** [comment]
@onursezn are you looking for sorting by 'nearest' ?

Then please use 'near' filter

https://developers.connectycube.com/server/custom_objects?id=_1-sorting

**Comment by alperbilgic** [comment]
The problem is that the given document does not describe the request data well. Should it be in json form and be like:
{
   'near': {
                  <field_name>: [latitude, longitude],
                  radius: 19999
    }
}

**Comment by DaveLomber** [comment]
@alperbilgic right, everything in JavaScript should be a JSON ;-D

**Comment by alperbilgic** [comment]
@DaveLomber Sir I also need to know the structure of the JSON object.
```
{
   'near': {
                  <field_name>: [latitude, longitude],
                  radius: 19999
    }
}
```

Is this structure in the right form? Are the field names and the value types that are passed correct?
