### ISSUE TITLE
cannot run RNChat sample code

### ISSUE THREAD

**Issue by wujianyy** [ConnectyCube/connectycube-reactnative-samples#219]
Read https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNChat and tried to compile the source code. The error message is shown. I paste the partial error code here. 

jian@tests-MacBook-Pro connectycube % cd connectycube-reactnative-samples/RNChat && npm install

> ConnectyCubeChatCodeSample@1.0.1 postinstall
> npx jetify && cd ios && pod install

Jetifier found 1138 file(s) to forward-jetify. Using 8 workers...
Auto-linking React Native modules for target `RNChat`: RNCAsyncStorage, RNCPushNotificationIOS, RNDeviceInfo, RNFastImage, RNGestureHandler, RNImageCropPicker, RNReanimated, RNScreens, RNVectorIcons, and ReactNativeAutogrowTextinput
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.63.0)
Installing FBReactNativeSpec (0.63.0)
Installing Folly (2020.01.13.00)
Installing QBImagePickerController (3.4.0)
Installing RCTRequired (0.63.0)
Installing RCTTypeSafety (0.63.0)
Installing RNCAsyncStorage (1.6.1)
Installing RNCPushNotificationIOS (1.0.5)
Installing RNDeviceInfo (5.5.1)
Installing RNFastImage (7.0.2)
Installing RNGestureHandler (1.5.2)
Installing RNImageCropPicker (0.27.0)
Installing RNReanimated (1.4.0)
Installing RNScreens (2.0.0-alpha.22)
Installing RNVectorIcons (6.6.0)
Installing RSKImageCropper (2.2.3)
Installing React (0.63.0)
Installing React-Core (0.63.0)
Installing React-CoreModules (0.63.0)
Installing React-RCTActionSheet (0.63.0)
Installing React-RCTAnimation (0.63.0)
Installing React-RCTBlob (0.63.0)
Installing React-RCTImage (0.63.0)
Installing React-RCTLinking (0.63.0)
Installing React-RCTNetwork (0.63.0)
Installing React-RCTSettings (0.63.0)
Installing React-RCTText (0.63.0)
Installing React-RCTVibration (0.63.0)
Installing React-callinvoker (0.63.0)
Installing React-cxxreact (0.63.0)
Installing React-jsi (0.63.0)
Installing React-jsiexecutor (0.63.0)
Installing React-jsinspector (0.63.0)
Installing ReactCommon (0.63.0)
Installing ReactNativeAutogrowTextinput (5.3.0)
Installing SDWebImage (5.8.3)
Installing SDWebImageWebPCoder (0.2.5)
Installing Yoga (1.14.0)
Installing boost-for-react-native (1.63.0)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
[!] /bin/bash -c 
set -e
#!/bin/bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -e

PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}"
CURRENT_ARCH="${CURRENT_ARCH}"

**Comment by ccvlad** [comment]
Hi, @wujianyy 
What the error message? You've pasted the install log above

**Comment by wujianyy** [comment]
wujian@tests-MacBook-Pro connectycube-reactnative-samples % cd RNChat 
wujian@tests-MacBook-Pro RNChat % ls
App.js                  __tests__               assets                  config.json             ios                     node_modules            package.json            yarn.lock
README.md               android                 babel.config.js         index.js                metro.config.js         package-lock.json       src
wujian@tests-MacBook-Pro RNChat % npm install

> ConnectyCubeChatCodeSample@1.0.1 postinstall
> npx jetify && cd ios && pod install

Jetifier found 1138 file(s) to forward-jetify. Using 8 workers...
Auto-linking React Native modules for target `RNChat`: RNCAsyncStorage, RNCPushNotificationIOS, RNDeviceInfo, RNFastImage, RNGestureHandler, RNImageCropPicker, RNReanimated, RNScreens, RNVectorIcons, and ReactNativeAutogrowTextinput
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.63.0)
Installing FBReactNativeSpec (0.63.0)
Installing Folly (2020.01.13.00)
Installing QBImagePickerController (3.4.0)
Installing RCTRequired (0.63.0)
Installing RCTTypeSafety (0.63.0)
Installing RNCAsyncStorage (1.6.1)
Installing RNCPushNotificationIOS (1.0.5)
Installing RNDeviceInfo (5.5.1)
Installing RNFastImage (7.0.2)
Installing RNGestureHandler (1.5.2)
Installing RNImageCropPicker (0.27.0)
Installing RNReanimated (1.4.0)
Installing RNScreens (2.0.0-alpha.22)
Installing RNVectorIcons (6.6.0)
Installing RSKImageCropper (2.2.3)
Installing React (0.63.0)
Installing React-Core (0.63.0)
Installing React-CoreModules (0.63.0)
Installing React-RCTActionSheet (0.63.0)
Installing React-RCTAnimation (0.63.0)
Installing React-RCTBlob (0.63.0)
Installing React-RCTImage (0.63.0)
Installing React-RCTLinking (0.63.0)
Installing React-RCTNetwork (0.63.0)
Installing React-RCTSettings (0.63.0)
Installing React-RCTText (0.63.0)
Installing React-RCTVibration (0.63.0)
Installing React-callinvoker (0.63.0)
Installing React-cxxreact (0.63.0)
Installing React-jsi (0.63.0)
Installing React-jsiexecutor (0.63.0)
Installing React-jsinspector (0.63.0)
Installing ReactCommon (0.63.0)
Installing ReactNativeAutogrowTextinput (5.3.0)
Installing SDWebImage (5.8.3)
Installing SDWebImageWebPCoder (0.2.5)
Installing Yoga (1.14.0)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
[!] /bin/bash -c 
set -e
#!/bin/bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -e

PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}"
CURRENT_ARCH="${CURRENT_ARCH}"

if [ -z "$CURRENT_ARCH" ] || [ "$CURRENT_ARCH" == "undefined_arch" ]; then
    # Xcode 10 beta sets CURRENT_ARCH to "undefined_arch", this leads to incorrect linker arg.
    # it's better to rely on platform name as fallback because architecture differs between simulator and device

    if [[ "$PLATFORM_NAME" == *"simulator"* ]]; then
        CURRENT_ARCH="x86_64"
    else
        CURRENT_ARCH="armv7"
    fi
fi

export CC="$(xcrun -find -sdk $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)"
export CXX="$CC"

# Remove automake symlink if it exists
if [ -h "test-driver" ]; then
    rm test-driver
fi

./configure --host arm-apple-darwin

# Fix build for tvOS
cat << EOF >> src/config.h

/* Add in so we have Apple Target Conditionals */
#ifdef __APPLE__
#include <TargetConditionals.h>
#include <Availability.h>
#endif

/* Special configuration for AppleTVOS */
#if TARGET_OS_TV
#undef HAVE_SYSCALL_H
#undef HAVE_SYS_SYSCALL_H
#undef OS_MACOSX
#endif

/* Special configuration for ucontext */
#undef HAVE_UCONTEXT_H
#undef PC_FROM_UCONTEXT
#if defined(__x86_64__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__rip
#elif defined(__i386__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip
#endif
EOF

# Prepare exported header include
EXPORTED_INCLUDE_DIR="exported/glog"
mkdir -p exported/glog
cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-apple-darwin-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking for arm-apple-darwin-gcc...  -arch armv7 -isysroot 
checking whether the C compiler works... no
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Users/wujian/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-40a13/missing: Unknown `--is-lightweight' option
Try `/Users/wujian/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-40a13/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/Users/wujian/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-40a13':
configure: error: C compiler cannot create executables
See `config.log' for more details

npm ERR! code 1
npm ERR! path /Users/wujian/Documents/code/github/connectycube/connectycube-reactnative-samples/RNChat
npm ERR! command failed
npm ERR! command sh -c npx jetify && cd ios && pod install

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wujian/.npm/_logs/2021-03-27T19_25_28_676Z-debug.log
wujian@tests-MacBook-Pro RNChat %

**Comment by wujianyy** [comment]
`wujian@tests-MacBook-Pro connectycube-reactnative-samples % cd RNChat 
wujian@tests-MacBook-Pro RNChat % ls
App.js                  __tests__               assets                  config.json             ios                     node_modules            package.json            yarn.lock
README.md               android                 babel.config.js         index.js                metro.config.js         package-lock.json       src
wujian@tests-MacBook-Pro RNChat % npm install

> ConnectyCubeChatCodeSample@1.0.1 postinstall
> npx jetify && cd ios && pod install

Jetifier found 1138 file(s) to forward-jetify. Using 8 workers...
Auto-linking React Native modules for target `RNChat`: RNCAsyncStorage, RNCPushNotificationIOS, RNDeviceInfo, RNFastImage, RNGestureHandler, RNImageCropPicker, RNReanimated, RNScreens, RNVectorIcons, and ReactNativeAutogrowTextinput
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.63.0)
Installing FBReactNativeSpec (0.63.0)
Installing Folly (2020.01.13.00)
Installing QBImagePickerController (3.4.0)
Installing RCTRequired (0.63.0)
Installing RCTTypeSafety (0.63.0)
Installing RNCAsyncStorage (1.6.1)
Installing RNCPushNotificationIOS (1.0.5)
Installing RNDeviceInfo (5.5.1)
Installing RNFastImage (7.0.2)
Installing RNGestureHandler (1.5.2)
Installing RNImageCropPicker (0.27.0)
Installing RNReanimated (1.4.0)
Installing RNScreens (2.0.0-alpha.22)
Installing RNVectorIcons (6.6.0)
Installing RSKImageCropper (2.2.3)
Installing React (0.63.0)
Installing React-Core (0.63.0)
Installing React-CoreModules (0.63.0)
Installing React-RCTActionSheet (0.63.0)
Installing React-RCTAnimation (0.63.0)
Installing React-RCTBlob (0.63.0)
Installing React-RCTImage (0.63.0)
Installing React-RCTLinking (0.63.0)
Installing React-RCTNetwork (0.63.0)
Installing React-RCTSettings (0.63.0)
Installing React-RCTText (0.63.0)
Installing React-RCTVibration (0.63.0)
Installing React-callinvoker (0.63.0)
Installing React-cxxreact (0.63.0)
Installing React-jsi (0.63.0)
Installing React-jsiexecutor (0.63.0)
Installing React-jsinspector (0.63.0)
Installing ReactCommon (0.63.0)
Installing ReactNativeAutogrowTextinput (5.3.0)
Installing SDWebImage (5.8.3)
Installing SDWebImageWebPCoder (0.2.5)
Installing Yoga (1.14.0)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
[!] /bin/bash -c 
set -e
#!/bin/bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -e

PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}"
CURRENT_ARCH="${CURRENT_ARCH}"

if [ -z "$CURRENT_ARCH" ] || [ "$CURRENT_ARCH" == "undefined_arch" ]; then
    # Xcode 10 beta sets CURRENT_ARCH to "undefined_arch", this leads to incorrect linker arg.
    # it's better to rely on platform name as fallback because architecture differs between simulator and device

    if [[ "$PLATFORM_NAME" == *"simulator"* ]]; then
        CURRENT_ARCH="x86_64"
    else
        CURRENT_ARCH="armv7"
    fi
fi

export CC="$(xcrun -find -sdk $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)"
export CXX="$CC"

# Remove automake symlink if it exists
if [ -h "test-driver" ]; then
    rm test-driver
fi

./configure --host arm-apple-darwin

# Fix build for tvOS
cat << EOF >> src/config.h

/* Add in so we have Apple Target Conditionals */
#ifdef __APPLE__
#include <TargetConditionals.h>
#include <Availability.h>
#endif

/* Special configuration for AppleTVOS */
#if TARGET_OS_TV
#undef HAVE_SYSCALL_H
#undef HAVE_SYS_SYSCALL_H
#undef OS_MACOSX
#endif

/* Special configuration for ucontext */
#undef HAVE_UCONTEXT_H
#undef PC_FROM_UCONTEXT
#if defined(__x86_64__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__rip
#elif defined(__i386__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip
#endif
EOF

# Prepare exported header include
EXPORTED_INCLUDE_DIR="exported/glog"
mkdir -p exported/glog
cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-apple-darwin-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking for arm-apple-darwin-gcc...  -arch armv7 -isysroot 
checking whether the C compiler works... no
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Users/wujian/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-40a13/missing: Unknown `--is-lightweight' option
Try `/Users/wujian/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-40a13/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/Users/wujian/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-40a13':
configure: error: C compiler cannot create executables
See `config.log' for more details

npm ERR! code 1
npm ERR! path /Users/wujian/Documents/code/github/connectycube/connectycube-reactnative-samples/RNChat
npm ERR! command failed
npm ERR! command sh -c npx jetify && cd ios && pod install

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wujian/.npm/_logs/2021-03-27T19_25_28_676Z-debug.log
wujian@tests-MacBook-Pro RNChat % `

**Comment by wujianyy** [comment]
wujian@tests-MacBook-Pro RNChat % npm install

> ConnectyCubeChatCodeSample@1.0.1 postinstall
> npx jetify && cd ios && pod install

Jetifier found 1138 file(s) to forward-jetify. Using 8 workers...
Auto-linking React Native modules for target `RNChat`: RNCAsyncStorage, RNCPushNotificationIOS, RNDeviceInfo, RNFastImage, RNGestureHandler, RNImageCropPicker, RNReanimated, RNScreens, RNVectorIcons, and ReactNativeAutogrowTextinput
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.63.0)
Installing FBReactNativeSpec (0.63.0)
Installing Folly (2020.01.13.00)
Installing QBImagePickerController (3.4.0)
Installing RCTRequired (0.63.0)
Installing RCTTypeSafety (0.63.0)
Installing RNCAsyncStorage (1.6.1)
Installing RNCPushNotificationIOS (1.0.5)
Installing RNDeviceInfo (5.5.1)
Installing RNFastImage (7.0.2)
Installing RNGestureHandler (1.5.2)
Installing RNImageCropPicker (0.27.0)
Installing RNReanimated (1.4.0)
Installing RNScreens (2.0.0-alpha.22)
Installing RNVectorIcons (6.6.0)
Installing RSKImageCropper (2.2.3)
Installing React (0.63.0)
Installing React-Core (0.63.0)
Installing React-CoreModules (0.63.0)
Installing React-RCTActionSheet (0.63.0)
Installing React-RCTAnimation (0.63.0)
Installing React-RCTBlob (0.63.0)
Installing React-RCTImage (0.63.0)
Installing React-RCTLinking (0.63.0)
Installing React-RCTNetwork (0.63.0)
Installing React-RCTSettings (0.63.0)
Installing React-RCTText (0.63.0)
Installing React-RCTVibration (0.63.0)
Installing React-callinvoker (0.63.0)
Installing React-cxxreact (0.63.0)
Installing React-jsi (0.63.0)
Installing React-jsiexecutor (0.63.0)
Installing React-jsinspector (0.63.0)
Installing ReactCommon (0.63.0)
Installing ReactNativeAutogrowTextinput (5.3.0)
Installing SDWebImage (5.8.3)
Installing SDWebImageWebPCoder (0.2.5)
Installing Yoga (1.14.0)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
[!] /bin/bash -c 
set -e
```
#!/bin/bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
```

set -e

PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}"
CURRENT_ARCH="${CURRENT_ARCH}"

if [ -z "$CURRENT_ARCH" ] || [ "$CURRENT_ARCH" == "undefined_arch" ]; then
    # Xcode 10 beta sets CURRENT_ARCH to "undefined_arch", this leads to incorrect linker arg.
    # it's better to rely on platform name as fallback because architecture differs between simulator and device

    if [[ "$PLATFORM_NAME" == *"simulator"* ]]; then
        CURRENT_ARCH="x86_64"
    else
        CURRENT_ARCH="armv7"
    fi
fi

export CC="$(xcrun -find -sdk $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)"
export CXX="$CC"

```
# Remove automake symlink if it exists
if [ -h "test-driver" ]; then
    rm test-driver
fi
```

```
./configure --host arm-apple-darwin

# Fix build for tvOS
cat << EOF >> src/config.h
```

```
/* Add in so we have Apple Target Conditionals */
#ifdef __APPLE__
#include <TargetConditionals.h>
#include <Availability.h>
#endif
```

```
/* Special configuration for AppleTVOS */
#if TARGET_OS_TV
#undef HAVE_SYSCALL_H
#undef HAVE_SYS_SYSCALL_H
#undef OS_MACOSX
#endif
```

```
/* Special configuration for ucontext */
#undef HAVE_UCONTEXT_H
#undef PC_FROM_UCONTEXT
#if defined(__x86_64__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__rip
#elif defined(__i386__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip
#endif
EOF
```

`# Prepare exported header include`
EXPORTED_INCLUDE_DIR="exported/glog"
mkdir -p exported/glog
cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-apple-darwin-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking for arm-apple-darwin-gcc...  -arch armv7 -isysroot 
checking whether the C compiler works... no
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Users/wujian/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-40a13/missing: Unknown `--is-lightweight' option
Try `/Users/wujian/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-40a13/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/Users/wujian/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-40a13':
configure: error: C compiler cannot create executables
See `config.log' for more details

npm ERR! code 1
npm ERR! path /Users/wujian/Documents/code/github/connectycube/connectycube-reactnative-samples/RNChat
npm ERR! command failed
npm ERR! command sh -c npx jetify && cd ios && pod install

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wujian/.npm/_logs/2021-03-27T19_25_28_676Z-debug.log

**Comment by ccvlad** [comment]
You should install/configure dependencies for your environment following the React Native guide - https://reactnative.dev/docs/0.63/environment-setup#installing-dependencies

The script can't run the `CommandLineTools` to finish `... cd ios && pod install` that is called from `npm run postinstall` script
