### ISSUE TITLE
I can receive push notifications in sample app but couldn't receive in my app

### ISSUE THREAD

**Issue by YoungDu** [ConnectyCube/connectycube-reactnative-samples#22]
I can receive push notifications in sample app but couldn't receive in my app,

my app is using react-native-firebase to handle notifications while sample app is using react-native-push-notification, I noticed that the Channel is GCM not FCM, will ConnectyCube support FCM for the push notifications and how to configure that?

**Comment by ccvlad** [comment]
Yes, we support FMC

Follow [this guide](https://developers.connectycube.com/android/push-notifications?id=configure-firebase-project-and-api-key) and then [use firebase guide](https://rnfirebase.io/docs/v4.3.x/notifications/receiving-notifications)

**Comment by YoungDu** [comment]
> Yes, we support FMC
> 
> Follow [this guide](https://developers.connectycube.com/android/push-notifications?id=configure-firebase-project-and-api-key) and then [use firebase guide](https://rnfirebase.io/docs/v4.3.x/notifications/receiving-notifications)

But this guide is for Android SDK and I'm using connectycube-react-native library fo

**Comment by ccvlad** [comment]
Just use "Configure Firebase project and API key" to prepare your admin panel and then follow react native firebase guide (link react-native-firebase with iOS/Android project and configure cloud messaging)

**Comment by Eramirez06** [comment]
you really should add documentation how to property implement this in React Native

**Comment by ccvlad** [comment]
Yes, we will updated the _React Native - Push Notifications_ section in our docs.

**Comment by DaveLomber** [comment]
In a case for further reference - we prepared a complete guide on how to integrate push notifications in React Native

 
https://developers.connectycube.com/reactnative/push-notifications
