### ISSUE TITLE
How do we create a "apns-push-type": "background" notification for IOS?

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#220]
I would like to send a header of "apns-push-type": "background".

As the apple documentation says you must send this header to make the notification a background notification so that the app can process the notification in the background. using the `application:didReceiveRemoteNotification:fetchCompletionHandler:` method.

Here is the documentation that describes this:
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns/

And here:
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app?preferredLanguage=occ

**Comment by DaveLomber** [comment]
@stephanoparaskeva there is no such a capability as for now
will add it to the roadmap 
Will let you know

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
