### ISSUE TITLE
Call the app when the phone is locked

### ISSUE THREAD

**Issue by dozsolti** [ConnectyCube/connectycube-reactnative-samples#223]
Hi,

How can I create a skype like screen when someone calls the app and that is closed and the phone is locked?
Demo: https://www.youtube.com/watch?v=vZBwifiOCEI

I know I have to use CallKeep, but that's not clear enough.

A [sample](https://github.com/ConnectyCube/connectycube-reactnative-samples#have-an-issue) will be really helpful

**Comment by DaveLomber** [comment]
A good starting point is https://developers.connectycube.com/reactnative/videocalling?id=receive-a-call-in-background

Basically you ned to integrate CallKit & VOIP pushes for iOS.

For Android - you cam omit it and use standard pushes

**Comment by DaveLomber** [comment]
Basically we have WIP MR https://github.com/ConnectyCube/connectycube-reactnative-samples/pull/200

**Comment by dozsolti** [comment]
I have implemented that part, but I don't know how to show a custom component over the lock screen

**Comment by DaveLomber** [comment]
which platform?

**Comment by dozsolti** [comment]
For now just android, but in the future I'm planning iOS too

**Comment by DaveLomber** [comment]
ok, for this we need to develop a custom Activity and show it from Push plugin

**Comment by dozsolti** [comment]
- Where do I create my custom Activity? in my android folder or one of the modules?
- How do I connect it with my react native code, passing variables and callbacks ?
- How do I show it from Push plugin?

**Comment by DaveLomber** [comment]
An updated video chat code sample with CallKit support is implemented

- code sample https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat
- blog post https://connectycube.com/2022/11/08/react-native-video-chat-code-sample-with-call-kit-support/
- documentation https://developers.connectycube.com/reactnative/videocalling?id=callkit
