### ISSUE TITLE
onNotification method get called in background but notification not coming in notification list

### ISSUE THREAD

**Issue by imsaurabhdixit** [ConnectyCube/connectycube-reactnative-samples#224]
Hi team,
In my case notification is coming from connectycube and even my onNotificaiton method get fire when the app is in background but notification didn't popup and not coming in notification list.
This is what i am getting in onNotification:
{
data:
badge: "1"
dialog_id: "60574552ca8bf468829098f5"
message: "You have 4 new messages"
user_id: "3791768"
proto: Object
finish: ƒ finish()
foreground: false
id: "-414371205"
userInteraction: false
}

I am think the notification data is wrong and due to which notification not get popup, because when i am using this api "https://fcm.googleapis.com/fcm/send" notification get popup in my application .

**Comment by banshiAnton** [comment]
Please, find solution in this issue
https://github.com/ConnectyCube/connectycube-reactnative-samples/issues/206
