### ISSUE TITLE
How we can invoke our app when we receive incoming call notification for background and quit state?

### ISSUE THREAD

**Issue by GuleriaAshish** [ConnectyCube/connectycube-reactnative-samples#227]
I am using the connectycube sdk for implementing the video call functionality in my app. It is working fine in my app and i am able to connect users through video call.

But there is one problem that i am facing right now. I am using the push notifications for alerting the user at receivers end. In foreground whenever a video call notification arrives we navigate the user to video call screen automatically where they can accept or reject that incoming call and it is working really fine.

The problem is with the background and Quit state incoming call notification. I want to open my app automatically on receiving incoming call notifications. So how can we achieve this thing?

Do you guys provides such functionality like we can see in whatsApp and other video calling apps as they automatically invoke the background and quit state apps.

We are about to finish our project but due to this issue we can't deploy our app. So please suggest some solutions for it, that will be very helpfull.

Versions that we are using :
React Native: 0.63.2
Connectycube sdk: 3.7.2

**Comment by GuleriaAshish** [comment]
@ccvlad, Please delete #225 and #226. It was posted by mistake

**Comment by DaveLomber** [comment]
Please refer to https://developers.connectycube.com/reactnative/videocalling?id=receive-a-call-in-background
