### ISSUE TITLE
Live messages update

### ISSUE THREAD

**Issue by syedmudaseer** [ConnectyCube/connectycube-reactnative-samples#230]
messages are not appearing as soon as the message is sent from another end. i have to go back and come back to see the chat screen to get messages

**Comment by DaveLomber** [comment]
Hi @syedmudaseer 
you mean at receiver's side the received message does not appear in chat screen util you close it and re-open again?

**Comment by syedmudaseer** [comment]
Hi@DaveLomber 
yes exactly.

**Comment by DaveLomber** [comment]
@syedmudaseer is it about chat code sample or this issue appears in you're own app?

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
