### ISSUE TITLE
CB SERVERS DOWN

### ISSUE THREAD

**Issue by CMLCNL** [ConnectyCube/connectycube-reactnative-samples#231]
Currently, our application in appstore and playstore does not open. Such an error arose after you made it to the servers. Close to 10 thousand can not enter now. So urgent.

```
Object {
  "code": 422,
  "detail": Object {
    "base": Array [
      "The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.",
    ],
  },
  "message": Object {
    "errors": Object {
      "base": Array [
        "The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.",
      ],
    },
  },
  "status": "error",
}
```

**Comment by DaveLomber** [comment]
Thank you for reporting the issue

We are investigating the root cause 

Will update here with more info

**Comment by CMLCNL** [comment]
I assure you it needs to be resolved very urgently. We log in with Firebase phone verification.
Our users are waiting for you. It is very urgent. @DaveLomber

**Comment by DaveLomber** [comment]
The root cause is identified

The team is working on a patch

More updates to come soon

**Comment by DaveLomber** [comment]
@CMLCNL we have deployed the patch 
Could you please check at your side and let us know whether the issue is resolved

**Comment by CMLCNL** [comment]
Yes @DaveLomber everything is fine for now. Thank you very much.

**Comment by CMLCNL** [comment]
@DaveLomber 
Some of the problems we detected.
The list of notifications sent in the -ConnectyCube admin panel does not work.
-There is a problem with the voip notification.
-We get complaints from our users. About not starting a conversation. During a voice or video call.

**Comment by DaveLomber** [comment]
@CMLCNL could you please provide more info if possible re 2nd and 3rd cases

**Comment by CMLCNL** [comment]
We cannot send voip call notifications.

Some users said that the voip notification came, but they said they could not have a healthy conversation.

**Comment by CMLCNL** [comment]
ERROR SEND VOIP: 

`{"code": 422, "detail": {"notification_type": ["in validation failed on notification_type"]}, "message": {"errors": {"notification_type": [Array]}}, "status": "error"}`

hey Dave please help us. 
```
const payload = JSON.stringify({
                                    callerName,
                                    uuid: session.ID,
                                    handle,
                                    hasVideo: "0",
                                    ios_badge: 0,
                                    ios_sound: "teleconn.mp3",
                                    ios_voip: 1
                                });

                                console.log(payload, "payload");

                                const pushParameters = {
                                    notification_type: "apns_voip",
                                    user: { ids: [profile.ccId] }, // recipients.
                                    environment: __DEV__ ? 'development' : 'production',
                                    message: TeleconnChat.pushnotifications.base64Encode(payload)
                                };

```

**Comment by CMLCNL** [comment]
We used to write apns_voip in the notification type field before, but I think the change has been made now. Will it be enough to just write push?

**Comment by DaveLomber** [comment]
the 'push' is a valid one and should be used here

**Comment by CMLCNL** [comment]
There was no such thing before and now our application in playstore and appstore is exploding.

**Comment by CMLCNL** [comment]
You should definitely remove the validation. The right choice. thousands of users are waiting for you. We will be working with Connectcube at an enterprise level in the near future. We are on the verge of a big investment. Please remove validation.

**Comment by DaveLomber** [comment]
@CMLCNL removing it. Will deploy the change soon

**Comment by CMLCNL** [comment]
Our application is not working for 2 days. We had great difficulties. We may have a small number of users, but this is important for our investment. @DaveLomber thank you for your interest.

**Comment by CMLCNL** [comment]
@DaveLomber 
Voip notification never came other phone.

`SEND VOIP [{"event": {"_id": "60957b6437dd46003353101d", "active": true, "created_at": "2021-05-07T17:39:48Z", "date": null, "end_date": null, "environment": "development", "event_type": "one_shot", "id": 9789, "kind": "API", "message": "eyJjYWxsZXJOYW1lIjoiQ2VtaWwgQ0FOTEkiLCJ1dWlkIjoiMmZiZjk0ZGEtYTUzOS00NjA0LThjYmEtNDU1YzMyZmRlZjExIiwiaGFuZGxlIjoiMTIyOTIxMyIsImhhc1ZpZGVvIjoiMCIsImlvc19iYWRnZSI6MCwiaW9zX3NvdW5kIjoidGVsZWNvbm4ubXAzIiwiaW9zX3ZvaXAiOjF9", "name": null, "notification_channel": [Object], "period": null, "tag_query": null, "updated_at": "2021-05-07T17:39:48Z", "user_id": 1229213}}, {"event": {"_id": "60957b6437dd46003353101e", "active": true, "created_at": "2021-05-07T17:39:48Z", "date": null, "end_date": null, "environment": "production", "event_type": "one_shot", "id": 9790, "kind": "API", "message": "eyJjYWxsZXJOYW1lIjoiQ2VtaWwgQ0FOTEkiLCJ1dWlkIjoiMmZiZjk0ZGEtYTUzOS00NjA0LThjYmEtNDU1YzMyZmRlZjExIiwiaGFuZGxlIjoiMTIyOTIxMyIsImhhc1ZpZGVvIjoiMCIsImlvc19iYWRnZSI6MCwiaW9zX3NvdW5kIjoidGVsZWNvbm4ubXAzIiwiaW9zX3ZvaXAiOjF9", "name": null, "notification_channel": [Object], "period": null, "tag_query": null, "updated_at": "2021-05-07T17:39:48Z", "user_id": 1229213}}]`

**Comment by DaveLomber** [comment]
@CMLCNL checking this now

**Comment by CMLCNL** [comment]
Is there any improvement?

**Comment by DaveLomber** [comment]
We identified the issue with subscription override where a user create both apns and apns_voip for same device id

The fix is on the way, should be deployed during next h

We continue checking the rest push functionality

More updates to come

**Comment by DaveLomber** [comment]
@CMLCNL the root cause of VOIP push notifications failure has been identified 

A patch was deployed and tested, It all should work well now

Please double check at your side

**Comment by CMLCNL** [comment]
Despite all my attempts. Payload is always null.

```
const payload = JSON.stringify({
                                    callerName,
                                    uuid: session.ID,
                                    handle,
                                    hasVideo: "0",
                                    ios_badge: 0,
                                    ios_sound: "x.mp3",
                                    ios_voip: 1
                                });

                                console.log(payload, "payload");

                                const pushParameters = {
                                    notification_type: "apns_voip",
                                    user: { ids: [profile.ccId] }, // recipients.
                                    environment: __DEV__ ? 'development' : 'production',
                                    message: ConnectyCube.pushnotifications.base64Encode(payload)
                                };
```

```
- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
  
 NSObject* aps = payload.dictionaryPayload[@"aps"];
```
Payload is null.

Look, I repeat. Everything was working before the server update. The application explodes because the payload is not coming.

**Comment by DaveLomber** [comment]
The initial issue was related to voip pushes do not come at all.
It's fixed now, the voip pushes go well now. 

Then

Are you expecting all voip push params to come as a part of 'aps'? 

Cause it comes now at top level, not inside 'aps'.  

Is this your current issue?

**Comment by CMLCNL** [comment]
Yes, we expected it to be the same as before. Because now users cannot use the application.

**Comment by CMLCNL** [comment]
How does shipping at the highest level benefit us? If it is useful, I will update the application in AppStore.

**Comment by DaveLomber** [comment]
Not a benefit 

Previously it was added to 'aps' by mistake cause 'aps' secrion is more for normal pushes - for some predefined params only

Anyway, will add it inside aps. Will update you once done

**Comment by DaveLomber** [comment]
@CMLCNL it should come inside aps now
Could you please check and let us know

**Comment by CMLCNL** [comment]
hey @DaveLomber You changed the structure completely. You changed the structure completely. It was not like that before. It was payload-> aps-> alert.

```
NSObject* aps = payload.dictionaryPayload[@"aps"];
 
 NSString* alert = [aps valueForKey:@"alert"];
 
 NSLog(@"%@", alert);
 
 NSData *webData = [alert dataUsingEncoding:NSUTF8StringEncoding];
 NSError *error;
 NSDictionary *jsonDic = [NSJSONSerialization JSONObjectWithData:webData options:NSJSONReadingMutableContainers error:&error];
 
 
 NSLog(@"%@", jsonDic);
 
 
 NSString *uuid = [jsonDic valueForKey:@"uuid"];
 NSString *callerName = [jsonDic valueForKey:@"callerName"];
 NSString *handle = [jsonDic valueForKey:@"handle"];
 
 
 NSLog(@"%@ %@ %@", handle,callerName,uuid);
```

Actually this is much better than what you do. I think you just put it all in payload.

For example: payload.dictionaryPayload [@ "callerName"];

Let it come at the highest level. Let me assign the AppStroe update. Because I used to have to serialize the data.

**Comment by CMLCNL** [comment]
Get data at the highest level. I will update the AppStore.

```
- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
  
  NSString *uuid = payload.dictionaryPayload[@"uuid"];
  NSString *callerName = payload.dictionaryPayload[@"callerName"];
  NSString *handle = payload.dictionaryPayload[@"handle"];
 
 NSLog(@"%@ %@ %@", handle,callerName,uuid);
```

**Comment by DaveLomber** [comment]
@CMLCNL please check now

we send it now both at highest level and inside aps.alert as string

**Comment by CMLCNL** [comment]
Congratulations. Thank you for your interest. Now its working voip notification.

**Comment by DaveLomber** [comment]
Sweet
much appreciated for your patience
