### ISSUE TITLE
Cannot send messages in groups

### ISSUE THREAD

**Issue by dozsolti** [ConnectyCube/connectycube-reactnative-samples#232]
Hi,

I am working on an app which already has dialogs between 2 users and works just fine. Now when I tried to integrated groups chats the messages aren't sending.

No errors, no warnings, nothing when I call the `send` function, but also nothing when I check in the dashboard the group or when I retrieve the dialog by id.

This is my send function, the property names are a bit different, because I have custom classes (ex. from dialog._id -> dialog.id). But the values are correct.

	async Send(dialog, message, connectyCubeUser, attachmentID = null) {
		const body = message.trim()
		const sentDate = Math.floor(Date.now() / 1000)

		const targetID = dialog.isGroup ? dialog.id : dialog.occupants_ids.find(
			elem => elem !== connectyCubeUser.id
		)

		let msg = {
			id: null,
			type: dialog.xmpp_type,
			body,
			extension: {
				save_to_history: 1,
				dialog_id: dialog.id,
				sender_id: connectyCubeUser.id,
				date_sent: sentDate,
				...(attachmentID ? { attachmentID } : {}),
			},
			markable: 1,
		}

		msg.id = await ConnectyCube.chat.send(targetID, msg)
		return msg
	}

Also I tried with the latest version (v3.9.1) (first tried with v3.7.8) but nothing

**Comment by DaveLomber** [comment]
@dozsolti please console log the 'msg' and 'targetID' vars

Also, please enable logs like here https://developers.connectycube.com/js/?id=configuration
and post the logs when you send a message

**Comment by dozsolti** [comment]
![image](https://user-images.githubusercontent.com/17215747/117256669-a2190780-ae53-11eb-94a8-9e8fdda2dda2.png)

**Comment by DaveLomber** [comment]
@dozsolti ok this is fine

then please share the logs

**Comment by dozsolti** [comment]
![image](https://user-images.githubusercontent.com/17215747/117257286-6468ae80-ae54-11eb-92d6-a1bd4f01b561.png)

**Comment by DaveLomber** [comment]
@dozsolti so it says no such room 

please show how you create a room before sending a message

**Comment by dozsolti** [comment]
I've used the new dialog popup from the dashboard, entered some name and the occupants ids and that's it

**Comment by dozsolti** [comment]
> @dozsolti so it says no such room
> 
> please show how you create a room before sending a message

It was created successfully and it exists in the dashboard
![image](https://user-images.githubusercontent.com/17215747/117258576-c83fa700-ae55-11eb-93e0-83f9be9c9405.png)

**Comment by dozsolti** [comment]
Updates: This wasn't working in any groups, but started working in some... The one I send it still doesn't work.
One key difference is that looks like if was created through API it works, but from dashboard no

**Comment by DaveLomber** [comment]
@dozsolti could you try top create a new dialog  via Dashboard and let us know how it works with it?

**Comment by dozsolti** [comment]
@DaveLomber Ok it worked, I created a new one from Dashboard and I've was able to send a message. 

The old group is working the same

**Comment by DaveLomber** [comment]
@dozsolti ok great 

if you to fix any old chats, just send here a list of iDs

**Comment by dozsolti** [comment]
It's alright, it was only for testing purposes.

I just wonder what happend to it, so I can omit it in the future

**Comment by DaveLomber** [comment]
@dozsolti There was a maintenance window yesterday, 
probably you just created some dialogs during it so it leaded to this behaviour

**Comment by dozsolti** [comment]
Alright, thank you for help
