### ISSUE TITLE
Custom Identity provider errors

### ISSUE THREAD

**Issue by stevenblake-banntech** [ConnectyCube/connectycube-reactnative-samples#233]
We've been using the Custom Identity provider up until now and it's been working great. Today it seems like it has stopped working.

`const session = await ConnectyCube.createSession({ login: email, password: token });`

produces the following:

`{"code": 404, "info": {"errors": ["User not found"]}}`

We're not seeing any errors from our API (endpoint which the custom identity uses). As I said, everything has been working OK up until now so I don't think it's on our end although I will not rule it out. Has anything changed on your end? Or something not working quite right?

**Comment by iuliansafta** [comment]
Hi, it seems that we're experiencing the same issue. Up until the last maintenance 05.05.2021, everything worked well.
@stevenblake-banntech have you found any solution to this?

**Comment by stevenblake-banntech** [comment]
> Hi, it seems that we're experiencing the same issue. Up until the last maintenance 05.05.2021, everything worked well.
> @stevenblake-banntech have you found any solution to this?

Unfortunately not.

**Comment by DaveLomber** [comment]
We are on the way of investigation.
The root cause is identified, the patch is on the way

**Comment by DaveLomber** [comment]
Guys, could you please try again and let us know how it all works now

**Comment by stevenblake-banntech** [comment]
Seems to be working for us now.

**Comment by iuliansafta** [comment]
It's working for us as well. Thanks!
