### ISSUE TITLE
node_modules/react-native-webrtc/ios/WebRTC.framework/WebRTC' does not contain bitcode

### ISSUE THREAD

**Issue by silverfh** [ConnectyCube/connectycube-reactnative-samples#234]
Hi,

I am facing an issue while react-native iOS Archive, works fine in dev mode though.

node_modules/react-native-webrtc/ios/WebRTC.framework/WebRTC' does not contain bitcode

I have tried to run "node_modules/react-native-webrtc/tools/downloadBitcode.sh"

but it not working.. it fails with invalid archive
if I try to browse the url directly it give me Forbidden error

https://dl.bintray.com/webrtc-builds/webrtc-builds/M84-1/WebRTC.tar.xz

my package details are as following

"react": "16.11.0",
"react-native": "0.62.0",
"react-native-connectycube": "^3.9.1",

Your help is highly appreciated..

Best Regards
Faheem

**Comment by DaveLomber** [comment]
@ccvlad could you please assist here?

**Comment by ccvlad** [comment]
Hi @silverfh 

We will release new version soon with react-native-webrtc 1.89.1 (downloads bitcode from GitHub repo). But I already can make prerelease to solve the issue.

Will update you here

**Comment by ccvlad** [comment]
@silverfh 
Check the [react-native-connectycube v.3.10.0-alpha.2](https://www.npmjs.com/package/react-native-connectycube/v/3.10.0-alpha.2) ([release notes](https://github.com/ConnectyCube/connectycube-js-sdk-releases/releases/tag/3.10.0-alpha))

**Comment by silverfh** [comment]
ok... 

what I did to make it work for now is disabling bitcode in Xcode... so I was able to make the archive and show something to client... coz its been delayed a lot and client is super duper unhappy...

anyway... we just started to face a new thing now... seems like the api's are changed.. and we have to use different functionality to log in and perform actions...

and so far the connecty documentation isnt updated yet... its like em at a closed road ... please provide some documentation to make it work for now..

I would like to not update anything at the moment... first I have to show something working to my client.. and then I'll have some time to update as per your suggestion above..

Please let me know if there is a working ground in this scenario !

coz I am integrating connecty to an existing application.. which is already very intense and have lots of functionality, so updating takes lots of time for me, it will involve lots of testing as well..

thanks

**Comment by DaveLomber** [comment]
Please provide some hints what exactly has changed recently, so we can check it

**Comment by silverfh** [comment]
one example...
I cant create a new user using the /users api anymore...
its telling me to use email w/0 login or something.... this started to happen suddenly 2 days back...

POST https://api.connectycube.com/users
>>>  reff: https://developers.connectycube.com/server/users

**Comment by DaveLomber** [comment]
<img width="773" alt="Screenshot 2021-05-08 at 15 57 40" src="https://user-images.githubusercontent.com/39332586/117540088-20250c00-b016-11eb-9cd5-b2362a7148ad.png">

Can do it w/o any issues

Could you please check again 
If still not working - provide a complete error output

**Comment by silverfh** [comment]
![Screenshot 2021-05-08 at 6 17 22 PM](https://user-images.githubusercontent.com/83134/117540761-1efdda00-b02a-11eb-9d6c-02fee1084373.png)

**code example..**
`
ConnectyCube.createSession()
    .then((session) => {
        this.setState({ loading: false, connectySession: session }, () => createNewUserAtCC(session))
    })
    .catch((error) => {
        console.log("ERROR: ", error);
        this.setState({ loading: false })
        alert("Unable to establish New User Session!")
    });


/*************** * Register user to conecty server * **/
const createNewUserAtCC = async(connectySession) => {
        this.setState({ loading: "Registering Calling user..." })
        const method = 'post';
        let postData = {
            'user[login]': "totona@getnada.com",
            'user[email]': "totona@getnada.com",
            'user[password]': "test1234",
            'user[full_name]': "user full name here",
            token: "B39FD5DA6F6825F2B5E47E2A1F8D87FB2A0E",
        }

        const serviceUrl = "https://api.connectycube.com/users";

        const res = await fetch(serviceUrl, {
                method: method,
                headers: {
                    'Content-Type': 'application/json',
                    'CB-Token': postData.token,
                },
                redirect: 'follow',
                referrerPolicy: 'no-referrer', 
                body: JSON.stringify(postData),
            })
            .then(res => {
                return res.json().then(r => {
                    console.log(JSON.stringify(r, 0, 2));
                    return r;
                });
            })
            .catch(err => {
                console.log("ERROR => ******** fetchApiData ********")
                console.log(serviceUrl);
                console.log(JSON.stringify(err, 0, 2));
                console.log("END ********************");
                alert("Unable to register Calling user");
                return false;
            })

        if (res.errors) {
            Alert.alert("Video Account Registration Error!", JSON.stringify(res.errors, 0, 2))
            return false;
        }
        return res;
    }
`

**Comment by meosieudang** [comment]
@silverfh , open Xcode -> Choose Build Settings -> choose tab "All" -> Build Options -> Enable Bicode -> u need to set No

**Comment by silverfh** [comment]
Hey...

I tried it.. but its giving me another error...

this is my session request response..

{
"application_id": *****, 
"created_at": "2021-05-10T12:51:30.558Z", 
"id": *******, 
"nonce": *******, 
"token": "1FF133B82AE441038DC91CDE9D06F1510565", 
"ts": 1620651088, 
"updated_at": "2021-05-10T12:51:30.558Z", 
"user_id": null
}

and this is when I try to create a user

{
  "errors": {
    "base": [
      "Required session does not exist"
    ]
  }
}


following is my request code
--------------
let postData = {
    user:{
        login: "email@mail.com",
        email: "email@mail.com",
        password: "test1234,
        full_name: "test user name,
        token: connectySession.token,
    }
}


const res = await fetch(serviceUrl, {
        method: method,
        headers: {
            'Content-Type': 'application/json',
            'CB-Token': postData.token,
        },
        redirect: 'follow', 
        referrerPolicy: 'no-referrer',
        body: JSON.stringify(postData),
    })

**Comment by silverfh** [comment]
Any updates guys ?

**Comment by silverfh** [comment]
got it resolved... 
the API call is changed.. now I have to register the user using ConnectyCube object..

you guys need to update the documentation and demo app as well..

**Comment by silverfh** [comment]
ok my bad found the tab for SDK V2 ...

but demo apps still needs updates..
