### ISSUE TITLE
Missing user's login

### ISSUE THREAD

**Issue by dozsolti** [ConnectyCube/connectycube-reactnative-samples#236]
Hi,

We facing issues on creating the users with API. The `login` property is missing!

![image](https://user-images.githubusercontent.com/17215747/117625883-2d113f00-b17f-11eb-9e78-1c69f2e2d9fb.png)

It used to work just fine, but around last week or so, it started creating users with no login, which is creating problems when the users logs in.

An user was created on `2021-05-04T09:05:23Z` and worked it, the next one on: `2021-05-07T07:15:47Z` doesn't.

The user is still getting created, with the correct full name and external id.

And this is how it's been configured in the dashboard:
![image](https://user-images.githubusercontent.com/17215747/117626963-5c747b80-b180-11eb-95f1-7be4be48e48c.png)

What is the problem?

**Comment by DaveLomber** [comment]
@dozsolti this should work now again 

If there is no 'login' mapping in response, then a default login will be created in format: 'custom_<uid>'

**Comment by dozsolti** [comment]
It creates it but, it failes at login 422
![image](https://user-images.githubusercontent.com/17215747/117655078-44602480-b19f-11eb-81f7-583a8ae9a090.png)

**Comment by dozsolti** [comment]
When I tried from the dashboard I got this:
![image](https://user-images.githubusercontent.com/17215747/117655142-5d68d580-b19f-11eb-9fac-d35aecef684f.png)
![image](https://user-images.githubusercontent.com/17215747/117655160-635eb680-b19f-11eb-8cf3-31aa2141dd93.png)


But I fixed by setting the `request params` to empty object and passes the test cip

**Comment by DaveLomber** [comment]
This is fixed as well now https://github.com/ConnectyCube/connectycube-reactnative-samples/issues/236#issuecomment-836601923 

Please let me know if you still face any issue

**Comment by dozsolti** [comment]
Yes, now it works.

Thank you!
