### ISSUE TITLE
API Changes

### ISSUE THREAD

**Issue by ganeshaskan** [ConnectyCube/connectycube-reactnative-samples#237]
Hi,

I am using the API URL ( https://api.connectycube.com/users/by_login)  to get user details. It is working fine until a day before. But right I am getting "User not found" error message. Please let me know is there any changes on API. How to resolve this issue.

Thanks

**Comment by DaveLomber** [comment]
@ganeshaskan could you please provide a log of request and response data

This will help us find a root cause 

Use this code snippet to get SDK logs https://developers.connectycube.com/reactnative/?id=configuration

**Comment by ganeshaskan** [comment]
Hi,

Here I attached the request and response as screenshot. It works previously but couple of days before only this login API its not working. In the screenshot login details I given is the valid one. But the response shows as "user not found". Kindly let me know is there any changes in API. 

Please give as input to fix this

![request](https://user-images.githubusercontent.com/29033386/117948809-1c9fc680-b32f-11eb-83e7-eb99cb50242f.png)
![response](https://user-images.githubusercontent.com/29033386/117948815-1e698a00-b32f-11eb-9329-d557cbb5ca72.png)

**Comment by DaveLomber** [comment]
Please let us know 2 things:
- your app id
- what value you pass in 'login' field

**Comment by banshiAnton** [comment]
HI @ganeshaskan maybe you have error in php
Please try to use
```php
'login='.$email;
```
or

```php
"login=$email"; // double quotes
```

**Comment by ganeshaskan** [comment]
Hi,

I tried both you mentioned format but still I am getting same "user not found" error. 

APP ID : 3496
login field I given teststudent100520211236@taylorrobinsonmusic.com

Thanks

**Comment by banshiAnton** [comment]
can you please show final builded request with url,query params,headers,body
maybe with curl-getinfo or other tools

**Comment by ganeshaskan** [comment]
Hi,

Below is the information I get when curl_getinfo used. 
![info](https://user-images.githubusercontent.com/29033386/117963280-ca19d680-b33d-11eb-9119-594934ce5e3f.png)

Tthanks

**Comment by banshiAnton** [comment]
try to use this
```php
curl_setopt($ch, CURLOPT_URL, 'https://api.connectycube.com/users/by_login?login='.$email);
```
later we deploy changes and you can use
```php
curl_setopt($ch, CURLOPT_POSTFIELDS, 'login='.$email);
```

**Comment by DaveLomber** [comment]
@ganeshaskan we have applied a patch
so it should work as before, please check

**Comment by ganeshaskan** [comment]
Hi,

Now by_login API is working fine. Thank you so much.

Please let us know is there any changes on the API (https://api.connectycube.com/chat/Message). This also worked previously but now not working. We are sending chat messages by using this API. chat_dialog_id, recipient_id and message parameters are sending properly. But chat not received. Below is the code we used works earlier.
Kindly let us know any changes on this API.

$arr = array("chat_dialog_id"=>$chat_dialog_id,"message"=>$message,"recipient_id"=>$recipient_id);
$json = json_encode($arr);
curl_setopt($ch, CURLOPT_URL, 'https://api.connectycube.com/chat/Message');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
//curl_setopt($ch, CURLOPT_POSTFIELDS, $json);
curl_setopt($ch, CURLOPT_POSTFIELDS, $json);
$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'CB-Token: '.$token;
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
$result_chat = curl_exec($ch);

Thanks

**Comment by DaveLomber** [comment]
@banshiAnton please check as well

**Comment by DaveLomber** [comment]
@ganeshaskan we have max:4000 validation for message field. What string you send?

**Comment by ganeshaskan** [comment]
Hi,

We sent chat message early having more number of characters. Please let me know why restrictions happens now.
Is Possible to increase message chars.

Thanks

**Comment by DaveLomber** [comment]
@ganeshaskan there must be some limit anyway at server side.
What max length are you sending?

**Comment by ganeshaskan** [comment]
Hi,

We are sending messages as html templates. So it should be more than 4000 chars. 
Previously all templates  looks good. But, due to char restriction message not received now.
How to overcome this. Kindly let me know

Thanks

**Comment by DaveLomber** [comment]
@ganeshaskan will 8K will be ok?

**Comment by ganeshaskan** [comment]
Hi,

Yes please change it and let me know. We will check

Thanks

**Comment by DaveLomber** [comment]
We set it to 8K please check

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
