### ISSUE TITLE
Video call freezing or disconnected when app goes to background

### ISSUE THREAD

**Issue by ankuret** [ConnectyCube/connectycube-reactnative-samples#239]
When app comes from background to foreground then video call freezing or disconnected.

**Comment by ccvlad** [comment]
It is OS limitation. Use [react-native-background-actions](https://github.com/jamesisaac/react-native-background-task) or other library to keep call activity in background. iOS will pause video in background, only audio will be active during background mode is active.

I suggest you to listen to [AppState](https://reactnative.dev/docs/appstate) and start/stop background activity if needed. Also good point to mute video while your application is not in foreground.
