### ISSUE TITLE
audio is not working in react native video chat

### ISSUE THREAD

**Issue by ksmkr** [ConnectyCube/connectycube-reactnative-samples#24]
I have used 'react-native-incall-manager' also but still my voice is not audible.

**Comment by ccvlad** [comment]
[react-native-incall-manager API](https://github.com/react-native-webrtc/react-native-incall-manager#api) - there are 2 methods to enable/disable the speakerphone:  setSpeakerphoneOn(flag: ?boolean), setForceSpeakerphoneOn(flag: ?boolean)
Did you mean this?

**Comment by ksmkr** [comment]
Thank you for your reply.

Yes I used this in fact in demo code setForceSpeakerphoneOn() is used. I used same like that but it is not working in my app.
I have set it on user connect with connectycube server

**Comment by ksmkr** [comment]
Hello Team,
When I used '<uses-permission android:name="android.permission.RECORD_AUDIO" />' this in manifest file. In my react native project it become audible.

But now it is catching sound of fan or moving device.and this noise is more than user voice.
Can you provide solution for this.

**Comment by ccvlad** [comment]
Could you explain? Did you use our sample (RNVideoChat)? Does this issue present there?

**Comment by ksmkr** [comment]
Yes this issue is present over there also.

**Comment by ccvlad** [comment]
Describe to us how to reproduce (steps to reproduce, model/os/version of devices which you use). We will check too.

**Comment by ksmkr** [comment]
In package.json,
"dependencies": { 
"@expo/vector-icons": "^10.0.3",
    "@react-native-community/async-storage": "^1.5.1",
    "@react-native-community/netinfo": "^4.1.5",
    "connectycube-reactnative": "^1.8.1",
    "firebase": "^6.3.3",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "native-base": "^2.13.5",
    "react": "16.9.0",
    "react-dom": "^16.8.6", 
 "connectycube-reactnative": "^1.8.1",
  "react-native-webrtc": "^1.69.1",
"react-native-incall-manager": "^3.2.6"
}

this versions I am using in my project and code is same as given in RNVideoChat.

**Comment by ccvlad** [comment]
Try to use last code of [RNVideoChat](https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat).

If nothing won't change, we will wait for _steps to reproduce_, also we need information about **models of devices**, **devices' OS** and **version of devices' OS** that you use.

**Comment by ksmkr** [comment]
This issue is appearing in RNVideoChat also,  I am facing this for android platform.IOS platform I haven't checked yet.

**Comment by ccvlad** [comment]
> If nothing won't change, we will wait for _steps to reproduce_, also we need information about **models of devices**, **devices' OS** and **version of devices' OS** that you use.

I’m going to close the issue cause no information. Please raise a separate issue in case of any other questions
