### ISSUE TITLE
dynamically fetch new users for video chat

### ISSUE THREAD

**Issue by rexcode** [ConnectyCube/connectycube-reactnative-samples#240]
in video chat sample - config file is used to store users data,  
is there a way to dynamically fetch any new user created via server api in the background, 
so the currently logged-in user call/chat list is auto refreshed and this user can chat/ video chat with them. 

Currently, if the newly created user detail is not hardcoded in config.js, that user when tried to call another user, the call will fail.

Please guide asap

**Comment by ccvlad** [comment]
It is possible. Use API calls to register new user and login by them. Get users...
- [sign-up](https://developers.connectycube.com/js/authentication-and-users?id=user-signup)
- [log-in](https://developers.connectycube.com/js/authentication-and-users?id=upgrade-session-token-user-login)
- [retrieve users](https://developers.connectycube.com/js/authentication-and-users?id=retrieve-users)

**Comment by rexcode** [comment]
Hi, thanks for your reply, will check it out.
Is it possible to automatically update users list, when a new user is created thru api or admin panel ?

**Comment by ccvlad** [comment]
Depends on what exactly you need. Usually we get users by situation.

- User can send a message about his/her registration via chat to others (e.g. use [ConnectyCube.chat.sendSystemMessage](https://developers.connectycube.com/js/messaging?id=system-messages) and some data to get on receiver's side)
- If user was created by super admin (via admin panel), you are also able to notify other users (read about a dialog type "broadcast" [here](https://developers.connectycube.com/js/messaging?id=dialogs))

**Comment by rexcode** [comment]
thanks for your quick reply,

I will check these out.

 in our app, all normal users can only call a specific user who has an admin tag assigned to it

Please clarify on 1 query - 
if a new user is created and he tries to call the specific admin, then
on the admin user (ie. call receiver) app crashes first,
so it means that the admin user needs to have this new user data to receive the call, correct ?

Please guide

**Comment by ccvlad** [comment]
Yes
You will receive call session in [onCallSession](https://developers.connectycube.com/js/videocalling?id=accept-a-call). Obtain `session.initiatorID` or `session.opponentsIDs` and [get users by IDs](https://developers.connectycube.com/js/authentication-and-users?id=retrieve-users-by-id) from server.
