### ISSUE TITLE
Video chat - TypeError when setting up onRemoteStreamListener 

### ISSUE THREAD

**Issue by daoma90** [ConnectyCube/connectycube-reactnative-samples#241]
I'm trying to set up the onRemoteStreamListener and I get a type error.

``TypeError: Cannot set property 'onRemoteStreamListener' of undefined``

![cctypeerror](https://user-images.githubusercontent.com/56395575/118613379-fc548980-b7be-11eb-9259-06b28a154731.png)

I'm currently just trying to console log the values from onRemoteStreamListener. The initListeners function is run in a useEffect with no dependencies. 

![CCproblem](https://user-images.githubusercontent.com/56395575/118612692-5274fd00-b7be-11eb-84e2-ebf8e88d0011.png)

The other video chat listeners are working. I can listen for calls, and I can listen to accepted calls. But when I add 
``ConnectyCube.videoChat.onRemoteStreamListener = onRemoteStreamListener;`` I get a crash.

If there is any more information I should add, please let me know.

**Comment by ccvlad** [comment]
Hi @daoma90 

You have a little mistake in your code. Please change `ConnectyCube.videoChat.onRemoteStreamListener` to `ConnectyCube.videochat.onRemoteStreamListener`. All letters must be in lower case.

**Comment by daoma90** [comment]
Oh god, now I feel like a dummy! :D

Thanks!
