### ISSUE TITLE
OnRejectListener and onSessionConnectionStateChangedListener do not work in ConnectyCube version 3

### ISSUE THREAD

**Issue by CMLCNL** [ConnectyCube/connectycube-reactnative-samples#243]
OnRejectListener and onSessionConnectionStateChangedListener do not work in ConnectyCube version 3. We are planning to migrate from version 1 to version 3, but there is such a problem. it is very important to us. We also get another error called setRemoteSessionDescription. Please review, we are looking forward to your feedback.

Version 3 is pretty fast and good actually if these issues are fixed we plan to switch to it immediately.

**Comment by ccvlad** [comment]
Hi @CMLCNL 
Please make sure that you use the [ConnectyCube.videochat.onRejectCallListener](https://developers.connectycube.com/js/videocalling?id=reject-a-call) as specified in our docs.

The SDK v2/3 doesn't have breaking changes in comparing with v1 for class `ConnectyCube.videochat` methods.
The main change between v1 and v2/3 is callbacks to get response from REST APIs were deprecated to use promises and async/await instead.

I will check RN SDK v.3.9.2 with the RNVideoChat sample and let you know.

Logs would be helpful to solve you issue! Could you send?

**Comment by CMLCNL** [comment]
Unfortunately, I reverted the project back to its original state. Version 1 statement. We've talked about this before. He said that other people had this problem.

**Comment by CMLCNL** [comment]
https://github.com/ConnectyCube/connectycube-js-sdk-releases/issues/10

**Comment by ccvlad** [comment]
Is it issue present between devices that work on react-native-connectycube? Could you specify details such as count of devices, OS platform (Android, iOS), which ConnectyCube SDKs (RN, JS, iOS, etc.)?

**Comment by CMLCNL** [comment]
These 2 functions did not work on both platforms. I tried different ios versions and tried different android 9 and 10. RN version 0.63 above.

I have been using connectycube for a long time.  If I say it doesn't work, it means I know something. I use everything the same, but when switching to version 3, these two functions are not triggered.

**Comment by ccvlad** [comment]
OK. As I understood you use only the react-native-connectycube SDK to make call...

I have upgraded our RNVideoChat sample to v.3.9.2, please check [here](https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/rn-video-chat-upgrade/RNVideoChat). All listeners are working there. Hope, it would be helpful.

I would ask you for logs or code snippets from your code to help if needed

**Comment by CMLCNL** [comment]
If there is an error that I will check and get back to you, I will get back to you with all the logs and important information. I am so thankful for your interest and interest.

**Comment by CMLCNL** [comment]
I congratulate you, you solved the problem in 3.7.5 in 3.9.2. Thank you so much. Could you please say something about this problem? @ccvlad  #242

**Comment by ccvlad** [comment]
I have answered to #242.
Please close the issue after you will migrate to v3 or ask if needed
