### ISSUE TITLE
Unable to login, missing 'user' object in session response

### ISSUE THREAD

**Issue by kkcy** [ConnectyCube/connectycube-reactnative-samples#246]
Hi there, our users couldn't login starting from today.
We're still using the old v1 SDK. Debugging it shows that when we run `createSession(userCredential)`, response only returned with 
```
Object {
  "application_id": 964,
  "created_at": "2021-06-10T04:13:36.015Z",
  "id": 324700901,
  "nonce": 1946,
  "token": "35FB547578B4D0544B2EF35735B14E0FD0F3",
  "ts": 1623298414,
  "updated_at": "2021-06-10T04:13:36.015Z",
  "user_id": null,
}
```
with user_id null, which i think is the reason why the user object is missing.
Usually it should be returned as
```
Object {
   ...,
   user_id: 1,
   user: {
      ...
   }
}
```

I'm sure there isn't any problem with our user credential though.

**Comment by DaveLomber** [comment]
@kkcy there was not any changes made today 

could you please show what you have inside userCredential ?

**Comment by banshiAnton** [comment]
Hi @kkcy  can you please provide sdk logs (request/response) for this request

**Comment by kkcy** [comment]
Hey guys, not sure what solves the problem, but we cleaned the node modules and reinstall works. Sorry for the trouble!
