### ISSUE TITLE
On session expiration callback not getting called

### ISSUE THREAD

**Issue by codepoetryindia** [ConnectyCube/connectycube-reactnative-samples#248]
init = () => ConnectyCube.init({
    appId: 4948,
    authKey: 'H2hUALR3s5wKnM7',
    authSecret: '************************',
},{ 
  on: {

    sessionExpired: (handleResponse, retry) => {
      console.log("call callback");
      handleResponse();
      // call handleResponse() if you do not want to process a session expiration,
      // so an error will be returned to origin request
      // handleResponse();

      ConnectyCube.createSession()
        .then(retry)
        .catch((error) => {});
    },
  },
  debug: { mode: 1 }
});

**Comment by ccvlad** [comment]
What will show `console.log(ConnectyCube.service.sdkInstance.config.on.sessionExpired)` after `ConnectyCube.init()`? Is the `console.log("call callback")` called?

Could you show your logs?

**Comment by codepoetryindia** [comment]
No, it's not getting called. after I destroy the session using the rest API

**Comment by ccvlad** [comment]
Try to make some API call after destroySession. The expiration callback is called after getting error

**Comment by codepoetryindia** [comment]
> Try to make some API call after destroySession. The expiration callback is called after getting error

Thanks for your response. issue has been resolved
