### ISSUE TITLE
unable to switch off video on video call

### ISSUE THREAD

**Issue by rexcode** [ConnectyCube/connectycube-reactnative-samples#250]
I have used this  - https://developers.connectycube.com/reactnative/videocalling?id=mute-video
to shut off video during a call but it is not working properly

It freezes the callers' image who has set video to mute but does not make the screen black on the receiver's end.

I have duplicated your set audio mute code from video chat sample

Please guide

![image](https://user-images.githubusercontent.com/12795884/122726292-7f23a500-d293-11eb-83cc-5f6d27dc9789.png)

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
