### ISSUE TITLE
Expo Go Compatible React Native Samples

### ISSUE THREAD

**Issue by mayank-mundhra-2012** [ConnectyCube/connectycube-reactnative-samples#253]
I am building an expo go react native project. Are there any samples for this? Could you please make some

**Comment by ccvlad** [comment]
Hi @mayank-mundhra-2012 !
We do not provide samples for Expo, because Expo does not have an ability to use WebRTC for video/audio calls.
Expo also blocks the customization of Android and iOS projects to use certain features.
You are able to use JS code from [RN Chat Sample](https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNChat/src), but you should replace Expo-incompatible libraries by Expo's analogs.

**Comment by mayank-mundhra-2012** [comment]
Could you make one for in app chat and file sharing. That is the only feature I need.

Is the js one compatible with mobile push notifications and mobile related systems.

Can you make a js sdk for react native + expo.

I will prefer a chat provider who has these so as to simplify my development.

**Comment by ccvlad** [comment]
> Could you make one for in app chat and file sharing. That is the only feature I need.

We will think about it and let you know.
You can use JS code from [RN Chat Sample](https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNChat/src) and replace Expo-incompatible libraries by Expo's analogs as I said. You will save time and understand better if you do it yourself

> Is the js one compatible with mobile push notifications and mobile related systems.

Expo has the [Push Notification](https://docs.expo.io/versions/latest/sdk/notifications/) implementation. Read our [guide](https://developers.connectycube.com/reactnative/push-notifications) to configure it via ConnectyCube admin panel and Firebase project

> Can you make a js sdk for react native + expo.

Our `react-native-connectycube` SDK compatible with Expo except `ConnectyCube.videochat` and `ConnectyCube.videochatconference`. But maybe this will work soon ([see](https://github.com/react-native-webrtc/react-native-webrtc/pull/1013))

> I will prefer a chat provider who has these so as to simplify my development.

The RNChat Sample has all implementations you need. Use the code to start your development. The Expo Push Notification was not being test by our team. We will check this and provide the guide as soon as possible

**Comment by mayank-mundhra-2012** [comment]
> We will think about it and let you know.
You can use JS code from RN Chat Sample and replace Expo-incompatible libraries by Expo's analogs as I said. You will save time and understand better if you do it yourself

Me and my team lack of expertise of android and ios. It might be difficult for us to replace native code modules hence. That is one of the reasons why I am considering using another provider who has this enabled. I can wait for some months before implementing chat. So if you make it then or later, I will definitely consider switching to you'll.

> Our react-native-connectycube SDK compatible with Expo except ConnectyCube.videochat and ConnectyCube.videochatconference. But maybe this will work soon (see)

If you are able to get all the features compatible, first with the expo plugins then as proper expo project eventually, it would be great. We lack the technical expertise and are leveraging interns. If I use react-native-connectycube SDK and only use in app chat and file transfer, will it work with expo or will it throw an error?

**Comment by ccvlad** [comment]
@mayank-mundhra-2012 
Unfortunately, the React Native sample based on Expo SDK isn't our priority.
FYI. The `react-native-connectycube` will work with Expo SDK w/o errors for chat and file transfer.

**Comment by mayank-mundhra-2012** [comment]
That serves my purpose for now. Thanks.

Please eventually build the remaining features also.

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
