### ISSUE TITLE
ConnectyCube.videochat.onCallListener works very slowly 

### ISSUE THREAD

**Issue by DavidAmirKham** [ConnectyCube/connectycube-reactnative-samples#254]
Sometimes, ConnectyCube.videochat.onCallListener is very slowly and can't get session for getUserMedia and makes error?
How to fix this bug?

**Comment by DavidAmirKham** [comment]
Please help me about this issue?

**Comment by DaveLomber** [comment]
hi @DavidAmirKham 

could you specify more about it

- how much it's slow? does it take 5-10 seconds from the call initiated to the onCallListener call at other party? 
- do you use RN at both sides?

**Comment by DavidAmirKham** [comment]
yes, I used RN at both sides and tested two times. 
The first time worked fast and in the second time, onCallListener worked before VideoScreen. 
When navigating to VideoScreen, onCallListener doesn't work.

**Comment by DaveLomber** [comment]
so on 2nd attempt it does not work at all, correct?

**Comment by DavidAmirKham** [comment]
Yes,  2nd attempt it does not work at all

**Comment by DavidAmirKham** [comment]
May be it is need to add 

resetState = () => {
    CallService.stopCall();
    AuthService.logout();
    .
    .
    .
};

**Comment by DaveLomber** [comment]
It seems it's an issue with a code sample itself, and some state is not reset

**Comment by DavidAmirKham** [comment]
Is it the bug from ConnectyCube?

**Comment by DavidAmirKham** [comment]
I would like to get receiving call from all screen and [login](https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNVideoChat/src/components/AuthScreen/index.js) AuthService and navigate to VideoScreen.

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
