### ISSUE TITLE
Push Notification Subscription is removed when sending message

### ISSUE THREAD

**Issue by dipti-samyak** [ConnectyCube/connectycube-reactnative-samples#256]
Can anyone please help us figure out an issue we are facing while sending chat message?
Below is the explanation of the scenario:

- There are two users say User1 & User2
- User1 has Push Notification subscription to an iOS device
- Now, when User2 sends message to User1 (NOTE : User1’s app is in background), User1’s Push Notification subscription is removed. This happens only when User1’s app is in background.
- Note that we haven’t removed subscription manually through code 

Thank you in advance

**Comment by DaveLomber** [comment]
Hi @dipti-samyak 

the push subscription can be removed automatically in the following cases:
- push token is invalid, so when a server sends a push and receives an error form Push Provider, e.g. token invalid, then the subscription will be removed automatically. Usually this can happen when you use dev tokens for prod env OR prod tokens for dev env. Please check this  first. 
- when other user subscribes with same push token, then it will be removed from previous user

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
