### ISSUE TITLE
expo snack?

### ISSUE THREAD

**Issue by TheFinality** [ConnectyCube/connectycube-reactnative-samples#257]
Can you make an expo snack with the video calling? Thanks!

**Comment by ccvlad** [comment]
Hi @JeaIousy !
The [React Native WebRTC](https://github.com/react-native-webrtc/react-native-webrtc) doesn't support Expo. The library used for audio/video calls. Therefore, we have no plans to do Expo samples.

<img width="634" alt="Снимок экрана 2021-08-03 в 11 20 24" src="https://user-images.githubusercontent.com/43810932/127983069-ccbf07aa-ff26-45aa-8bff-acdf2a905672.png">

**Comment by JeaIousy** [comment]
if I eject, will I be able to use this?

**Comment by ccvlad** [comment]
If you do the eject, the result will be the same with using a regular React Native (without Expo). I mean that you will convert Expo project to React Native.

**Comment by JeaIousy** [comment]
oh

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
