### ISSUE TITLE
make lock screen while Video Chating

### ISSUE THREAD

**Issue by DavidAmirKham** [ConnectyCube/connectycube-reactnative-samples#258]
React Native ConnectyCube make lock screen while video chating. How to detect not to lock screen?

**Comment by ccvlad** [comment]
Hi @DavidAmirKham !
Try to use the lib [React Native InCallManager](https://github.com/react-native-webrtc/react-native-incall-manager#api) and call the method `InCallManager.setKeepScreenOn(true)` at start of a video call.

**Comment by DavidAmirKham** [comment]
Thanks, it worked.

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
