### ISSUE TITLE
If call goes more than 10 minutes then if one user end the call then the second user call does not get stop.

### ISSUE THREAD

**Issue by priyankasaini3** [ConnectyCube/connectycube-reactnative-samples#259]
Some time ConnectyCube.videochat.onStopCallListener.   listener not call for second user if call goes more then  9 or 10 minutes. In our APP call will go for more then an hour so we need a solution for that so please guide us how can we handle this case.

Thanks

**Comment by DaveLomber** [comment]
It should work despite the call duration 

Could you please make sure that you still have an active chat connection

Also, you can provide the logs form the side where you stop the call, we will check what's happening under the hood

**Comment by priyankasaini3** [comment]
Hi,
       I have implemented the below code in config file after that it works fine.
Thanks


chat: {
      reconnectionTimeInterval: 5,
      ping: {
        enable: true,
        timeInterval: 60
      },
    },

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
