### ISSUE TITLE
Can't build yourself?

### ISSUE THREAD

**Issue by buzznab** [ConnectyCube/connectycube-reactnative-samples#261]
I love this SDK badly and want my project built around it
Please pardon my trouble. All attempts failed, I couldn't continue to build.
You have said you could it for FREE.
Am asking that you build it up so I can continue from there.
_Got troubles with building React Native code sample? Just create an issue at Issues page - we will create the sample for you. For FREE!_
 Chat /P2P/Video/Conference etc

**Comment by DaveLomber** [comment]
Hi @buzznab 

could you please describe in details what you want to build

- which sample you use
- what troubles you have with it

**Comment by buzznab** [comment]
which sample you use

All the features out of the box as seen below
https://github.com/ConnectyCube/connectycube-reactnative-samples

what troubles you have with it
- I failed to combine all both in -one.
- Please help very important

**Comment by DaveLomber** [comment]
There are 2 code samples:

- chat https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNChat
- video calling (updated very recently) https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat

Both are build using similar flow - with functional components, redux etc.

Please try move some parts from one sample to another one, and raise a ticket with details if you face any issues
