### ISSUE TITLE
Not worked , I thought it first high quality integration but nothing worked well 

### ISSUE THREAD

**Issue by joy-mollick** [ConnectyCube/connectycube-reactnative-samples#262]
Not log in correctly , just taking slow time also promise not handling error WEBRtc error when press for call . Very bad experience during development with this

**Comment by DaveLomber** [comment]
@joy-mollick could you please specify which code sample you have an issue with

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
