### ISSUE TITLE
how to clear "No Message Yet" chat

### ISSUE THREAD

**Issue by ciamalaeaskan** [ConnectyCube/connectycube-reactnative-samples#263]
We are using connectycube React and React-native chat system with our application. On that when we open a new chat (dialog) from our contact list and leave that without sending any message, then its showing "No message yet" on our chat history page (refer the attached screenshot). Can we have any settings option to remove that empty chat from our chat history. Can you please help on this.

<img width="321" alt="Screenshot 2021-08-24 at 11 04 29 AM" src="https://user-images.githubusercontent.com/54099216/130566310-4a8fb7ee-42ff-4132-bf3b-eb99e4acc87a.png">

**Comment by DaveLomber** [comment]
you can try to filter here https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNChat/src/screens/main/dialogs/index.js#L122

e.g. create a Redux selector or filter all the empty dialogs

**Comment by DaveLomber** [comment]
A new chat sample with new push notification lib is created 
Please follow this MR for any issues https://github.com/ConnectyCube/connectycube-reactnative-samples/pull/296
