### ISSUE TITLE
Connectycube chat connection failing

### ISSUE THREAD

**Issue by swati229** [ConnectyCube/connectycube-reactnative-samples#264]
I am getting issue while connecting with ConnectyCube chat. Below function
--> await ConnectyCube.chat.connect({ userId, password }) is not working properly due to that Listners for video calling like _OnCallListners and others are not working. 

Please help!!!

**Comment by ccvlad** [comment]
Unfortunately we don't have common sample for this case. For public projects we use push notification to get call info due app is inactive.

- a caller do `session.call()` and [send push notification](https://developers.connectycube.com/js/push-notifications?id=send-push-notifications) in parallel (e.g. send caller name/id and state of call video/audio)
- a callee receives push notification in background and show screen to accept or reject the incoming call
- Init ConnectyCube SDK, connect to chat, assign listeners to get incoming call and do `session.accept()` or `session.reject()` after the callee has chosen `accept` or `reject` action.
- ignore this push notification in foreground, because chat is connected and onCallListener will get call session.

**Comment by brijesh029394** [comment]
Hi @ccvlad 
Thanks for you reply. We are following the same steps which you provided but only push notification things we are using differently means we are calling Firebase Push/VOIP Push API separately in the app. If user is iOS user then we are sending Voip Push notification and if user is Android user then we are sending Firebase push notification. Also we are sending this push notifications after 5 sec of delay, the reason is to add delay here is when we are initiating video call then at receiver end **onCallListeners** takes some time to invoke so due to this we are not getting any session for video call, that's why we are adding 5 sec delay here for push notification.
So we have two queries here which is given below
- The step which we are following for push notification is the right approach?, is this can be cause of Video call connecting issue because sometime video works and sometime not?
- We found that connectycube chat taking sometime to connect due to this call was not connected, so how we can resolve this?

Please look at below connectycube code which we are using for video call. Please check and let us know if we are doing anything wrong here.

App.js

export default class App extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            appState: AppState.currentState,
            showIncomingModal: false,
            localStream: null,
            remoteStreams: [],
            isActiveCall: false,
            isIncomingCall: false,
            showProgress: false,
            showInomingVideoCall: undefined,
            answerCall: false,
            applicationKill: true,
}
  this._setUpListeners();
this._session1 = null;
        this.localStream = null;
        this.remoteStreams = [];
        this.showCallFromKill = false;



 async _setUpListeners() {

        await ConnectyCube.init(...config);
        setTimeout(() => {
            ConnectyCube.videochat.onCallListener = this._onCallListener;
            ConnectyCube.videochat.onAcceptListener = this._onAcceptCallListener;
            ConnectyCube.videochat.onRejectCallListener = this._onRejectCallListener;
            ConnectyCube.videochat.onStopCallListener = this._onStopCallListener;
            ConnectyCube.videochat.onUserNotAnswerListener = this._onUserNotAnswerListener;
            ConnectyCube.videochat.onRemoteStreamListener = this._onRemoteStreamListener;
            ConnectyCube.videochat.onSessionConnectionStateChangedListener = this.onSessionConnectionStateChangedListener;
        }, 5000);
    }

// i used callkeep for allState(background, foreground, kill)


 RNCallKeep.addEventListener('answerCall', async ({ callUUID, ...o }) => {
            await AsyncStorage.setItem('answerFromKill', 'true'); 
            this.setState({ showProgress: true, answerCall: true });

            if (AppState.currentState === 'background') {
                await AuthService.autologin().then(() => {
                    console.log('AuthServiceanswerCallkillStateSwati')
                    if (AppState.currentState === 'background') {
                        LaunchApplication.open('MobilPT');
                    }
                    this.recurse();
                });
            } else {
                console.log('AuthServicecallkillStateSwati')
                this.recurse();
            }
        });

        RNCallKeep.addEventListener('endCall', async ({ callUUID, type }) => {
            if (!this.state.answerCall) {
                if (this._session1 != null) {
                    this._onPressReject()
                } else {
                    //call api when get killValue = true
                }
            }

        });


  recurse = () => {
        var t;
        var count = 0;
        t = setInterval(async () => {
            if (this._session1 !== null) {
                console.log('recurseSession', this._session1)
                clearInterval(t);
                this._onPressAccept();
            }
            count++;
            console.log('CounValueSessiontValue', count);

            if (count > 5) {
                clearInterval(t);
            }
        }, 1000);

    };

_onCallListener = async (session, extension) => {
        const logDetails = ' _onCallListener ' + session;
        this.checkViceoCall(logDetails)
        
        console.log('_onCallListenerCheck', extension)
        console.log('checkActiveCall', this.state.isActiveCall)
        this._session1 = session;
        CallService.processOnCallListener(session)
            .then(() => this.showInomingCallModal(session)) // after checking going to show incoming call
            .catch(this.hideInomingCallModal);
    };

_onPressAccept = async () => {
        RNCallKeep.rejectCall('3e0729b4-e167-11eb-890e-53204137ebb5');
        CallService.acceptCall(this._session1).then((stream) => {
            console.log('acceptCall', stream)
            const { opponentsIDs, initiatorID, currentUserID } = this._session1;
            const opponentsIds = [initiatorID, ...opponentsIDs].filter(
                (userId) => currentUserID !== userId,
            );
            this.initRemoteStreams(opponentsIds);
            this.setLocalStream(stream);
            this.makeSessionNull();
        });

    };

**Comment by brijesh029394** [comment]
HI @ccvlad 

We have created some some logs from the application. Please look at below logs. The behaviour is very much inconsistent. The call is not connected and on the Receiver side it is showing Caller Is Busy &  Caller side Calling window is keep getting disconnected. Call is not connected.

08/30/2021 12:06:57 setup from kill state 

08/30/2021 12:06:57 VoipPushNotificationRegisterToken  1bff937b8871acf365792f29c4cd561ab4bcd6434ac023dae366def01d100f2f

08/30/2021 12:07:38loginWithConnectycube Connected

08/30/2021 12:08:30 _onCallListener ID: 1f34539f-49f6-42fb-a6a3-309160d50e4a, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:08:30 showInomingCallModal ID: 1f34539f-49f6-42fb-a6a3-309160d50e4a, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:08:30 applicationKill null

08/30/2021 12:08:30 _onRejectCallListener ID: 1f34539f-49f6-42fb-a6a3-309160d50e4a, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 14477689

08/30/2021 12:08:30 _onStopCallListener ID: 1f34539f-49f6-42fb-a6a3-309160d50e4a, initiatorID:  4477737, opponentsIDs: 4477689, state: 5, callType: 14477737

08/30/2021 12:08:30 hideInomingCallModal 

08/30/2021 12:08:30 hideInomingCallModal 

08/30/2021 12:08:35 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:08:42 answerCall from kill state 

08/30/2021 12:08:42 RNCallKeep answerCall 

08/30/2021 12:08:44loginWithConnectycube kill Connected

08/30/2021 12:08:47 recurseCall 

08/30/2021 12:08:53loginWithConnectycube kill Connected

08/30/2021 12:08:55loginWithConnectycube kill Connected

08/30/2021 12:09:15 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:09:15 _onCallListener ID: 0b8363cf-b463-4c6d-b400-fbfbfcd4587d, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:09:15 showInomingCallModal ID: 0b8363cf-b463-4c6d-b400-fbfbfcd4587d, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:09:15 _onRejectCallListener ID: 0b8363cf-b463-4c6d-b400-fbfbfcd4587d, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 14477689

08/30/2021 12:09:16 _onStopCallListener ID: 0b8363cf-b463-4c6d-b400-fbfbfcd4587d, initiatorID:  4477737, opponentsIDs: 4477689, state: 5, callType: 14477737

08/30/2021 12:09:16 hideInomingCallModal 

08/30/2021 12:09:16 endCall from kill state 

08/30/2021 12:09:16 RNCallKeep endCall 

08/30/2021 12:09:16 hideInomingCallModal 

08/30/2021 12:09:40loginWithConnectycube kill Connected

08/30/2021 12:09:44loginWithConnectycube kill Connected

08/30/2021 12:10:34loginWithConnectycube kill Connected

08/30/2021 12:10:37 _onCallListener ID: 0c257b40-14de-47bb-b08c-9d9719f1d738, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:10:37 showInomingCallModal ID: 0c257b40-14de-47bb-b08c-9d9719f1d738, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:10:38loginWithConnectycube kill Connected

08/30/2021 12:10:42 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:10:45 answerCall from kill state 

08/30/2021 12:10:45 RNCallKeep answerCall 

08/30/2021 12:10:45 RNCallKeep answerCall else background active

08/30/2021 12:10:50 recurseCall 

08/30/2021 12:10:51 recurseCallSessionCount 0

08/30/2021 12:10:51 _onPressAccept ID: 0c257b40-14de-47bb-b08c-9d9719f1d738, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:10:51 endCall from kill state 

08/30/2021 12:10:51 RNCallKeep endCall 

08/30/2021 12:10:52 makeSessionNull 

08/30/2021 12:10:52 _onRemoteStreamListener ID: 0c257b40-14de-47bb-b08c-9d9719f1d738, initiatorID:  4477737, opponentsIDs: 4477689, state: 2, callType: 14477737

08/30/2021 12:11:41 _onStopCallListener ID: 0c257b40-14de-47bb-b08c-9d9719f1d738, initiatorID:  4477737, opponentsIDs: 4477689, state: 5, callType: 14477737

08/30/2021 12:11:41 resetState 

08/30/2021 12:11:41 resetState 

08/30/2021 12:11:41 hideInomingCallModal 

08/30/2021 12:11:41 hideInomingCallModal 

08/30/2021 12:12:15 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:12:15 _onCallListener ID: 6b429a25-4b76-4d24-9e06-a7bc6fd2607f, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:12:15 showInomingCallModal ID: 6b429a25-4b76-4d24-9e06-a7bc6fd2607f, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:12:15 _onRejectCallListener ID: 6b429a25-4b76-4d24-9e06-a7bc6fd2607f, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 14477737

08/30/2021 12:12:15 _onCallListener ID: 22733ed7-43ee-4a92-91a3-d1c4e87a1e4a, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:12:15 showInomingCallModal ID: 22733ed7-43ee-4a92-91a3-d1c4e87a1e4a, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:12:15 _onRejectCallListener ID: 22733ed7-43ee-4a92-91a3-d1c4e87a1e4a, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 14477737

08/30/2021 12:12:16 hideInomingCallModal 

08/30/2021 12:12:16 hideInomingCallModal 

08/30/2021 12:12:16 endCall from kill state 

08/30/2021 12:12:16 RNCallKeep endCall 

08/30/2021 12:12:18 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:12:20 answerCall from kill state 

08/30/2021 12:12:20 RNCallKeep answerCall 

08/30/2021 12:12:22loginWithConnectycube kill Connected

08/30/2021 12:12:25 recurseCall 

08/30/2021 12:13:22 endCall from kill state 

08/30/2021 12:13:22 RNCallKeep endCall 

08/30/2021 12:14:11 setup from kill state 

08/30/2021 12:14:11 VoipPushNotificationRegisterToken  1bff937b8871acf365792f29c4cd561ab4bcd6434ac023dae366def01d100f2f

08/30/2021 12:14:12loginWithConnectycube kill Connected

08/30/2021 12:14:32loginWithConnectycube Connected

08/30/2021 12:15:24 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:15:24 _onCallListener ID: 8fd37b4f-f73d-451d-a5bf-6e8419755a59, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:15:24 showInomingCallModal ID: 8fd37b4f-f73d-451d-a5bf-6e8419755a59, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:15:24 _onRejectCallListener ID: 8fd37b4f-f73d-451d-a5bf-6e8419755a59, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 14477737

08/30/2021 12:15:25 hideInomingCallModal 

08/30/2021 12:15:25 endCall from kill state 

08/30/2021 12:15:25 RNCallKeep endCall 

08/30/2021 12:16:04loginWithConnectycube kill Connected

08/30/2021 12:16:08 _onCallListener ID: 4ea96d40-a5e5-47b2-9f07-22fe982b986a, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:16:08 showInomingCallModal ID: 4ea96d40-a5e5-47b2-9f07-22fe982b986a, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:16:08 _onRejectCallListener ID: 4ea96d40-a5e5-47b2-9f07-22fe982b986a, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 14477737

08/30/2021 12:16:09 hideInomingCallModal 

08/30/2021 12:16:12 _onCallListener ID: dd4c68a8-de72-49bf-bcee-fadf17988d16, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:16:12 showInomingCallModal ID: dd4c68a8-de72-49bf-bcee-fadf17988d16, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:16:12 _onRejectCallListener ID: dd4c68a8-de72-49bf-bcee-fadf17988d16, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 14477737

08/30/2021 12:16:12 hideInomingCallModal 

08/30/2021 12:16:13 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:16:16 answerCall from kill state 

08/30/2021 12:16:16 RNCallKeep answerCall 

08/30/2021 12:16:16 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:16:17 _onCallListener ID: 5ca3eb17-f9e4-41c9-b3ba-74d0d0a15b04, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:16:17 showInomingCallModal ID: 5ca3eb17-f9e4-41c9-b3ba-74d0d0a15b04, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:16:17 _onRejectCallListener ID: 5ca3eb17-f9e4-41c9-b3ba-74d0d0a15b04, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 14477737

08/30/2021 12:16:17 hideInomingCallModal 

08/30/2021 12:16:17 endCall from kill state 

08/30/2021 12:16:17 RNCallKeep endCall 

08/30/2021 12:16:17loginWithConnectycube kill Connected

08/30/2021 12:16:21 _onCallListener ID: 9676b08e-2505-4cf6-bbb2-e4339827ff63, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:16:21 showInomingCallModal ID: 9676b08e-2505-4cf6-bbb2-e4339827ff63, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:16:21 _onRejectCallListener ID: 9676b08e-2505-4cf6-bbb2-e4339827ff63, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 14477737

08/30/2021 12:16:21 hideInomingCallModal 

08/30/2021 12:16:21 recurseCall 

08/30/2021 12:16:22 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:16:25 answerCall from kill state 

08/30/2021 12:16:25 RNCallKeep answerCall 

08/30/2021 12:16:25 RNCallKeep answerCall else background active

08/30/2021 12:16:26 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:16:30 recurseCall 

08/30/2021 12:16:37 _onCallListener ID: 3d97180d-3c80-4c4b-b11e-18a609cbaa56, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:16:37 showInomingCallModal ID: 3d97180d-3c80-4c4b-b11e-18a609cbaa56, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:16:37 _onRejectCallListener ID: 3d97180d-3c80-4c4b-b11e-18a609cbaa56, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 14477737

08/30/2021 12:16:37 hideInomingCallModal 

08/30/2021 12:16:37 endCall from kill state 

08/30/2021 12:16:37 RNCallKeep endCall 

08/30/2021 12:16:41 _onCallListener ID: 7a670a14-5496-412b-9e7d-8cf32097b79f, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:16:41 showInomingCallModal ID: 7a670a14-5496-412b-9e7d-8cf32097b79f, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:16:41 _onRejectCallListener ID: 7a670a14-5496-412b-9e7d-8cf32097b79f, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 14477737

08/30/2021 12:16:41 hideInomingCallModal 

08/30/2021 12:16:42 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:16:46 answerCall from kill state 

08/30/2021 12:16:46 RNCallKeep answerCall 

08/30/2021 12:16:46 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:16:47loginWithConnectycube kill Connected

08/30/2021 12:16:51 recurseCall 

08/30/2021 12:16:52 _onCallListener ID: ba76186e-ac84-4d0d-b158-b60863fe62ca, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:16:52 showInomingCallModal ID: ba76186e-ac84-4d0d-b158-b60863fe62ca, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:16:53 _onRejectCallListener ID: ba76186e-ac84-4d0d-b158-b60863fe62ca, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 14477737

08/30/2021 12:16:53 hideInomingCallModal 

08/30/2021 12:16:53 endCall from kill state 

08/30/2021 12:16:53 RNCallKeep endCall 

08/30/2021 12:16:58 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:17:01 answerCall from kill state 

08/30/2021 12:17:01 RNCallKeep answerCall 

08/30/2021 12:17:03loginWithConnectycube kill Connected

08/30/2021 12:17:06 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:17:06 _onCallListener ID: a1661e09-6463-4939-9699-d29443e3cee3, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:17:06 showInomingCallModal ID: a1661e09-6463-4939-9699-d29443e3cee3, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:17:06 _onRejectCallListener ID: a1661e09-6463-4939-9699-d29443e3cee3, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 14477737

08/30/2021 12:17:06 recurseCall 

08/30/2021 12:17:06 hideInomingCallModal 

08/30/2021 12:17:07 endCall from kill state 

08/30/2021 12:17:07 RNCallKeep endCall 

08/30/2021 12:17:15 _onCallListener ID: 7d3e98fa-ce25-405c-ba7f-120b286b7902, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:17:15 showInomingCallModal ID: 7d3e98fa-ce25-405c-ba7f-120b286b7902, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:17:15 _onRejectCallListener ID: 7d3e98fa-ce25-405c-ba7f-120b286b7902, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 14477737

08/30/2021 12:17:16 hideInomingCallModal 

08/30/2021 12:17:21 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:17:23 answerCall from kill state 

08/30/2021 12:17:23 RNCallKeep answerCall 

08/30/2021 12:17:23 RNCallKeep answerCall else background active

08/30/2021 12:17:24 VoipPushNotification  {"type":"voip","aps":{"content-available":1,"alert":"Video calling","badge":1},"fullName":"Robert"}

08/30/2021 12:17:28 recurseCall 

08/30/2021 12:17:30 _onCallListener ID: ceef8c19-0c4c-42bf-a6b2-b73235619fb4, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:17:30 showInomingCallModal ID: ceef8c19-0c4c-42bf-a6b2-b73235619fb4, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:17:30 recurseCallSessionCount 1

08/30/2021 12:17:30 _onPressAccept ID: ceef8c19-0c4c-42bf-a6b2-b73235619fb4, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 1

08/30/2021 12:17:30 endCall from kill state 

08/30/2021 12:17:30 RNCallKeep endCall 

08/30/2021 12:17:30 _onRejectCallListener ID: ceef8c19-0c4c-42bf-a6b2-b73235619fb4, initiatorID:  4477737, opponentsIDs: 4477689, state: 1, callType: 14477737

08/30/2021 12:17:30 hideInomingCallModal

**Comment by DaveLomber** [comment]
Could someone confirm whether this issue is still actually? We will follow up
