### ISSUE TITLE
onCallListener is not working in iOS during kill state.

### ISSUE THREAD

**Issue by brijesh029394** [ConnectyCube/connectycube-reactnative-samples#267]
We are using connectycube library for video calling and onCallListener is not working in kill state in iOS due to this we are not getting any session and not able to connect video call. 

Please provide any suggestion.

**Comment by DaveLomber** [comment]
An updated video chat code sample with CallKit support is implemented

- code sample https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat
- blog post https://connectycube.com/2022/11/08/react-native-video-chat-code-sample-with-call-kit-support/
- documentation https://developers.connectycube.com/reactnative/videocalling?id=callkit
