### ISSUE TITLE
Push Notification sometimes works , sometimes doesn't work above android 9 

### ISSUE THREAD

**Issue by joy-mollick** [ConnectyCube/connectycube-reactnative-samples#268]
I have tried everything regarding push notification but nothing works well. It was working on below Android 10 but above that notification is not working. After searching for some hours,I found there might be sometimes duplicate notifications come which cause duplicate messages also in chat dialog . Please can anyone help?

**Comment by DaveLomber** [comment]
@joy-mollick we brought a new push notifications library which addressed some issues   https://github.com/ConnectyCube/connectycube-reactnative-samples/pull/296

Please read the details and provide a feedback/comments if any
