### ISSUE TITLE
No doubt ,message gets duplicated all time with RNChat sample project . Any help ???

### ISSUE THREAD

**Issue by joy-mollick** [ConnectyCube/connectycube-reactnative-samples#269]
This doesn't work well , there are so many warnings . There is also all time duplicate messages which has not been seen ,when you enter to see unseen messages then all unread messages gets duplicated !!!! 
 which just make this package painful. There are so many bugs also ......

**Comment by DaveLomber** [comment]
A new chat sample with new push notification lib is created 
Please follow this MR for any issues https://github.com/ConnectyCube/connectycube-reactnative-samples/pull/296
