### ISSUE TITLE
Can I use videochat and onlychat option together like whatsapp or messenger ??? Anyone help ?

### ISSUE THREAD

**Issue by joy-mollick** [ConnectyCube/connectycube-reactnative-samples#270]
I want to use video chatting integrating with my RNChat app like whatsapp , But Without cloning RNVideoChat app from here ,you can't make video chat application manually ,there will be so many bugs . So How can I integrate both into one application .Any suggest.

**Comment by DaveLomber** [comment]
The best way would be the following:

1) check and learn Chat app https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNChat

along with Chat API documentation https://developers.connectycube.com/reactnative/messaging 

2) Check and learn Video Chat app https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat

along with Video Chat API documentation https://developers.connectycube.com/reactnative/videocalling

3) Then, use Chat app as a basis and integrate Video Chat features into it

**Comment by joy-mollick** [comment]
> The best way would be the following:
> 
> 1. check and learn Chat app https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNChat
> 
> along with Chat API documentation https://developers.connectycube.com/reactnative/messaging
> 
> 1. Check and learn Video Chat app https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat
> 
> along with Video Chat API documentation https://developers.connectycube.com/reactnative/videocalling
> 
> 1. Then, use Chat app as a basis and integrate Video Chat features into it

I can't make manually video chat working demo without cloning this RNVideoChat example , This is the main problem I can't integrate video features into chat basis app , I have already completed chat app . So I decided adding chat app files with RnVideo Chat example , but unfortunately many unknown errors during doing this . I added whole RNChat navigation as a navigation component to RNVideoChat navigator.js . And then add functionality by pressing button to go there ,but when I use VideoChat ,that is ok but when I navigate to chat app component by pressing button Suddenly unknown errors and undefined is not function and............................ dev=false,minify something error . Could you kindly please help me to work this issue out ?

**Comment by DaveLomber** [comment]
An updated video chat code sample with CallKit support is implemented

- code sample https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat
- blog post https://connectycube.com/2022/11/08/react-native-video-chat-code-sample-with-call-kit-support/
- documentation https://developers.connectycube.com/reactnative/videocalling?id=callkit

Now it should be easier to integrate both samples together cause they share a similar development flow
