### ISSUE TITLE
Connecticube Video Call Issue

### ISSUE THREAD

**Issue by NavneetSachan** [ConnectyCube/connectycube-reactnative-samples#271]
Dear Team,
           In one of our project we have used FREE version of connectycube. We have implemented Chat, Video call but recently customer provided feedbacks that "Audio is not good in calling" also some time we found issues while Logging into connectycube user account which is needed to initiate Chat and Video. Are they known issues? Are these issues because of poor internet connection?

Also I wanted to check what are the limitations of FREE VERSION over paid options apart form support and cloud? 

Once we know the limitations we can get back to customer with recommendations.

**Comment by DaveLomber** [comment]
@NavneetSachan there should not be much diff between free & hobby/pro plans in terms of call quality 

Are you using P2P calls?

**Comment by NavneetSachan** [comment]
Yes we are using P2P calls.

Most of the issues are coming when while initiating a chat we try to Login to conencituce user account  and when we gets failed we are showing "Services Unavailable at this moment" but this is happening very frequently.

**Comment by DaveLomber** [comment]
@NavneetSachan are you able to provide more information which API is failing ? 
Would be great to get more information which API and what exact error you receive

**Comment by DaveLomber** [comment]
@swati229 thanks
The last question - what's your location region?

**Comment by DaveLomber** [comment]
There were recently some updates in terms of video calling and React Native

1) An updated video chat code sample with CallKit support is implemented

- code sample https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat
- blog post https://connectycube.com/2022/11/08/react-native-video-chat-code-sample-with-call-kit-support/
- documentation https://developers.connectycube.com/reactnative/videocalling?id=callkit

2) There is a new feature to limit the max cap bandwidth 
https://developers.connectycube.com/reactnative/videocalling?id=call-quality
which can help improve the call quality.
We suggest to play with the feature and see if it helps to improve the quality at your end

Please let us know
