### ISSUE TITLE
Can't able to open dialog for some users

### ISSUE THREAD

**Issue by ciamalaeaskan** [ConnectyCube/connectycube-reactnative-samples#272]
Hi,  we are using our Connectycube web chat system in our application,  On that we need to open dialog with thier dialog-id from external link but its not working for some user, because we are showing only 100 dialogs per user on the left pane while login. But that respective dialog is not available on that list. Do we have any other option or api to  open user dialog which is not available on that list.

**Comment by DaveLomber** [comment]
If it's not there, then I suggest to retrieve the dialog from server, by id

https://developers.connectycube.com/reactnative/messaging?id=list-dialogs
Look at filters 

you can pass '_id: xxx' and get this particular dialog from server

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
