### ISSUE TITLE
not login

### ISSUE THREAD

**Issue by ilayadivya** [ConnectyCube/connectycube-reactnative-samples#273]
i got an error when  login as an user.

{"line":213460,"column":25,"sourceURL":"http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.testapp&modulesOnly=false&runModule=true"}

**Comment by DaveLomber** [comment]
which error? could you provide the complete log

**Comment by ilayadivya** [comment]
I used react native sample video calling sample code .

I just changed config file and click on login as user button , it is
showing alert message like already sent.

Please help me resolve it.

**Comment by DaveLomber** [comment]
The above alert is not complete 

Plese post the complete erorr log

**Comment by ilayadivya** [comment]
They are no error log , only geting error alert, guide me get log

**Comment by DaveLomber** [comment]
An updated video chat code sample with CallKit support is implemented

- code sample https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat
- blog post https://connectycube.com/2022/11/08/react-native-video-chat-code-sample-with-call-kit-support/
- documentation https://developers.connectycube.com/reactnative/videocalling?id=callkit

Please try it at your end and raise an issue if it's still actual
