### ISSUE TITLE
onNotification event is triggered but notification doesn't popup

### ISSUE THREAD

**Issue by UmerQur3shi** [ConnectyCube/connectycube-reactnative-samples#278]
Hello,
I'm trying to implement connectycube push notifications for android, the onNotification event is triggered when a notification is sent from connectycube console and in the app but the notification doesn't popup in the device, I've tried on both emulator and physical device and the result was same. I'm doing everything according to the instructions given, please tell me why I'm getting a silent notification with no popup? regards.

**Comment by andybui090** [comment]
me too, help
