### ISSUE TITLE
ConnectyCube sends silent data to the App instead of notification

### ISSUE THREAD

**Issue by UmerQur3shi** [ConnectyCube/connectycube-reactnative-samples#279]
Hello,
Notifications sent to the App via ConnectyCube do not popup and there is no sound as well, it only sends data to the App and onNotification is triggered. To make it work I need to make a local notification in onNotification of my App, is there any way to send a proper noisy notification to the App instead of silent data which doesn't even popup notification? Help will be appreciated, thanks.

**Comment by DaveLomber** [comment]
As for now - only FCM Data notifications are supported.

There is a task to add support the FCM Notifications type. That will be added in near future
