### ISSUE TITLE
OnSent is called before onDelivered most of the time

### ISSUE THREAD

**Issue by UmerQur3shi** [ConnectyCube/connectycube-reactnative-samples#280]
I've implemented the message status/send_state logic according to the sample provided for chat. The issue is that onSent is called after onDelivered most of the time which is causing problem in displaying the corrent current status of a message, how do we avoid onSent being called after onDelivered by the listener?

**Comment by DaveLomber** [comment]
@UmerQur3shi theoretically speaking it could sometime happen due to network delays

Th proper flow to handle it is to check the message status in Redux. If it's already DELIVERED, then ignore it in 'onSent' callback
