### ISSUE TITLE
Way to check if user being called is busy

### ISSUE THREAD

**Issue by alphazrexx** [ConnectyCube/connectycube-reactnative-samples#282]
Hi,

I am integrating your sample code for 1-1 chat and video calling service in an existing react native app

I am using remote and local push notification to alert the call receiver of an incoming call but when some other user calls the receiver, the current call is sometimes stopped (because of notification reloading the app for navigating to call screen) or a new call alert is received in the existing call ?

So before I call is there a way to check whether the user being called is busy and if so redirect the user to another caller ?

**Comment by DaveLomber** [comment]
Potentially you could share a state of call somewhere and check it before initiating a call

But this could lead to sone collisions, e.g. in some case you will be getting false positive states 

What I recommend is the following:
- call a user
- on receiver side - to check if a user is busy and if yes - reject a call under the hood with a special status, so a call initiator can process it accordingly

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
