### ISSUE TITLE
Last activity subscription listener not working

### ISSUE THREAD

**Issue by UmerQur3shi** [ConnectyCube/connectycube-reactnative-samples#283]
Hey there,
I'm trying to get the online/last seen status of a user but the listener provided in the docs (ConnectyCube.chat.onLastUserActivityListener) is not working.
The method ConnectyCube.chat.getLastUserActivity(userId) is working fine but I need to subscribe to the status/Last activity of a user when the chat box is open. Please let me know how to make that listener work if I'm not doing it correctly. Help will be appreciated, thanks.

**Comment by DaveLomber** [comment]
@UmerQur3shi this feature had a limited access for a while.
Now it should be available for everyone. Please try again using the documentation https://developers.connectycube.com/js/messaging?id=last-activity-subscription
