### ISSUE TITLE
Notification is sending in Both Side Application when i sending chat message.

### ISSUE THREAD

**Issue by ParmarJigarr** [ConnectyCube/connectycube-reactnative-samples#284]
I have set up the chat from connectycube and sending and receiving messages successfully , than i use make set up for push Notification set up and getting the normal notification of app when order accept and cancel order but when i intigrating push notification set up of connectycube than i am getting notifications from chats but the issue is i am sending msg from driver app than i am getting notifications  into the both driver and customer app instead of customer app.

**Comment by DaveLomber** [comment]
@ParmarJigarr if you have 2 diff mobile apps with same ConnectyCube App ID, then you need to do the following:

1) when subscribe to pushes, pass a proper 'bundle_identifier', so each app has its own bundle_identifier.
It means a user subscribes for pushes only for this particular app

https://developers.connectycube.com/reactnative/push-notifications?id=subscribe-to-push-notifications

3) Then also, you need 2 different iOS push notifications certificates, with diff bundles ids.
You need to create 2 of them and upload to ConnectyCube dashboard. 

Then in this case, a user will be receiving a push on particular app only

**Comment by ParmarJigarr** [comment]
Thanks for your replay .
I have checked my driver side bundle id That is correct still i am getting notifications in both side and currently i am checking for android side so i have not performed 3rd step which you mentioned.

**Comment by DaveLomber** [comment]
A new chat sample with new push notification lib is created 
Please follow this MR for any issues https://github.com/ConnectyCube/connectycube-reactnative-samples/pull/296
