### ISSUE TITLE
push notification not working in IOS

### ISSUE THREAD

**Issue by ParmarJigarr** [ConnectyCube/connectycube-reactnative-samples#286]
we have application with 2 side one is customer and another is driver and not getting notifications in IOS side
queries
1. We have to make two different account for driver and customer or single account can manage ?
2. We have checked in error log as well but there is no any type of error showing , we have uploaded p12 certificates as well for driver and customer both side.
3 . does it support p8 certificate ?

**Comment by ParmarJigarr** [comment]
We have two apps and need to upload p12 certificate for both side with single account and in dashboard we can only upload single p12 certificate so how can we manage ?

**Comment by DaveLomber** [comment]
1 - you need a SINGLE ConnectyCUbe app/account
2 - 2 certificates should be uploaded 
3 - not yet

Also 

when subscribe to pushes, pass a proper 'bundle_identifier', so each app has its own bundle_identifier.

It means a user subscribes for pushes only for this particular app
https://developers.connectycube.com/reactnative/push-notifications?id=subscribe-to-push-notifications


Can you confirm you have done it?

**Comment by ParmarJigarr** [comment]
Yes , i have done it but getting 422 error in log and also i can see on subscription is success

**Comment by DaveLomber** [comment]
@ParmarJigarr please provide an example of the 422 in a log

We should be able to get more info from it

**Comment by DaveLomber** [comment]
A new chat sample with new push notification lib is created 
Please follow this MR for any issues https://github.com/ConnectyCube/connectycube-reactnative-samples/pull/296
