### ISSUE TITLE
Remote notification received but not showing on android ! Not working .

### ISSUE THREAD

**Issue by joy-mollick** [ConnectyCube/connectycube-reactnative-samples#288]
Notification received but silently not showing up like pop up notifications on android . This issue is very common but still not be able to find any proper solution . This is really unexpected !

**Comment by DaveLomber** [comment]
PLease check https://github.com/ConnectyCube/connectycube-reactnative-samples/issues/222#issuecomment-1018585971

**Comment by DaveLomber** [comment]
@joy-mollick we brought a new push notifications library which addressed some issues   https://github.com/ConnectyCube/connectycube-reactnative-samples/pull/296

Please read the details and provide a feedback/comments if any
