### ISSUE TITLE
if i try to send message after some time from customer side app , the message was not sent into other driver side app.

### ISSUE THREAD

**Issue by ParmarJigarr** [ConnectyCube/connectycube-reactnative-samples#291]
if i try to send message after some time from customer side app (app was idle for about 10 minutes) , the message was not sent into other driver side app. i need to kill the app and reopen app the it will work fine

**Comment by ccvlad** [comment]
Hi @ParmarJigarr
Device's OS closes chat connection after some time in inactive state.
I suggest you import '@react-native-community/netinfo' and listen to internet connection. Do `ConnectyCube.chat.disconnect()` when your app losses internet connection and call `ConnectyCube.chat.connect(params)` after the internet becomes online.

**Comment by ParmarJigarr** [comment]
okay so where i have to do this code of internet connection ? on press of send message of somewhere else ?

**Comment by DaveLomber** [comment]
You have to put it inside some service class file

because it's a listener 

```
import NetInfo from "@react-native-community/netinfo";


// Subscribe
const unsubscribe = NetInfo.addEventListener(state => {
  console.log("Connection type", state.type);
  console.log("Is connected?", state.isConnected);
});

// Unsubscribe
unsubscribe();
```
