### ISSUE TITLE
onMessage Listener: Sent message from one party is not being received by other party,

### ISSUE THREAD

**Issue by natalialuzuriaga** [ConnectyCube/connectycube-reactnative-samples#292]
Hi there,

I am developing a React Native app using Expo and am using react-native-connectycube version 3.14.0.

I'm encountering an issue where when both parties are connected to ConnectyCube, the messages being sent from one party are not being received by the other party. 

I think this might have to do with the onMessage listener. I implemented the listeners exactly the same way as the ChatService.js service file in the React Native Samples. I am receiving nothing from the onMessage listener when the message is sent.

Any guidance would be much appreciated!

Below are the logs for when I send a message:
<img width="862" alt="Screen Shot 2022-02-13 at 7 33 06 PM" src="https://user-images.githubusercontent.com/29980737/153795705-a9071067-0f4c-4c03-a2f8-cc0825d3be2c.png">

**Comment by DaveLomber** [comment]
I see 'type=3' which is wrong

it should be `type="chat"` for 1-1 and  `type="groupchat"` for group chats

**Comment by natalialuzuriaga** [comment]
Thanks for getting back to me!

As advised, I passed in ``type="chat"`` when calling ``ConnectyCube.chat.send(params)``. The onMessage listener is still not being triggered as shown in the updated logs below:

<img width="764" alt="Screen Shot 2022-02-18 at 1 19 24 AM" src="https://user-images.githubusercontent.com/29980737/154659970-23f643cb-eac9-458f-a22a-9d9436f7f51e.png">

**Comment by DaveLomber** [comment]
Ok then please show 2 code snippets:

- how you send a message
- and a place where you set listeners. Is it before chat connect or after? Try to set it all before
