### ISSUE TITLE
Notification suddenly stopped working - Error: getaddrinfo EMFILE fcm.googleapis.com : getaddrinfo EMFILE fcm.googleapis.com

### ISSUE THREAD

**Issue by rexcode** [ConnectyCube/connectycube-reactnative-samples#293]
Hi there,

I have built a app few months back using your chat and video call service, app was working fine. Notifications were working fine.
Now I have rebuild the app to make some changes, but notifications are no longer working - 

My app details - 
 "react-native": "0.63.0",
  "react-native-connectycube": "^3.7.5",

android log
![image](https://user-images.githubusercontent.com/12795884/156144508-7ed926c1-6bfe-49e8-b1ea-79ac804b460d.png)

connectycube admin
![image](https://user-images.githubusercontent.com/12795884/156144648-61218319-4f1d-434e-ba0c-ab331648f533.png)

Notification log from connectycube admin - 1
![image](https://user-images.githubusercontent.com/12795884/156144705-b5d13875-4eef-46ee-a5cc-58dd9434a310.png)

Notification log from connectycube admin - 2
![image](https://user-images.githubusercontent.com/12795884/156144742-d70c011f-60b9-4a0e-827c-251d92fc4e0d.png)

Have I to make any changes - as it was all  working fine and suddenly I start getting errror -
 "Error: getaddrinfo EMFILE fcm.googleapis.com : getaddrinfo EMFILE fcm.googleapis.com"

I have also checked with Mobile phone, getting same error

Please guide

**Comment by rexcode** [comment]
Also  I had used  notification to inform call receiving user of incoming video call - viideo call also has stopped

**Comment by DaveLomber** [comment]
@rexcode is it still actual?

**Comment by arnofo** [comment]
Hello,

I encounter the same problem, @rexcode have you found a fix ?

**Comment by DaveLomber** [comment]
@arnofo are you still face it?

**Comment by arnofo** [comment]
@DaveLomber i just tested it and it seems to work again.
Would be nice to know what caused it though.

**Comment by DaveLomber** [comment]
It looks like a network issue, e.g. a ConnectyCube Push service was not able to communicate with Google FCM service by some reason. 

Looks like as an intermittent connection issue

**Comment by andybui090** [comment]
Me too, please help me check push notify android chat message, iOS work, android not work

**Comment by DaveLomber** [comment]
@andybui090 please share more details
