### ISSUE TITLE
Driver change then chatting between new driver and customer is possible ?

### ISSUE THREAD

**Issue by GimmeForeDev1** [ConnectyCube/connectycube-reactnative-samples#294]
i have 2 side application , one is for customer side and second is for driver side 
i have successfully chatting from both side , but after some time now requirement is that driver can also change from backend side so is it possible that initially chatting is working in between 1st driver and customer but now driver change so chaating between second driver and customer ?

**Comment by DaveLomber** [comment]
I suggest to use group chat between driver and customer 

Initially it will be 1 driver and 1 customer in a group chat

But later, you can remove driver 1 from group chat (via Admin Panel) and add Driver 2 to group chat 


- Here is a list of dialogs available in admin panel 
![Screenshot 2022-04-21 at 11 20 13](https://user-images.githubusercontent.com/39332586/164411946-577d61cf-f39c-401d-89c7-30263b01373a.png)

- Click on some dialog and edit its occupants 
![Screenshot 2022-04-21 at 11 20 32](https://user-images.githubusercontent.com/39332586/164411966-00feeea3-e041-4e6e-a79b-06c706e5ef7c.png)
