### ISSUE TITLE
Message not sending first time and  not authorized  user to cat and start chat session not authorized

### ISSUE THREAD

**Issue by UdjinStolboviy** [ConnectyCube/connectycube-reactnative-samples#299]
Hello. The following errors occurred. Please help with the solution. id 5750
Error description.
We are creating a new User and trying to send a message. The first message is not sent to the ConnectyCube.chat.connect service and also does not work properly ConnectyCube.init

There are problems with ConnectyCube.pushnotifications

before that everything worked properly, this error appeared 5 -7 days ago.

the code base of our messenger was not changed. Please tell me what could be the problem?

**Comment by DaveLomber** [comment]
Hi @UdjinStolboviy 

could you please provide more info what errors you face, e.g. some logs/errors exampels

**Comment by UdjinStolboviy** [comment]
![Simulator Screen Shot - iPhone 8 - 2022-06-17 at 10 00 54](https://user-images.githubusercontent.com/63309975/175490855-8c733103-ff56-41cf-a920-3cf95cf94a51.png)
![Simulator Screen Shot - iPhone 8 - 2022-06-17 at 15 17 48](https://user-images.githubusercontent.com/63309975/175490934-a3056ac5-0380-458d-a17f-771114c522bf.png)
![Simulator Screen Shot - iPhone 8 - 2022-06-17 at 15 27 40](https://user-images.githubusercontent.com/63309975/175490970-d3c4152b-2234-47e6-8c4f-483e12ecf5b4.png)
![Simulator Screen Shot - iPhone 8 - 2022-06-17 at 15 33 00](https://user-images.githubusercontent.com/63309975/175490983-7ab813e4-0ba3-4e1b-b15f-36b0f549cb6c.png)

**Comment by DaveLomber** [comment]
If talking about "occupants_ids field must contain an opponent user id"
it means when you create a private 1-1 chat https://developers.connectycube.com/js/messaging?id=create-1-1-chat 
you need to pass another user id in  `occupants_ids` field
e.g. ` occupants_ids: [56],`

**Comment by UdjinStolboviy** [comment]
I pass on all valid data. Your server cannot find this data

**Comment by UdjinStolboviy** [comment]
{ type: DialogType.PRIVATE_CHAT, occupants_ids: opponentIds }

**Comment by UdjinStolboviy** [comment]
![Simulator Screen Shot - iPhone 8 - 2022-06-27 at 09 26 05](https://user-images.githubusercontent.com/63309975/175883533-ecf15fb4-00de-4e39-b57f-12c23d1a920e.png)

**Comment by DaveLomber** [comment]
@UdjinStolboviy non-authorized means the password is wrong 

do you use Custom Identity provider ? or just simple login+pwd flow ?

**Comment by DaveLomber** [comment]
Closed as stale
Please create a new issue if it's still actual
