### ISSUE TITLE
RNChat npm run android failed

### ISSUE THREAD

**Issue by YoungDu** [ConnectyCube/connectycube-reactnative-samples#3]
Got this error:
Could not get unknown property 'mergeResourcesProvider' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.

**Comment by NazarB99** [comment]
Add this to  /node_modules/react-native-push-notification/android/build.gradle
def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION = "+"
def DEFAULT_FIREBASE_MESSAGING_VERSION = "+"

**Comment by DaveLomber** [comment]
@YoungDu does it resolve your issue?

**Comment by YoungDu** [comment]
> @YoungDu does it resolve your issue?

nope

**Comment by DaveLomber** [comment]
@YoungDu ok, could you provide more info re this issue

Dod you run the build using the command `npm run android` ?

Please post the complete output of the log error

We do not face this issue at your side, need to get more info to understand what is the reason  and how we can help

**Comment by gilons** [comment]
> Add this to /node_modules/react-native-push-notification/android/build.gradle
> def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION = "+"
> def DEFAULT_FIREBASE_MESSAGING_VERSION = "+"

That is not the solution
your app has so many issues likes:
-missing packages
-not using androidx 
and still using the old deprecated compile instead of implementation

for this particular issue, the solution if found here
https://github.com/wix/react-native-navigation/issues/4757#issuecomment-468133753

I will make a push request where i resolved those issues if you wish so

**Comment by DaveLomber** [comment]
@gilons we will be much appreciated 🥇

**Comment by gilons** [comment]
hello @DaveLomber i cannot push ot repo i'm getting 403 http error

**Comment by DaveLomber** [comment]
@gilons could you please create a fork of the repo, and then make a PR from your fork to this main repo?

**Comment by gilons** [comment]
ok

**Comment by Pranav-munna** [comment]
> ReactNativeJS ▶︎ TypeError: Invalid attempt to spread non-iterable instance
>                              │ 
>                              │ This error is located at:
>                              │ in AppRoot (created by ConnectFunction)
>                              │ in ConnectFunction (at App.js:10)
>                              │ in Provider (at App.js:9)
>                              │ in App (at renderApplication.js:40)
>                              │ in RCTView (at AppContainer.js:101)
>                              │ in RCTView (at AppContainer.js:119)
>                              └ in AppContainer (at renderApplication.js:39)

I have resolved most of the errors and finally was able to run the sample cod but after running the above mentioned error occurred
