### ISSUE TITLE
set proxy when connecting to cc server

### ISSUE THREAD

**Issue by starlessboi** [ConnectyCube/connectycube-reactnative-samples#302]
HI
I want to be able to set a proxy address when connecting to cc, and route all of my traffic to cc through that address
can I do this in my app?
thanks

**Comment by DaveLomber** [comment]
A `fetch` is used under the hood for HTTP requests.

If you have  a code snippet for `fetch` re how to set a proxy - please share, we will point further

**Comment by DaveLomber** [comment]
I think you can use this lib https://github.com/touv/node-fetch-with-proxy

and overwrite a standard `fetch` implementation
