### ISSUE TITLE
Video call Notification and callkeep not working  when app is in foreground and  background (Killed).

### ISSUE THREAD

**Issue by osamajamal29** [ConnectyCube/connectycube-reactnative-samples#305]
In debug and release build i run the video call sample project but unfortunately when app is in foreground and in killed state notifications and callkeep call option are not coming .Please help

**Comment by DaveLomber** [comment]
@osamajamal29 2 questions:
- which platform - iOS/Android?
- did you setup Push Notifications properly?

**Comment by osamajamal29** [comment]
Thank so much for the response. On both platforms (Android and IOS). Yes i setup  Push Notifications properly . It is  quite strange when i run  video call  sample  project  through cable in my phone  in foreground and in killed state  callkeep (call option are coming).. But when i generate  debug build and then try to test  it is not working.

**Comment by DaveLomber** [comment]
@osamajamal29 "generate debug build" you mean TestFlight build ?

**Comment by DaveLomber** [comment]
@osamajamal29 got it
this is strange cause both debug build and install through cable is basically the same debug build. Is there any errors/warnign when you do ` /gradlew assembleDebug ` ?

**Comment by osamajamal29** [comment]
I run cd android and then  run  ./gradlew assembleDebug in project root terminal. It successfully generate debug build . Build is  also working fine. Video/Audio call functionality also working perfectly when i test app on 2 different devices . But when i close (Killed) app on any one device i assume i receive notification when i try to call the same person in the app  but unfortunately i did-not receive any notification from connectycube . The problem is i am unable to receive notification .Thank you

**Comment by DaveLomber** [comment]
This is can be on of the 2 possible issues:

1) push notifications are not configured properly. 
To check it, can you just check the Android app logs via Android Studio and see of there is a log about received push notification payload.

Also, additional, go to ConnectyCUbe Admin panel, Push Notifications and check Queue section. There should be a list of all pushes sent and their status (delivered vs failed)

2) IF the above ^^^ is working well (means the status in Admin panel is 'delivered' and in Android Studio logs you can see the received push payload), but still nothing is in app UI, 
then I suggest to double check this code is configured properly https://developers.connectycube.com/reactnative/videocalling?id=receive-call-request-in-backgroundkilled-state

**Comment by osamajamal29** [comment]
Ok sure i will let you know. Thank you so much .

**Comment by osamajamal29** [comment]
I identified the problem React native Wix notification right now doesn't support local notification ..

**Comment by DaveLomber** [comment]
re status  'Sent' In ConnectyCube Push Notifications Queue

You can click on it and see the details

**Comment by DaveLomber** [comment]
re WIX - actually it does support local notification https://wix.github.io/react-native-notifications/docs/localNotifications
