### ISSUE TITLE
Check you set participant and login to the chat

### ISSUE THREAD

**Issue by richanshah** [ConnectyCube/connectycube-reactnative-samples#313]
@TatankaConCube , when i create group with two occupant ids 

{"items":[{"user":{"_id":"64edcb9d303009002ea5fcce","id":10551474,"created_at":"2023-08-29T10:42:37Z","updated_at":"2023-08-30T05:30:10Z","last_request_at":"2023-08-30T05:30:10Z","login":"Richa","email":"richashah688@gmail.com","full_name":"Richa Shah","phone":"9016804343","custom_data":"{uuid: a014ef63-e94c-4eeb-b16b-f90e4c681fbf}","avatar":"https://main-court-demo122136-dev.s3.amazonaws.com/public/User/1693305744031191/1693305744031191.jpg","external_id":"a014ef63-e94c-4eeb-b16b-f90e4c681fbf","timezone":null,"website":null,"twitter_id":null,"external_user_id":null,"facebook_id":null,"user_tags":null,"is_guest":null}},{"user":{"_id":"64edcfb4303009002ea5fd83","id":10551524,"created_at":"2023-08-29T11:00:04Z","updated_at":"2023-08-30T05:32:13Z","last_request_at":"2023-08-30T05:32:13Z","login":"Bhumi","email":"shahricha723@gmail.com","full_name":"Bhumi Shah","phone":"9016121616","custom_data":"{uuid: a1c76c8f-d305-4857-bb45-9ba43993720a}","avatar":"https://main-court-demo.s3.amazonaws.com/images/User/User.p

i am getting below error on send message

Check you set participant and login to the chat

**Comment by richanshah** [comment]
onSendMessage message= {_id: 64eed5c60ec7072db093d88a, chat_dialog_id: null, message: hii, date_sent: 1693373894, sender_id: null, recipient_id: null, read_ids: null, delivered_ids: null, views_count: null, attachments: null, reactions: null, id: null, created_at: null, updated_at: null}

**Comment by richanshah** [comment]
well i had to do login again in chat , yesterday's login got expired. although i have handled onsessionexpirted but it didnt go there.

**Comment by TatankaConCube** [comment]
Just for clarification: the API session has its own lifecycle and the chat connection has its own. You should use the `CubeSessionManager` to manage the API session and use the `CubeChatConnection` and its `connectionStateStream` for listening to the chat connection state. Please follow our documentation on how [Connect to chat](https://developers.connectycube.com/flutter/messaging?id=connect-to-chat) and listen to the chat connection state and how to [Create API session](https://developers.connectycube.com/flutter/authentication-and-users?id=create-session-token) and [provide the callback](https://developers.connectycube.com/flutter/authentication-and-users?id=session-expiration) for restoring an expired session.
