### ISSUE TITLE
Receiving Error: WebSocket ECONNERROR wss://chat.connectycube.com:5291

### ISSUE THREAD

**Issue by LagoonProject** [ConnectyCube/connectycube-reactnative-samples#315]
Hi,

I am suddenly receiving the following errors when connecting to chat:

 ERROR  [Chat] xmppClient.start error [Error: WebSocket ECONNERROR wss://chat.connectycube.com:5291]
 ERROR  [Chat] xmppClient.start error [Error: Connection is not offline]

It seems to come from cubeChat.js

**Comment by ccvlad** [comment]
Is something not working for you or are you just seeing the error?

Chat should have an "offline" status for connection but its status is different (e.g. "closing", "online"). It is like the connection to chat was prevented because it is not ready to open a new connection.

**Comment by LagoonProject** [comment]
thanks for your clarification. I don't have this error message anymore, so I guess everything is fine.

**Comment by ccvlad** [comment]
Thanks for your feedback. You can see the error due to the Internet issue. Chat tries to restore the connection and gets the error or other warnings while it is trying to establish the connection
