### ISSUE TITLE
Remove dialog for all users

### ISSUE THREAD

**Issue by LagoonProject** [ConnectyCube/connectycube-reactnative-samples#316]
Hi,

1) To delete a group chat dialog I use this piece of code :

`ConnectyCube.chat.dialog.delete(dialogId)`

But even if the user is the owner, the dialog is removed for the user but remains for the other occupants. Is it possible to delete the dialog for all users with the React Native API ?

2) Side question : is it possible to remove a 1v1 chat dialog from the history  ?

Thanks

**Comment by ccvlad** [comment]
Hi
1. https://developers.connectycube.com/reactnative/messaging/#remove-dialog
- If other occupants were offline while a dialog was deleted then they will have to [sync dialogs with a server ](https://developers.connectycube.com/reactnative/messaging/#list-dialogs) to remove the dialog from UI/DB if needed.
- If other occupants are online while a dialog is deleting, the owner should send [a system message](https://developers.connectycube.com/reactnative/messaging/#system-messages) to each occupant to inform them about the delete action. You can pass the deleted dialog ID to inform which dialog has to be removed from UI/DB
```javascript
      const message = {
        extension: {
          delete_dialog_by_id: dialogId,
        },
      };

      ConnectyCube.chat.sendSystemMessage(userId, message);
```
2. Yes. In the same way. But a 1v1 chat dialog will be recreated if a user sends a message to his opponent

**Comment by LagoonProject** [comment]
thanks @ccvlad .

I think that's what I am doing but I don't get the expected result.

User A creates a group chat (type 2), with user B as an occupant => `ConnectyCube.chat.dialog.create(params)`

User A and User B see the dialog in their dialog list  => `ConnectyCube.chat.dialog.list({})`

Then User A deletes the dialog  => `ConnectyCube.chat.dialog.delete(dialogId);`

User A doesn't see the dialog anymore, but user B still see the dialog in its list when calling  => 
`ConnectyCube.chat.dialog.list({})`

I'm not sure if I am missing something?
The users are connect via firebase and user A appears as the owner of the group chat in the back end.

**Comment by ccvlad** [comment]
@LagoonProject 
Try to do `ConnectyCube.chat.dialog.delete(dialogId, {force: 1})`.
Unfortunately, we didn't specify the second argument in our docs, but it is in [REST API docs](https://developers.connectycube.com/server/chat/#delete-dialog), and `react-native-connectycube` SDK has to support it. Please check with the `force = 1` param and let us know about the result. I will update the docs if it works

**Comment by LagoonProject** [comment]
@ccvlad Thanks so much, it works perfectly, I was missing {force: 1}
