### ISSUE TITLE
FCM server key for cloud messaging

### ISSUE THREAD

**Issue by akashdeep0515** [ConnectyCube/connectycube-reactnative-samples#317]
As FCM server key for cloud messaging is a legacy concept and firebase no longer provides server key, how do i register my firebase project in connectycube console?? The documentation asks to add FCM server key 
![screenshot_capture_-_2024-08-05_-_13-01-12~2](https://github.com/user-attachments/assets/f5b12056-5fec-4885-9f4c-4755b99e3545)

**Comment by DaveLomber** [comment]
@akashdeep0515 from Admin panel there is a guide how to use new approach with Service Account Key

<img width="900" alt="Screenshot 2024-08-05 at 10 52 28" src="https://github.com/user-attachments/assets/1ebeccbc-5767-4a2e-a3b0-f29ae9b4509f">

**Comment by akashdeep0515** [comment]
but firebase won't let me enable Cloud Messaging API (Legacy) as they have removed it completely, i can obtain the server key, and that is my question

**Comment by DaveLomber** [comment]
@akashdeep0515 In this case you just need to upload JSON key an an Input field in Dashboard.

Here is a complete guide re how to use Service Account Key 
https://developers.connectycube.com/reactnative/push-notifications/#android
