### ISSUE TITLE
I can't send message if add emoji

### ISSUE THREAD

**Issue by iKronyck** [ConnectyCube/connectycube-reactnative-samples#32]
I have a problem when send emoji in chat, this problem present if the user send iOS icon or if use the library  node-emoji

i received this error: 
```The string to be encoded contains characters outside of the Latin1 range```

Any solutions for this?

i'm use:
Device: Iphone 11 Simulator
react-native 0.60.5
connectycube-reactnative: 1.8.1
node-emoji: 1.10.0

**Comment by Eramirez06** [comment]
same issue here, please provide a solution for this

**Comment by ccvlad** [comment]
The screenshot from iPhone Simulator (emoji from iOS keyboard works well):
![Screenshot 2020-01-28 at 12 06 28](https://user-images.githubusercontent.com/43810932/73256209-3238bd80-41ca-11ea-83e7-d6bd4481e283.png)

Is it error of the 'node-emoji' or  from the 'connectycube-reactnative'?
It isn't clear where the issue is. Could you provide detailed log?

**Comment by iKronyck** [comment]
Sorry, the problem stay when send the push notification to other user and this ocurred for to conver base64Encode.

This is the response obtained in catch

<img width="658" alt="Captura de Pantalla 2020-01-28 a la(s) 09 36 19" src="https://user-images.githubusercontent.com/12678606/73278888-e2e69300-41b1-11ea-94c6-ff36c71467c4.png">

This is my code for send message and push notification:

![carbon](https://user-images.githubusercontent.com/12678606/73279756-3a393300-41b3-11ea-8ebb-d84ac2e7ae45.png)

**Comment by DaveLomber** [comment]
@iKronyck btw
there are automatic push notifications to offline users when you send a message

it can be enabled at Admin panel, Chat module, Offline Notifications -> ENABLE AUTOMATIC NOTIFICATIONS FOR OFFLINE USERS IN CHAT

so you do not need to initiate them by yourself 

can it work for you?

**Comment by Eramirez06** [comment]
Any way to send the emoji from my app? without activate that fuction?

**Comment by ccvlad** [comment]
The problem with **ConnectyCube.pushnotifications.base64Encode(_emoji_)**.
Try to use custom method to encode emojies to base64 until we will check it.

**Comment by Eramirez06** [comment]
but how to send the push without
*ConnectyCube.pushnotifications.base64Encode(emoji)*
is there any way to send the message if a dont  add *base64Encode* or i just delete the parse from function *base64Encode* in lib?

**Comment by DaveLomber** [comment]
Hi @Eramirez06 
what @ccvlad  is proposing is to try a diff lib/method to get base64 data in ReactNative 

there are many libs in RN to do so, so please just try any other 
e.g. this one or similar 

https://github.com/eranbo/react-native-base64  

`ConnectyCube.pushnotifications.base64Encode(emoji)` is just a wrapper around base64 logic, nothing more

**Comment by Eramirez06** [comment]
ok understood thanks i'll be checking this for update and absolutely thanks for the support guys

**Comment by DaveLomber** [comment]
Hi @Eramirez06 @iKronyck 

Please find React Native SDK 2.1.7 with the mentioned issue addressed 

https://www.npmjs.com/package/react-native-connectycube/v/2.1.7 

Please let us know if there is something else is required in our attention

Thank you!

**Comment by Eramirez06** [comment]
cool tomorrow i'll try it
