### ISSUE TITLE
A sample code without redux

### ISSUE THREAD

**Issue by akshayhalasangi** [ConnectyCube/connectycube-reactnative-samples#33]
Hi Team,
I am able to run the default code sample but I have an issue integrating that in my project. I am not using redux and or flux. Any help will be greatly appreciated.

**Comment by DaveLomber** [comment]
@akshayhalasangi please let us know the following:
- what navigation you use? 
- what code sample you are required - video or chat?
- what you use for states management if not redux?

**Comment by akshayhalasangi** [comment]
@DaveLomber Thanks for the reply,

I'm using react-navigation and I need samples for both video and chat. I should be able to figure out the other one even if I get one of these. I'm a newbie so I don't use any third party library for state management. 

Hoping for a quick reply.

**Comment by DaveLomber** [comment]
@akshayhalasangi  we are going to release new Video Chat code sample soon and w/o redux, will let you know here

re chat - it still will be with Redux cause it's pretty hard to do it without it
So I recommend you to master Redux as it's sometimes pretty hard to build apps without it :)

**Comment by akshayhalasangi** [comment]
@DaveLomber That's sad. I was trying to integrate the chat app As-Is and it was throwing me errors here and there. Since it was not related to ConnectyCube I didn't mention those here. Is there anyway you can help me out here? I need this done ASAP. I've been trying to pick apart the entire thing though.

**Comment by DaveLomber** [comment]
@akshayhalasangi I recommend to use our existing chat sample with Redux 
and take at least one day to learn Redux basics , it's not so many things 

W/o Redux it's really hard to build it..

**Comment by DaveLomber** [comment]
@akshayhalasangi  new Video Chat code sample w/o redux is pushed 
Please check https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat

**Comment by DaveLomber** [comment]
I'm closing this one as Video Chat code sample w/o redux is here already 
and for Chat we do not have such plans in near future
