### ISSUE TITLE
Cannot connect the call

### ISSUE THREAD

**Issue by akshayhalasangi** [ConnectyCube/connectycube-reactnative-samples#39]
Hello there,
I've modified the RNVideoChat code according to my needs and I'm facing this issue while trying to start the call.

`import React from 'react';
import {SafeAreaView, StatusBar} from 'react-native';
import ConnectyCube from 'react-native-connectycube';
import RTCViewGrid from './RTCViewGrid';
import {CallService} from '../services';
import ToolBar from './ToolBar';
import UsersSelect from './UsersSelect';

export default class VideoScreen extends React.Component {
  constructor(props) {
    super(props);

    this.opponentsIds = props.navigation.getParam('opponentsIds');

    this.state = {
      localStream: null,
      remoteStreams: [],
      selectedUsersIds: [],
      isActiveSelect: true,
      isActiveCall: false,
    };

    this._setUpListeners();
  }

  componentWillUnmount() {
    //AuthService.logout();
    CallService.stopCall();
  }

  componentDidUpdate(prevProps, prevState) {
    const currState = this.state;

    if (
      prevState.remoteStreams.length === 1 &&
      currState.remoteStreams.length === 0
    ) {
      CallService.stopCall();
      this.resetState();
    }
  }

 selectUser = userId =>
    this.setState(prevState => ({
      selectedUsersIds: [...prevState.selectedUsersIds, userId],
    })); 

   unselectUser = userId =>
    this.setState(prevState => ({
      selectedUsersIds: prevState.selectedUsersIds.filter(id => userId !== id),
    })); 

  closeSelect = () => this.setState({isActiveSelect: false});

  setOnCall = () => this.setState({isActiveCall: true});

 initRemoteStreams =  opponentsIds => {
    console.log("==============================")
    console.log("selected user :"+JSON.stringify(this.state.selectedUsersIds))
    console.log("initRemoteStreams opponentsIds :"+JSON.stringify(opponentsIds))
    console.log("==============================")
    const emptyStreams = opponentsIds.map(userId => ({
      userId,
      stream: null,
    }));

    console.log("emptyStreams :"+JSON.stringify(emptyStreams))

    this.setState({remoteStreams: emptyStreams});
    console.log("remoteStreams : "+JSON.stringify(this.state.remoteStreams));
  };

  updateRemoteStream = (userId, stream) => {
    this.setState(({remoteStreams}) => {
      const updatedRemoteStreams = remoteStreams.map(item => {
        if (item.userId === userId) {
          return {userId, stream};
        }

        return {userId: item.userId, stream: item.stream};
      });

      return {remoteStreams: updatedRemoteStreams};
    });
  };

  removeRemoteStream = userId => {
    this.setState(({remoteStreams}) => ({
      remoteStreams: remoteStreams.filter(item => item.userId !== userId),
    }));
  };

  setLocalStream = stream => this.setState({localStream: stream});

  resetState = () =>
    this.setState({
      localStream: null,
      remoteStreams: [],
      selectedUsersIds: [],
      isActiveSelect: true,
      isActiveCall: false,
    });

  _setUpListeners() {
     console.log("==============================")
    console.log("in _setUpListeners")
    console.log("==============================")
    ConnectyCube.videochat.onCallListener = this._onCallListener;
    ConnectyCube.videochat.onAcceptCallListener = this._onAcceptCallListener;
    ConnectyCube.videochat.onRejectCallListener = this._onRejectCallListener;
    ConnectyCube.videochat.onStopCallListener = this._onStopCallListener;
    ConnectyCube.videochat.onUserNotAnswerListener = this._onUserNotAnswerListener;
    ConnectyCube.videochat.onRemoteStreamListener = this._onRemoteStreamListener;
  }

  _onCallListener = (session, extension) => {
    console.log("==============================")
     console.log("_onCallListener session :"+JSON.stringify(session));
      console.log("_onCallListener extension :"+JSON.stringify(extension));
      console.log("==============================")
    CallService.processOnCallListener(session).then(stream => {
      const {opponentsIDs, initiatorID, currentUserID} = session;

console.log("==============================")
      console.log("_onCallListener opponentsIDs :"+JSON.stringify(opponentsIDs));
      console.log("_onCallListener initiatorID :"+JSON.stringify(initiatorID));
      console.log("_onCallListener currentUserID :"+JSON.stringify(currentUserID));
console.log("==============================")

      const opponentsIds = [initiatorID, ...opponentsIDs].filter(
        userId => currentUserID !== userId,
      );

      this.initRemoteStreams(opponentsIds);
      this.setLocalStream(stream);
      this.closeSelect();
    });
  };

  _onAcceptCallListener = (session, userId, extension) => {
    this.setOnCall();
  };

  _onRejectCallListener = (session, userId, extension) => {
    CallService.processOnRejectCallListener(userId);
  };

  _onStopCallListener = (session, userId, extension) => {
    const isStoppedByInitiator = session.initiatorID === userId;

    CallService.processOnStopCallListener(userId, isStoppedByInitiator);

    if (isStoppedByInitiator) {
      this.resetState();
    } else {
      this.removeRemoteStream(userId);
    }
  };

  _onUserNotAnswerListener = (session, userId) => {
    CallService.processOnUserNotAnswer(userId);
    this.removeRemoteStream(userId);
  };

  _onRemoteStreamListener = (session, userId, stream) => {
    this.updateRemoteStream(userId, stream);
    this.setOnCall();
  };

  render() {
    const {
      localStream,
      remoteStreams,
      selectedUsersIds,
      isActiveSelect,
      isActiveCall,
    } = this.state;

    const localStreamItem = localStream
      ? [{userId: 'localStream', stream: localStream}]
      : [];
    const streams = [...remoteStreams, ...localStreamItem];

    console.log("localStreamItem :"+JSON.stringify(localStreamItem));
    console.log("streams :"+JSON.stringify(streams));

    CallService.setSpeakerphoneOn(remoteStreams.length > 0);

    return (
      <SafeAreaView style={{flex: 1, backgroundColor: 'black'}}>
        <StatusBar backgroundColor="black" barStyle="light-content" />
        <RTCViewGrid streams={streams} />
        <UsersSelect
          isActiveSelect={isActiveSelect}
          opponentsIds={this.opponentsIds}
          selectedUsersIds={selectedUsersIds}
          selectUser={this.selectUser}
          unselectUser={this.unselectUser}
        />
        <ToolBar
          selectedUsersIds={selectedUsersIds}
          localStream={localStream}
          isActiveSelect={isActiveSelect}
          isActiveCall={isActiveCall}
          closeSelect={this.closeSelect}
          initRemoteStreams={this.initRemoteStreams}
          setLocalStream={this.setLocalStream}
          resetState={this.resetState}
        />
      </SafeAreaView>
    );
  }
}
`

My package.json

`{
  "name": "DigiHealthPatientApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@mapbox/polyline": "^1.1.0",
    "@ptomasroos/react-native-multi-slider": "^1.0.0",
    "@react-native-community/async-storage": "github:react-native-community/react-native-async-storage",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/google-signin": "^3.0.4",
    "@react-native-community/masked-view": "^0.1.6",
    "@react-native-community/netinfo": "^4.6.1",
    "geolib": "^3.2.0",
    "jetifier": "^1.6.5",
    "native-base": "^2.13.8",
    "react": "16.9.0",
    "react-geocode": "^0.2.1",
    "react-native": "0.61.5",
    "react-native-app-intro-slider": "^2.0.1",
    "react-native-autocomplete-input": "^4.1.0",
    "react-native-autogrow-textinput": "^5.3.0",
    "react-native-background-downloader": "^2.3.2",
    "react-native-btr": "^1.1.4",
    "react-native-calendars": "^1.214.0",
    "react-native-collapsible": "^1.5.1",
    "react-native-connectycube": "^2.1.0",
    "react-native-custom-checkbox": "^1.5.2",
    "react-native-custom-snackbar": "^1.0.1",
    "react-native-datepicker": "^1.7.2",
    "react-native-datepicker-dialog": "0.0.9",
    "react-native-device-info": "^5.4.1",
    "react-native-dialog": "^5.6.0",
    "react-native-document-picker": "^3.2.4",
    "react-native-fbsdk": "^1.1.1",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-file-viewer": "^2.0.1",
    "react-native-fs": "^2.16.4",
    "react-native-geocoding": "^0.4.0",
    "react-native-gesture-handler": "^1.5.3",
    "react-native-get-location": "^1.4.2",
    "react-native-google-autocomplete": "^0.1.8",
    "react-native-html-to-pdf": "^0.8.0",
    "react-native-image-crop-picker": "^0.26.1",
    "react-native-image-picker": "^1.1.0",
    "react-native-image-slider": "^2.0.3",
    "react-native-incall-manager": "^3.2.7",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-maps": "^0.26.1",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-material-menu": "^1.0.0",
    "react-native-modal": "^11.5.3",
    "react-native-onesignal": "^3.6.0",
    "react-native-orientation-loading-overlay": "^0.1.6",
    "react-native-print": "^0.6.0",
    "react-native-push-notification": "^3.1.9",
    "react-native-razorpay": "^2.1.31",
    "react-native-reanimated": "^1.3.0",
    "react-native-router-flux": "^4.2.0-beta.1",
    "react-native-safe-area-context": "^0.6.4",
    "react-native-screens": "^2.0.0-beta.1",
    "react-native-search-filter": "^0.1.5",
    "react-native-share": "^2.0.0",
    "react-native-status-bar-height": "^2.4.0",
    "react-native-whc-toast": "^1.0.0",
    "react-navigation": "^1.0.0-beta.21",
    "react-navigation-deprecated-tab-navigator": "^1.2.0",
    "react-redux": "^5.1.1",
    "redux": "^4.0.4",
    "rn-prompt": "^1.0.4"
  },
  "devDependencies": {
    "@babel/core": "7.7.4",
    "@babel/runtime": "7.7.4",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.7.2",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.3",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }
}
`

Any help would be appreciated

![1581614098598](https://user-images.githubusercontent.com/9262835/74464034-d0aa6b80-4eb8-11ea-8238-a3c850c54839.JPEG)

**Comment by DaveLomber** [comment]
It looks like you do not have an active connection to chat, which is used as a signaling in video calls 

Could you please double check it?

**Comment by akshayhalasangi** [comment]
@DaveLomber I was able to solve it. You were right active connection to chat wasn't created
