### ISSUE TITLE
Unable to clone the repo

### ISSUE THREAD

**Issue by HimanshuGajera** [ConnectyCube/connectycube-reactnative-samples#47]
I am getting this error:

Git: fatal: repository 'https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat/' not found

**Comment by DaveLomber** [comment]
Hi @HimanshuGajera 

please try `git clone git@github.com:ConnectyCube/connectycube-reactnative-samples.git`

**Comment by HimanshuGajera** [comment]
I am unable to make video calls using sample app.

How i will be able to make video calls using sample code?
Please advise.

**Comment by ccvlad** [comment]
https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNVideoChat/README.md#quick-start-and-develop

Use real iOS/Android devices instead of simulator/emulator to have active cameras

**Comment by HimanshuGajera** [comment]
I am using actual device, still not able to make calls.
The connecting dial just keeps on buffering and i am getting the following
warning.

**Comment by ccvlad** [comment]
You should have min 2 device and do login by different users on each device, then make a call from User1 to User2 and User2 have to accept an incoming call. Also don't forget to allow requested permissions.

Provide us some helpful information such as logs or steps to reproduce if you would not able to make call. Maybe I have missunderstood you

**Comment by HimanshuGajera** [comment]
At first place,I am not able to login with any of the users then i will
make video calls?


Guide me on this issue and the screenshot i shared is the only log i am
getting.
Nothing in my terminal window.

**Comment by ccvlad** [comment]
I don't see any screenshot. Please attach again

**Comment by HimanshuGajera** [comment]
These are the screenshots :-

**Comment by ccvlad** [comment]
![Screenshot 2020-03-17 at 14 37 05](https://user-images.githubusercontent.com/43810932/76856866-e4047a00-685c-11ea-890c-3cad699f7996.png)

**Comment by HimanshuGajera** [comment]
I was e-mailing you directly from the Gmail app.
Please send the link of github page which screenshot you had sent me.
I will send the screenshots again.

**Comment by ccvlad** [comment]
Just send via [GitHub issues](https://github.com/ConnectyCube/connectycube-reactnative-samples/issues/47).

**Comment by HimanshuGajera** [comment]
These are screenshots:
![Screenshot_20200317-171656_RNVideoChat](https://user-images.githubusercontent.com/62088223/76860491-2344c200-6881-11ea-8fdb-c0485549b4ac.jpg)
![Screenshot_20200317-171646_RNVideoChat](https://user-images.githubusercontent.com/62088223/76860519-2fc91a80-6881-11ea-9926-cc88e6235ef9.jpg)

**Comment by ccvlad** [comment]
`#/connectycube-reactnative-samples/RNVideoChat/src/components/AuthScreen/index.js`

Change `const _onFailLogin = () => {...}`  to `const _onFailLogin = (error = {}) =>`

Then we will see the error

**Comment by HimanshuGajera** [comment]
This is what i'm getting
![Screenshot_20200317-232132_RNVideoChat](https://user-images.githubusercontent.com/62088223/76886044-3322cd00-68a6-11ea-8902-f749aecc4f34.jpg)

**Comment by ccvlad** [comment]
I see that you have changed users' names, seems you have also changed users in config. Make sure that you correctly pointed a [config](https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNVideoChat/src/config.js#L3) on your ConnectyCube app (https://admin.connectycube.com/)

**Comment by HimanshuGajera** [comment]
I didn't get you correctly.
What am i supposed to do?
Should i keep tha names as before or by changing the names i have to dom
some other configurations as well?

And the admin login link you've sent, i can't find anything there because i
have not anable the custome cofiguration option.

**Comment by ccvlad** [comment]
Revert the config file to the [source state](https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNVideoChat/src/config.js) and check again, do not change anything.
You are getting the error cause backend doesn't know your users.

**Comment by HimanshuGajera** [comment]
Okay it is working for me. Thanks !

But how I can change the user name or how I can create a login page and make users to manually add the credentials and connect the page with app.

I didn’t find this info on connectycube guide page.

Please Guide me with this.

**Comment by ccvlad** [comment]
Just change user's name: https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNVideoChat/src/config.js#L15.

Also you are able to create new app on our shared server. Follow the [guide](https://developers.connectycube.com/?id=getting-started).

Then create users via the admin panel or via [user API ](https://developers.connectycube.com/js/authentication-and-users?id=user-signup) and set its to the config file.

**Comment by HimanshuGajera** [comment]
Okay, still not 100% clear to me but seems getable. I'll try and reach out
to you if i face any issues.

Thanks for your time and this useful help.🙏
