### ISSUE TITLE
merge chat with video call not showing incoming call screen

### ISSUE THREAD

**Issue by yogitaV-dev** [ConnectyCube/connectycube-reactnative-samples#49]
Hi.. i merged video call with chat header call button, but incoming call screen not showing.

![1585546400274](https://user-images.githubusercontent.com/62869246/77878651-6ab25180-7276-11ea-90c2-6098a1f01a30.JPEG)

**Comment by ccvlad** [comment]
Hi, @yogitaV-dev

The RN Chat and the RN VideoChat samples have different configs (have pointed on different server's applications). Also The VideoChat Sample has static set with four users when the Chat includes authentication login (can register new users and log in with existed users). I am trying to say you that those React Native samples have not been created to would merged between themselves.

Could you describe what you have done to clear you issue?

**Comment by yogitaV-dev** [comment]
i took chat sample and on chat screen header i added video call button and on that button i redirect to videoscreen which i took from video chat sample its working fine. but how to handle incoming call because from video chat it comes to video screen but when i merged the code my first screen after login is chat dialog screen... so please tell me the way how we can integrate.

**Comment by ccvlad** [comment]
The samples were created to show how to use ConnectyCube SDK with React Native. We didn't connect those samples to simplify each code sample (demo).
You should create you own application using our docs ([auth](https://developers.connectycube.com/js/authentication-and-users), [chat](https://developers.connectycube.com/js/messaging), [videocall](https://developers.connectycube.com/js/videocalling)) and some code from samples.
