### ISSUE TITLE
not able to get group chat history 

### ISSUE THREAD

**Issue by yogitaV-dev** [ConnectyCube/connectycube-reactnative-samples#50]
i checked RNChat with default config i can see the group history but when we try to change config with my app config that time i am not able to see group chat history which i have done

**Comment by Kachanov-dev** [comment]
HI @yogitaV-dev.
Can you get dialogs or is it a problem with receiving messages?

**Comment by ccvlad** [comment]
@yogitaV-dev 
Do you expect to see the history that you have created on default config? Did you change [API's endpoints](https://developers.connectycube.com/js/?id=initialize) in your config?

**Comment by yogitaV-dev** [comment]
> HI @yogitaV-dev.
> Can you get dialogs or is it a problem with receiving messages?

i am facing problem with receiving  messages and i checked with my connectycube  dashboard there also i am getting null with group chat message. and if try with RNChat default config that time i am able to see group chat histroy

**Comment by yogitaV-dev** [comment]
> @yogitaV-dev
> Do you expect to see the history that you have created on default config? Did you change [API's endpoints](https://developers.connectycube.com/js/?id=initialize) in your config?

yes..i change endpoint also and login with my credential and created new group with conversation but when i close the app and open again the app group history not showing. But if i keep the app default config and login with accordingly that time group chat history working fine. i want to say that RNSample chat group history working fine but when i change the config with my app config and try to make group chat... that time chat history not showing when i open the app again

**Comment by ccvlad** [comment]
Can we see what were changed in you config? Are you use our shared server's endpoints?

**Comment by yogitaV-dev** [comment]
> Can we see what were changed in you config? Are you use our shared server's endpoints?

i used my app config  {
  "name": "Rnchat",
  "displayName": "Rnchat",
  "senderID": "594331487245",
  "connectyCubeConfig": [
    {
      "appId": 2022,
      "authKey": "LQHEMpcZEADKMYR",
      "authSecret": "8-Q4zKT7xdhmtW7"
    },
    { "chat": {
      "streamManagement": {
        "enable": true
      }
    },
      "debug": {
        "mode": 1
      } 
    }
  ]
}

**Comment by ccvlad** [comment]
Any errors in your console?

**Comment by yogitaV-dev** [comment]
> Any errors in your console?

no, but in my connectycube account chat history for group  all are showing null

**Comment by Kachanov-dev** [comment]
Hi @yogitaV-dev  
Before sending a message to a group chat, you need to join the chat:
Doc: https://developers.connectycube.com/js/messaging?id=group-chat

**Comment by yogitaV-dev** [comment]
Group chat history working fine now...Thanks

**Comment by yogitaV-dev** [comment]
Thanks for your support now it's working fine..
