### ISSUE TITLE
RNchat sample App.json, Navigator and a lot more is missing

### ISSUE THREAD

**Issue by astroana** [ConnectyCube/connectycube-reactnative-samples#53]
Hello, I am new to connectycube and I am just trying out the samples. the video calling sample works fine, but the chat sample is having error and looking for app.json file and navigator inside src.

![error](https://user-images.githubusercontent.com/48448899/78419540-683a6800-7679-11ea-80e0-913a08292bf9.JPG)

I created an app.json then after that another error message looking for this:

![er2](https://user-images.githubusercontent.com/48448899/78419950-62468600-767d-11ea-8be3-536e7a1d903e.JPG)

and also this

![er2](https://user-images.githubusercontent.com/48448899/78419787-cbc59500-767b-11ea-9943-b89d9de6f78b.JPG)

**Comment by ccvlad** [comment]
Hi, @astroana 

Looks like the Metro server uses cached files from previous build. Try to close your terminal with the Metro server and start React Native build process from scratch.

Execute those commands in your terminal:
1. Clean Metro's server cache from the root of ~/RNChat: `watchman watch-del-all && rm -rf /tmp/metro-bundler-cache-* && rm -rf /tmp/haste-map-react-native-packager-*`
2. Clean android build cache: `cd android && ./gradlew clean && ./gradlew cleanBuildCache`
3. Return to the root folder (RNChat): `cd ../`
3. Run: `npm run android` or `yarn android`

Hope that it will be helpful.

**Comment by astroana** [comment]
I just did and even remove all the cache files inside drive c:/user folder and still the result is the same. I tested the RNChat sample first to make sure. My other projects works fine after running yarn android. I don't think it's the metro server caches because when I ran yarn android on RNchat sample my terminal doesn't show any errors on gradle nor having issue installing the app and Build is always successfull.

**Comment by ccvlad** [comment]
The _app.json_ file does not exist in the RNChat.
**name** and **displayName** imports from _config.json_.
I had been getting the same errors after switch between different projects. Cleaning of all caches had been helping.
I can't reproduce the issue.
Try to clean `~/.npm/_cacache` and `/.react-native-cli/cache`.

**Comment by astroana** [comment]
I already did, tried installing android studio and gradle and nodejs to a new pc. but no luck.

Don't know why the errors still appear only with RNChat.

**Comment by ccvlad** [comment]
Do have `import ... from "./src/services"` or `import ... from "app.json"` in your _~/RNChat/index.js_ ?

**Comment by astroana** [comment]
I just cloned the sample git repo and I did not change anything inside RNChat because I am just trying to test the repo as is, same with RNVideo which works fine without any errors.

**Comment by ccvlad** [comment]
Does the issue still present?

I suggest you to ask React Native team by few reasons:
- The RNChat doesn't have those imports (_"./src/services"_ and _"app.json"_ in **index.js** and ***App.js*)
- Our team can't reproduce the issue.
