### ISSUE TITLE
Push notification is not coming in RNSample chat example...do we need to add any extra things

### ISSUE THREAD

**Issue by yogitaV-dev** [ConnectyCube/connectycube-reactnative-samples#56]

**Comment by ccvlad** [comment]
Nothing clear.
Please describe what you do and what you expect.
1. Steps to reproduce
2. Console log, warnings/errors
3. Environments/platforms
4. Do you use physical devices or simulator/emulator?
5. Does it reproduce in the RNSample code (base code)?

**Comment by yogitaV-dev** [comment]
i am runnig RNChat sample code provided by you, and try to get chat notification when user is offline and somebody doing message in my android device but not getting any notification . i am able to see subscription device in connectycube admin panel  with my app config but if i also try to send notification from admin panel that time also not getting notification and showing 'Success
Gcm channel. Notification has been successfully added to queue'

**Comment by yogitaV-dev** [comment]
also i have created my own app and change app config and add firebase configuration also but not getting chat notification. I tried from adming panel but not getting . i am using android device... is it working in RNChat sample code provided by you or we need to add extra things from our side ?

**Comment by ccvlad** [comment]
Did you follow this [guide](https://developers.connectycube.com/reactnative/push-notifications?id=push-notifications)?

**Comment by yogitaV-dev** [comment]
> Did you follow this [guide](https://developers.connectycube.com/reactnative/push-notifications?id=push-notifications)?

Yes , i followed the same. i want to know that is push chat notification working in your RNChat sample app ? because i am running same code but not able to get chat notification

**Comment by ccvlad** [comment]
Use one report for each issue - https://github.com/ConnectyCube/connectycube-reactnative-samples/issues/59
