### ISSUE TITLE
getMediaDevices

### ISSUE THREAD

**Issue by tihor123** [ConnectyCube/connectycube-reactnative-samples#57]
Whenever I am calling this function I am getting an error.
Type error: cannot read property 'getMediaDevices' of undefined.

  setMediaDevices() {
    return ConnectyCube.videochat.getMediaDevices('videoinput').then((mediaDevices) => {
      this.mediaDevices = mediaDevices;
    }).catch((error)=>{console.log(error)})
  }

**Comment by banshiAnton** [comment]
Hi @tihor123, i think you call this func before you call ConnectyCube.init()
Please make sure that you call ConnectyCube.videochat.getMediaDevices after init sdk (ConnectyCube.init())
https://developers.connectycube.com/reactnative/?id=initialize

**Comment by sjwoodard** [comment]
same issue on RN 0.61.5 on Android -- i didn't test iOS...

the sample works fine by itself, but when i try to implement I get:
```
Possible Unhandled Promise Rejection (id: 4):
TypeError: null is not an object (evaluating 'WebRTCModule.enumerateDevices')
```
and
```
Possible Unhandled Promise Rejection (id: 5):
TypeError: undefined is not an object (evaluating 'params.audio')
```
I've verified permissions are correct

**Comment by tihor123** [comment]
Thanks for the reply. But in my case react-native-webrtc was the problem.
It did not work with latest gradle version. When I downgraded the gradle
version everything worked according to the sample code.

Thank and regards

**Comment by ccvlad** [comment]
@Aakash359 
Are you using a physical iOS device or an iOS simulator?

**Comment by Aakash359** [comment]
> @Aakash359 Are you using a physical iOS device or an iOS simulator?

I am try to running on iOS simulator even i am calling after the (ConnectyCube.init()) function but still not resolved yet, i have downgrade the react-native-connectycube versions also

**Comment by ccvlad** [comment]
iOS simulator does not provide access to camera. You have to use a real device

**Comment by Aakash359** [comment]
> iOS simulator does not provide access to camera. You have to use a real device

Tried with iOS physical device also getting same issues i don't know why any solutions you have ? ... it is perfectly working in Android

**Comment by ccvlad** [comment]
Make sure you've completed the React Native WebRTC setup.

Here is the guide for iOS - https://github.com/react-native-webrtc/react-native-webrtc/blob/HEAD/Documentation/iOSInstallation.md
Reference from our docs - https://developers.connectycube.com/reactnative/videocalling?id=connect-webrtc-lib

**Comment by Aakash359** [comment]
> Make sure you've completed the React Native WebRTC setup.
> 
> Here is the guide for iOS - https://github.com/react-native-webrtc/react-native-webrtc/blob/HEAD/Documentation/iOSInstallation.md Reference from our docs - https://developers.connectycube.com/reactnative/videocalling?id=connect-webrtc-lib

Yes I have setup perfectly everything from doc is this is bug or do i need to change something in native side, i have given all the required permission in info.plist file like camera, microphone.
