### ISSUE TITLE
Video conference sample

### ISSUE THREAD

**Issue by Jempan** [ConnectyCube/connectycube-reactnative-samples#58]
Hi! Just started to play around with ConnectyCube and it looks very promising for my use case. Is there any chance you can add a video conference sample for react native?

**Comment by DaveLomber** [comment]
@Jempan We will definitely release it in the nearest future 

For now the best way is:
- check Web conference sample https://github.com/ConnectyCube/connectycube-web-samples/tree/master/videochat-conf . Live demo is available here http://teatalk.connectycube.com
- get existing P2P video chat sample for RN https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat and try to migrate it to conf API by yourself, it should be pretty easy as with new SDK 3.0 we unified the P2P and Conf API, so it's pretty the same. 

New conf API doc is available here https://developers.connectycube.com/js/videocalling-conference  - it's the same for Web and RN, no differences

**Comment by Jempan** [comment]
Thanks a lot for the information @DaveLomber! Looking forward to the RN sample 👏
