### ISSUE TITLE
RNChat sample code push notification working only when app is in background... but if i change the appConfig with my application config that time not able to get push notification even app is in background ...i already posted the one issue before...Please reply the same

### ISSUE THREAD

**Issue by yogitaV-dev** [ConnectyCube/connectycube-reactnative-samples#59]
I am running the RNChat sample code and notification working only when app is in background and if app is killed or in forground that time not working .
And i checked the same app with my config that time i am not able to get push notification when app is in background only.

also i put the firebase google-json file and firebase configuration but still not getting any notification.. please help us...  i already posted the one issue related to this.. but didn't get any reply from your side.
Please reply on the same

**Comment by Kachanov-dev** [comment]
Hi @yogitaV-dev,  could you please tell me devices you check push notifications?

**Comment by yogitaV-dev** [comment]
i am 

> Hi @yogitaV-dev, could you please tell me devices you check push notifications?

i am running on android device.. please help to resolve this

**Comment by Kachanov-dev** [comment]
> i am
> 
> > Hi @yogitaV-dev, could you please tell me devices you check push notifications?
> 
> i am running on android device.. please help to resolve this

Which Android ?  Nexus, Pixel, Samsung or Vivo  and please tell me model devices.

**Comment by yogitaV-dev** [comment]
> > i am
> > > Hi @yogitaV-dev, could you please tell me devices you check push notifications?
> > 
> > 
> > i am running on android device.. please help to resolve this
> 
> Which Android ? Nexus, Pixel, Samsung or Vivo and please tell me model devices.

Moto G4 Plus, oppo f1 plus

**Comment by yogitaV-dev** [comment]
Also i just tried to replace  RNChat app config with my app config.. but not getting notification 

My app config is below

{
  "name": "Rnchat",
  "displayName": "Rnchat",
  "senderID": "594331487245",
  "connectyCubeConfig": [
    {
      "appId": 2022,
      "authKey": "LQHEMpcZEADKMYR",
      "authSecret": "8-Q4zKT7xdhmtW7"
    },
    { "chat": {
      "streamManagement": {
        "enable": true
      }
    },
      "debug": {
        "mode": 1
      } 
    }
  ]
}

**Comment by ccvlad** [comment]
for foreground notification you should use local notification. Describe your steps when you are able to receive push notification and when you are expecting but it fails.

> Also i just tried to replace RNChat app config with my app config.. but not getting notification
> 
> My app config is below
> 
> {
> "name": "Rnchat",
> "displayName": "Rnchat",
> "senderID": "594331487245",
> "connectyCubeConfig": [
> {
> "appId": 2022,
> "authKey": "LQHEMpcZEADKMYR",
> "authSecret": "8-Q4zKT7xdhmtW7"
> },
> { "chat": {
> "streamManagement": {
> "enable": true
> }
> },
> "debug": {
> "mode": 1
> }
> }
> ]
> }

**senderID** the same with [the Sample RNChat's config](https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNChat/config.json), but **appId** and other not. Seems you didn't end configuration.

**Comment by yogitaV-dev** [comment]
> for foreground notification you should use local notification. Describe your steps when you are able to receive push notification and when you are expecting but it fails.
> 
> > Also i just tried to replace RNChat app config with my app config.. but not getting notification
> > My app config is below
> > {
> > "name": "Rnchat",
> > "displayName": "Rnchat",
> > "senderID": "594331487245",
> > "connectyCubeConfig": [
> > {
> > "appId": 2022,
> > "authKey": "LQHEMpcZEADKMYR",
> > "authSecret": "8-Q4zKT7xdhmtW7"
> > },
> > { "chat": {
> > "streamManagement": {
> > "enable": true
> > }
> > },
> > "debug": {
> > "mode": 1
> > }
> > }
> > ]
> > }
> 
> **senderID** the same with [the Sample RNChat's config](https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNChat/config.json), but **appId** and other not. Seems you didn't end configuration.

Thanks
