### ISSUE TITLE
Duplicate/Unsent messages when using two accounts

### ISSUE THREAD

**Issue by ethanx94** [ConnectyCube/connectycube-reactnative-samples#61]
Description:
When testing against two of my own accounts, I send a message from one account. Logged out. Then logged back in as my other account and send a message. The message from the second account appears to have sent twice. 

However when exiting and reopening the app (or switching accounts once more), it did not appear to send at all.

Workaround:
Close and reopen the app after signing out and signing in as another user.

**Comment by Kachanov-dev** [comment]
Thank you for the bug report! We will fix it with the next update.

**Comment by ccvlad** [comment]
Please create a new issue if the problem still exist.
