### ISSUE TITLE
onStop extension is received mutated

### ISSUE THREAD

**Issue by whenmoon** [ConnectyCube/connectycube-reactnative-samples#66]
If an opponent stops a call, I am expecting to be able to receive an object they pass to `session.stop(extension)` inside my onStop listener.

I pass an object to `session.stop(myObject)`:

`stopCall(session, { stopType: STOP_TYPE_TIME_OUT });`

```javascript
const stopCall = (session, extension = {}) => {
  session.stop(extension);
};
```
Then on the other opponents end inside the onStop listener I receive the extension: 
```javascript
ConnectyCube.videochat.onStopCallListener = (session, id, extension) => {
  console.log(extension);
};
```
However the extension object received looks like this:
<img width="1118" alt="Screenshot 2020-04-26 at 14 28 12" src="https://user-images.githubusercontent.com/33122888/80421204-652f4200-88dc-11ea-92c2-1d9ea80b299d.png">

It is not the same object I sent but the properties are buried in there somewhere.
It is not a plain object like it is when I follow the same pattern but with `session.call(myObject)`.

How can I receive the extension I sent like when using `session.call({})` ?

**Comment by banshiAnton** [comment]
Hi @whenmoon, I will test the code and let you know

**Comment by banshiAnton** [comment]
I have tested on sdk 2.1.6 and all works well.
Please can you provide sdk version and you extension object example (it is { stopType: STOP_TYPE_TIME_OUT }
)
what is variable type of STOP_TYPE_TIME_OUT

**Comment by whenmoon** [comment]
Hi @banshiAnton thanks for the quick reply - I am using SDK version ^1.8.1 and type of STOP_TYPE_TIME_OUT is `string`

**Comment by banshiAnton** [comment]
Hi @whenmoon as fast solution try extension with minimum 2 props
for example 
```javascript
const extension = { stopType: STOP_TYPE_TIME_OUT, props: '1' }
session.stop(extension);
```

**Comment by whenmoon** [comment]
Hi @banshiAnton, thank you ok I will try that - in the meantime I tried updating to a new SDK as you said you had it working fully on v2.1.6, but I ran in to this problem:

https://github.com/ConnectyCube/connectycube-reactnative-samples/issues/68

Any ideas what could be the problem here?

**Comment by banshiAnton** [comment]
Out dev team start investigate that issue

**Comment by whenmoon** [comment]
Hi @banshiAnton I resolved the above issue and got this working correctly on v3.0.1, thanks for your help!
