### ISSUE TITLE
Customizing notifications

### ISSUE THREAD

**Issue by sjwoodard** [ConnectyCube/connectycube-reactnative-samples#69]
I'm trying to access the `localNotification` config options in https://github.com/zo0r/react-native-push-notification. I'm working based on your `PushNotificationService` in the sample, but I can't find where to add these options:
```
PushNotification.localNotification({
  bigText: "My big text",
  subText: "This is a subText",
  vibration: 300,
  ongoing: true,
  ignoreInForeground: true,
});
```

**Comment by banshiAnton** [comment]
Hi @sjwoodard, in PushNotificationService we user  https://github.com/zo0r/react-native-push-notification https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNChat/src/services/push-notification.js#L1

**Comment by ccvlad** [comment]
Closed due to inactivity, please re-open if the issue is still persists
