### ISSUE TITLE
Loudspeaker not Working in VideoChat

### ISSUE THREAD

**Issue by Pranav-munna** [ConnectyCube/connectycube-reactnative-samples#7]
How can I enable/use Loudspeaker in my phones loudspeaker for making the video call.
currently unable to use the loudspeaker option, even in the sample cod provided

**Comment by ccvlad** [comment]
We have not implemented this ability in our sample.
Use [react-native-incall-manager](https://github.com/react-native-webrtc/react-native-incall-manager)
`InCallManager.setKeepScreenOn(true)` to ON ([see details](https://github.com/react-native-webrtc/react-native-incall-manager#api))

**Comment by Pranav-munna** [comment]
It is not working

**Comment by ccvlad** [comment]
Please ask [react-native-webrtc team](https://github.com/react-native-webrtc/react-native-incall-manager/issues) since we don serve the **react-native-webrtc/react-native-incall-manager** package.
