### ISSUE TITLE
Full chat and video call sample code (Without redux) required for my existing project

### ISSUE THREAD

**Issue by shaheenshaikh6** [ConnectyCube/connectycube-reactnative-samples#72]
Hello Team,

I've found this wonderful Chat call API .I checked the sample code The video call sample code is easy to integrate in my existing application code but the chat sample code using Redux. I need simple chat call without redux, so that i can integrate it with my existing project code.Please provide if possible..

Thanks
Shaheen

**Comment by ccvlad** [comment]
We have rewritten code w/o redux, so I close the issue
