### ISSUE TITLE
Unhandled Promise rejection Error in Auth Screen of RNVideoChat

### ISSUE THREAD

**Issue by mayanksaurabh** [ConnectyCube/connectycube-reactnative-samples#74]
`Possible Unhandled Promise Rejection (id: 0):
SyntaxError: JSON Parse error: Unexpected EOF
parse@[native code]
processAjaxError@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:166392:63
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:166375:36
tryCallOne@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:28865:16
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:28966:27
_callTimer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:32405:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:32441:19
callImmediates@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:32659:33
callImmediates@[native code]
__callImmediates@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2719:35
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2505:34
__guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2702:15
flushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2504:21
flushedQueue@[native code]
callFunctionReturnFlushedQueue@[native code]`

![Screenshot from 2020-05-10 12-41-18](https://user-images.githubusercontent.com/19463877/81493142-9126cc00-92bb-11ea-9c2e-d6d5d4753051.png)
This is the error coming when tried to log in from auth screen using the physical android device and running the app.

**Comment by mayanksaurabh** [comment]
`{"data": {"application_id": 2296, "auth_key": "GsxmV7rzLaTM3-u", "nonce": 7111, "signature": "84781d6ab1d6fbc302d0203031e60a746448c849", "timestamp": 1589095967, "user": {"login": "videouser4", "password": "videouser4"}}, "type": "POST", "url": "https://api.connectycube.com/session.json"}
`
This is the JSON for the connectycube session api. The json is valid . Checked on JSON formatter but there is JSON parse error from the API.
![Screenshot from 2020-05-10 13-05-00](https://user-images.githubusercontent.com/19463877/81493564-e0223080-92be-11ea-8e71-465da3d195d9.png)

**Comment by ccvlad** [comment]
Seems you have changed a config (the config points on other appId). Did you create users and add its to the config too? Does the error present with the [default config](https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNVideoChat/src/config.js)?

The JSON parse error comes from response. I can't see why. The ConnectyCube.createSession() method fails and can't parse an error object.

**Comment by ccvlad** [comment]
Closed due to inactivity. Please re-open if the issue is still persists.
