### ISSUE TITLE
search functionality for private chat.

### ISSUE THREAD

**Issue by KadambariN** [ConnectyCube/connectycube-reactnative-samples#75]
Does search functionality work for private chat. 
Request -> https://api.connectycube.com/chat/search.json {"data": {"chat_dialog_ids": "here I am sending dialog id (only one)", "search_text": "Hello"}, "type": "GET", "url": "https://api.connectycube.com/chat/search.json"}

Response -> {"dialogs": [], "messages": [], "users": []} 
I am getting this response for private chat i.e. empty response and for group chat search is working fine.

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
