### ISSUE TITLE
After clear chat history for specific user then apply search for the same that time search is giving result for text which is already deleted by clear chat 

### ISSUE THREAD

**Issue by yogitaV-dev** [ConnectyCube/connectycube-reactnative-samples#77]
ConnectyCube.chat.message
      .delete(messagesIds, params)
      .then(result => {
        // alert("deleted message" + result)      })
      .catch(error => { alert("error-" + JSON.stringify(error)) });

after applying this all chat item cleared then applying for the search it shows result for deleted text

    searchData = await ConnectyCube.chat.search(params);

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
