### ISSUE TITLE
WebSocket ECONNERROR wss://chat.connectycube.com:5291

### ISSUE THREAD

**Issue by sjwoodard** [ConnectyCube/connectycube-reactnative-samples#78]
I just started receiving the following errors:
```
WebSocket ECONNERROR wss://chat.connectycube.com:5291 errors
Connection is not offline
```
The ConnectyCube admin UI is up, but going slowly. Is there a problem with the backend?

**Comment by sjwoodard** [comment]
I just received a 502 gateway timeout on the CC admin website, so I'm guessing this is a backend issue.

**Comment by DaveLomber** [comment]
@sjwoodard 

Hi 

Thank you for contacting ConnectyCube 

There was an outage with ConnectyCube Chat Service.
We received a huge spike in CPU load in ConnectyCube Chat Service at Shared instance in ~4h ago, 
which caused a performance degradation and in the end - service down 

For now - ConnectyCube Chat Service is restored, 
we are closely monitoring all the services  
and the team is analysing the situation to apply all the required remedies 

Sorry of any inconvenience 

Should you have any questions - please let us know 

ConnectyCube team

**Comment by sjwoodard** [comment]
Thanks for the update
