### ISSUE TITLE
Lost sound once the screen is turned off

### ISSUE THREAD

**Issue by masmerino13** [ConnectyCube/connectycube-reactnative-samples#79]
Hi CN Team,

We are pretty close to have our app ready to be published, but, now we are having an issue and well, if you have any idea on how to fix that, will be, appreciated.

Well, basically, the issue is when the user is in a call, if the screen is turned off, audio/microphone are lost, yeah, the user can't hear anything and it can't be heard either, this is still happening to us on Samsung S7, Android 8. Working well on Android 9

Any idea about how to fix that is very welcome.

Regards

**Comment by ccvlad** [comment]
Hi, @masmerino13 

Thank you for the reported issue. We have not known about the problem. Need to check.

Few questions.
What you mean about "screen turned off"? Is it device lock state or work of proximity sensor?
Do you know any devices with the issue instead of S7 on Android 8? What the model on your device with Android 9?

Thanks!

**Comment by masmerino13** [comment]
*What you mean about "screen turned off"? Is it device lock state or work of proximity sensor?*
- Is the device lock state

*Do you know any devices with the issue instead of S7 on Android 8? What the model on your device with Android 9?*
By now, we found that only happen on Samsung S7 (Android 8), also tested on Samsung S8 (Android 9) and working well there

This is why we are not pretty sure what's going on.

**Comment by ccvlad** [comment]
OK! Anyway, thank you for the information. We will let you know about news after we would manage to catch the problem.

**Comment by masmerino13** [comment]
Thank you @ccvlad ,

Any help will be very welcome!

**Comment by ccvlad** [comment]
Currently, we have not been able to reproduce the bug. I am going to close the issue. Please, create a new issue if the problem still exist.
