### ISSUE TITLE
unable to retrieve audio devices

### ISSUE THREAD

**Issue by Pranav-munna** [ConnectyCube/connectycube-reactnative-samples#8]
unable to retrieve audio devices
```
getAudioDevices() {
		return new Promise((resolve, reject) => {
				ConnectyCube.videochat.getMediaDevices('audiooutput').then(devices => {
					console.log('responces audio'+devices);
				devices ? resolve(devices) : reject();
			});
		});
	}
```
this code returns nothing where as if i mentioned  "videoinput" instead of  "audiooutput" it returnes two objects

**Comment by ccvlad** [comment]
You are able to get 'videoinput' and 'audioinput' (it means front and camera from 'videoinput' and microphone from 'audioinput').
getMediaDevices() without params will return all input media devices.

**Comment by ccvlad** [comment]
Was the info helpful for you?

**Comment by ccvlad** [comment]
Closing the issue as resolved. Please raise a separate issue in case of any other questions.
