### ISSUE TITLE
onCallListener called but onRemoteStreamListener is not

### ISSUE THREAD

**Issue by whenmoon** [ConnectyCube/connectycube-reactnative-samples#83]
I have the following code where the `onCallListener` callback if fired, but the `onRemoteStreamListener` is not:

```javascript
    try {
      const connectyCubeSession = await createSession();
      ConnectyCube.init(...getConfig(connectyCubeSession.token));
      ConnectyCube.videochat.onCallListener = (session, extension) => {
      // this is called when an incoming call occurs
        store.dispatch(incomingCall(session, extension));
      }
      ConnectyCube.videochat.onRemoteStreamListener = (...args) => {
      // this call back is never called when an incoming call occurs
      }
      ConnectyCube.videochat.onSessionConnectionStateChangedListener = (...args) => {
        store.dispatch(connectionStateChange(...args));
      };
      const connectyCubeUserProfile = await logInToConnectycube(userCredentials);
      store.dispatch(userData({ connectyCubeUserProfile }));
      await connectToChat(connectyCubeSession, connectyCubeUserProfile);
    } catch (error) {
```

I am running this code when a HeadlessJS task is triggered in the background on Android. The session and extension are received by the `onCallListener` but for some reason a remote stream is never received.  I have tried moving the listeners to after the SDK is connected to chat, but it makes no difference. What could be the problem?

I'm using RN v 0.61.4 and "react-native-connectycube": "^3.0.1",

Thanks.

**Comment by banshiAnton** [comment]
Hi @whenmoon do you accept the call in onCallListener ?

**Comment by whenmoon** [comment]
Actually that's a good point - this particular code is for a new user journey / call answer flow that is triggered by a notification button press.

So the call has to be accepted for the remote stream listener to be triggered?

**Comment by DaveLomber** [comment]
@whenmoon correct
the real streams exchange happens after the remote party accepted the call

**Comment by whenmoon** [comment]
Ok got it - thanks that must be the problem. I'll close the issue then cheers.

**Comment by masihurmaruf** [comment]
hi @whenmoon i am also having the similar problem. Can you please share how you have solved it?
