### ISSUE TITLE
Bad Authentication data. Unauthorized on remote side. Status: 404.With empty response

### ISSUE THREAD

**Issue by abdallahasswad** [ConnectyCube/connectycube-reactnative-samples#88]
Hi,

I'm using ConnectyCube.users.signup(userProfile)

```
const userProfile = {
    login: "test.user",
    password: "12345678",
    email: "test@hotmail.com",
    full_name: "Test User",
  };
```

and the account is created successfully.

I'm trying to login with the account created but i'm receiving error code 422 "Bad Authentication data. Unauthorized on remote side. Status: 404.With empty response".

```
const userCredentials = { login: "test.user", password: "12345678" };
ConnectyCube.login(userCredentials)
.then((user) => {
     console.log("success")
 })
.catch((error) => {
    console.log("failed")
 });
```

can anyone help me solving this issue ?

Thank you guys.

**Comment by DaveLomber** [comment]
@abdallahasswad did you enable custom identity provider? 
https://developers.connectycube.com/guides/custom-identity-provider

seems yes

If you are using it then you do not need to sign up the users
Just use a login, and the credentials will be validated against your external user base

**Comment by abdallahasswad** [comment]
@DaveLomber 
i've checked my ConnectyCube account and custom identity provider is enabled.
i've enabling it before just to test something but actually i never use it.
My problem was solved after disabling it.

Thank you.
