### ISSUE TITLE
Firebase authentication

### ISSUE THREAD

**Issue by sshvaiko** [ConnectyCube/connectycube-reactnative-samples#93]
Hello!

Do you support only Firebase phone provider or all providers? I would like to use Facebook and Apple.
Can you show me an example?

Thanks,
Stan

**Comment by DaveLomber** [comment]
Hi @sshvaiko 
We have a built in integration with Firebase phone provider

Also we have Facebook sign in support (not Firebase Facebook but just Facebook)

Does it work in your case?

**Comment by sshvaiko** [comment]
Hi @DaveLomber! Thank you for your answer.

Not really because I'm going to use more providers from Firebase (Google, for example), I think it would be awesome to have an integration with all Firebase providers.

What is the best option in my case? Create a new Connecty Cube user via API when someone registered on the app?

**Comment by DaveLomber** [comment]
@DaveLomber  yes that's right - create a ConnectyCube user via API when someone registered on the app

either login+pwd or email+pwd required, 
so you can use some sequence here
