### ISSUE TITLE
Cordova push notifications no work on background

### ISSUE THREAD

**Issue by Oscarato** [ConnectyCube/connectycube-reactnative-samples#94]
I have a problem with the push notifications. The notificatios arrived fine with the app is running and when the app is on foreground. But on background o app killed, the notifications are not handled by the system, nothing happens. I make test from firebase console and work, but from ConnectyCube console says the message arrived, but in the app nothing happens.

**Comment by ccvlad** [comment]
Duplicate issue - https://github.com/ConnectyCube/connectycube-cordova-samples/issues/4
