### ISSUE TITLE
Can we make a simple Audio only call?

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#98]
I want to be able to provide high quality audio calls that only require minimum internet speed/bandwidth.

I want to give the users an option to Audio call (no video).

How is this done?

**Comment by Kachanov-dev** [comment]
Hi @stephanoparaskeva.
The  ConnectyCube SDK has the "muteVideo && unmuteVideo" methods.
After receiving the local stream, you need to call the method  `this._session.muteVideo ()`

**Comment by stephanoparaskeva** [comment]
> Hi @stephanoparaskeva.
> The ConnectyCube SDK has the "muteVideo && unmuteVideo" methods.
> After receiving the local stream, you need to call the method `this._session.muteVideo ()`

Is this as good as an actual audio call? it sounds a little bit hacky.

There needs to be a way to start an audio call from the begging rather than just muting video...

**Comment by Kachanov-dev** [comment]
> > Hi @stephanoparaskeva.
> > The ConnectyCube SDK has the "muteVideo && unmuteVideo" methods.
> > After receiving the local stream, you need to call the method `this._session.muteVideo ()`
> 
> Is this as good as an actual audio call? it sounds a little bit hacky.
> 
> There needs to be a way to start an audio call from the begging rather than just muting video...

If you are using conferences (Janus):
 - You can pass parameter `mediaParams={video: false}`, but you cannot re-enable the video.
If you are using WebRTC (p2):
- Specify the session type `ConnectyCube.videochat.CallType. AUDIO` more information - [Create video session](https://developers.connectycube.com/js/videocalling?id=create-video-session)

**Comment by stephanoparaskeva** [comment]
> > > Hi @stephanoparaskeva.
> > > The ConnectyCube SDK has the "muteVideo && unmuteVideo" methods.
> > > After receiving the local stream, you need to call the method `this._session.muteVideo ()`
> > 
> > 
> > Is this as good as an actual audio call? it sounds a little bit hacky.
> > There needs to be a way to start an audio call from the begging rather than just muting video...
> 
> If you are using conferences (Janus):
> 
> * You can pass parameter `mediaParams={video: false}`, but you cannot re-enable the video.
>   If you are using WebRTC (p2):
> * Specify the session type `ConnectyCube.videochat.CallType. AUDIO` more information - [Create video session](https://developers.connectycube.com/js/videocalling?id=create-video-session)

What if you are using standard 1-to-1 calls?

Is there any chance the ConnectyCube team can introduce a standard Audio Call, like they have for Video Call, so they can be separate and optimised. Especially for when you are not using conferences (janus) and only using standard.

**Comment by stephanoparaskeva** [comment]
>   If you are using WebRTC (p2):
> * Specify the session type `ConnectyCube.videochat.CallType. AUDIO` more information - [Create video session](https://developers.connectycube.com/js/videocalling?id=create-video-session)

That's really good.
If you can do this `ConnectyCube.videochat.CallType. AUDIO` to initiate 1-to-1 audio call, why did you not say this originally?

**Comment by ccvlad** [comment]
@stephanoparaskeva 
For first, tell us what type of calls are you going to use?
We have video/audio calls based on WebRTC (peer-to-peer). [Sample](https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat).
And conference calls based on Janus technology (one user create a room and invites others). [Sample](https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChatConf)

**Comment by ccvlad** [comment]
Here the docs:
- https://developers.connectycube.com/js/videocalling
- https://developers.connectycube.com/js/videocalling-conference

My team-mate was explained you about the Conference calls:
- you are able to get and send only audio stream when call **session.getUserMedia(params)** with **{video: false}** in params
- but the best way is set mute after call, cause you won't transport video track ("0" bytes sends) and can switch-on the video when you want

**Comment by stephanoparaskeva** [comment]
> Here the docs:
> 
> * https://developers.connectycube.com/js/videocalling
> * https://developers.connectycube.com/js/videocalling-conference
> 
> My team-mate was explained you about the Conference calls:
> 
> * you are able to get and send only audio stream when call **session.getUserMedia(params)** with **{video: false}** in params
> * but the best way is set mute after call, cause you won't transport video track ("0" bytes sends) and can switch-on the video when you want

This is very informative. Close as per solution. Thanks!
