### ISSUE TITLE
Any way to send IOS/Android notifications via ConnectyCube?

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-reactnative-samples#99]
If I want to send push notifications, can I do this just using ConnectyCube alone, how does this compare to something like AWS SNS (Simple Notification Service)?

I want to send Mobile Notifications so user can see chat messages on their lock screen or ones that pop up.

* Should this be used with something like SNS if connectycube has this?
* Do we need 'react-native-push-notifications'?
* Can you set up a timed notification reminder. Eg  on August 5th at 3:30 send User B a notification?

**Comment by banshiAnton** [comment]
Hi @stephanoparaskeva, follow this guide https://developers.connectycube.com/reactnative/push-notifications
You need to use react-native-push-notifications lib or other to receive push
Create custom push event https://developers.connectycube.com/js/push-notifications?id=send-push-notifications

**Comment by banshiAnton** [comment]
You can create scheduled push https://developers.connectycube.com/server/push_notifications?id=create-event

**Comment by stephanoparaskeva** [comment]
> Hi @stephanoparaskeva, follow this guide https://developers.connectycube.com/reactnative/push-notifications
> You need to use react-native-push-notifications lib or other to receive push
> Create custom push event https://developers.connectycube.com/js/push-notifications?id=send-push-notifications

Both of these just show me this:
<img width="1013" alt="Screenshot 2020-07-21 at 09 49 41" src="https://user-images.githubusercontent.com/40718272/88033654-87c9a380-cb37-11ea-8985-e1c87f43454f.png">

**Comment by banshiAnton** [comment]
![Screenshot from 2020-07-21 11-54-19](https://user-images.githubusercontent.com/20343723/88034140-eea38880-cb48-11ea-89ef-31539ed0bd52.png)

**Comment by stephanoparaskeva** [comment]
Oh that is weird. It doesn't seem to work in Brave Browser but it does work in chrome. That's weird, isn't it

**Comment by DaveLomber** [comment]
@stephanoparaskeva could you please tell more about what's Brave Browser?
Have not used it much, but curious

**Comment by stephanoparaskeva** [comment]
> @stephanoparaskeva could you please tell more about what's Brave Browser?
> Have not used it much, but curious

Brave Browser is an internet browser that uses Google Chrome's engine but has security features. Just think of it as another version of Google Chrome. This is the website https://brave.com/ 

On my brave browser whenever I visit https://developers.connectycube.com/js/push-notifications?id=send-push-notifications
I get
<img width="687" alt="Screenshot 2020-07-21 at 13 39 26" src="https://user-images.githubusercontent.com/40718272/88055908-9f188900-cb57-11ea-9637-a466ffcb192e.png">


But on chrome I get:
<img width="1013" alt="Screenshot 2020-07-21 at 13 39 53" src="https://user-images.githubusercontent.com/40718272/88055945-ae97d200-cb57-11ea-9362-d0b9efd8aef0.png">


I'm not sure why but I am just letting you know. My questions that I asked were solved so thank you all!
